### ISSUE TITLE
hold

### ISSUE THREAD

**Issue by khrameev** [sipsorcery/sipsorcery#1]
what about hold?

**Comment by sipsorcery** [comment]
?

**Comment by khrameev** [comment]
how can i hold call?

**Comment by sipsorcery** [comment]
If you want to it with SIP signalling (it can also be done by simply switching the audio) you send an in-dialogue INVITE request with an "a=sendonly" appended to the SDP. See https://tools.ietf.org/html/rfc5359#page-6 for an example.
