### ISSUE TITLE
How to Hold/unHold?

### ISSUE THREAD

**Issue by daichan4649** [sipsorcery/sipsorcery#100]
Very nice library. I am grateful.

I don't know how to implement Hold/unHold function. Please let me know if you have an c# example. I am using [SIPSorcery (3.6.0)](https://www.nuget.org/packages/SIPSorcery/) by NuGet.

[Music on Hold (RFC7088)](https://tools.ietf.org/html/rfc7088)

The same topic is in stackoverflow but page not found...
[how-to-hold-sipsorcery-voip-call-in-c](https://stackoverflow.com/questions/42872202/how-to-hold-sipsorcery-voip-call-in-c)

Pardon my broken English.

**Comment by sipsorcery** [comment]
Call hold [example](https://sipsorcery.github.io/sipsorcery/articles/callhold.html) now available.
