### ISSUE TITLE
Transfer a received call

### ISSUE THREAD

**Issue by rodolphopedra** [sipsorcery/sipsorcery#101]
If I receive a call, I use the "m_uas".

How do i transfer this call without a new call, only transfering the received?

Asterisk use 1 channel for the received call. Occurs in same cases that exists the limit 1 for calls, so another call is not possible, only transfering the active call for another extension...

Sorry my english!!!

**Comment by sipsorcery** [comment]
I've added a new [example program](https://github.com/sipsorcery/sipsorcery/tree/master/examples/CallTransferServer) that transfers a received call to an Asterisk server. Also added brief explanatory [article](https://sipsorcery.github.io/sipsorcery/articles/calltransferserver.html).

If it's not what you had in mind feel free to re-open the issue.
