### ISSUE TITLE
ParseSIPURI does not fail on badly formatted IPv6 SIPURI

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#112]
according to RFC5118 (referencing RFC3261) IPv6 Address must be bracketed in SIPURI.
Providing a sipuri-string without brackets does not throw SIPValidationException.
Same goes for IPv6 mapped IPv4 addresses

XUnit-Test
```

//rj2: should throw exception
Assert.Throws<SIPValidationException>(() => SIPURI.ParseSIPURI("sip:user1@2a00:1450:4005:800::2004"));//ipv6 host without mandatory brackets
Assert.Throws<SIPValidationException>(() => SIPURI.ParseSIPURI("sip:user1@:::ffff:127.0.0.1"));//ipv6 with mapped ipv4 localhost
//rj2: should/does not throw exception
sipURI = SIPURI.ParseSIPURI("sip:[::ffff:127.0.0.1]");
Assert.True(sipURI.Host == "[::ffff:127.0.0.1]", "The SIP URI host was not parsed correctly.");

```

**Comment by sipsorcery** [comment]
I agree with the first two cases but how is the URI below invalid?

````
sip:[::ffff:127.0.0.1]
````

**Comment by sipsorcery** [comment]
#113 fixes first two cases. I'll leave the PR unmerged pending clarification on previous question.

**Comment by rj2Skipper** [comment]
> I agree with the first two cases but how is the URI below invalid?
> 
> ```
> sip:[::ffff:127.0.0.1]
> ```

it isn't invalid
my comment is misleading!?
"should not and does not throw exception"

Ralf

**Comment by sipsorcery** [comment]
Thanks for clarification (I read comment as "should and does not throw exception").
