### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by rodolphopedra** [sipsorcery/sipsorcery#115]
Hot to make a call using WebSocket?

**Comment by sipsorcery** [comment]
I'll need to add a web socket client channel to enable this.

Do you have an example of the SIP Server software or service you are trying to call over a web socket?

**Comment by rodolphopedra** [comment]
I use an Asterisk server

**Comment by sipsorcery** [comment]
Client web socket connections are now supported via the `SIPClientWebSocketChannel` class.

Quick way to test:

  - Start the user agent server example:

````
examples\UserAgentServer>dotnet run
````

  - Call it with the user agent client example:

````
examples\UserAgentClient>dotnet run -- 127.0.0.1;transport=wss
````
