### ISSUE TITLE
Softphone sample does not support the latest

### ISSUE THREAD

**Issue by daichan4649** [sipsorcery/sipsorcery#117]
Very nice library. I am so grateful.

Are you planning to keep up with the latest maintenance?
Please let me know if you have a plan.
Currently, it corresponds to the old version (3.5.0).

The Softphone sample logic is very helpful, so be sure to keep it up to date.

Pardon my broken English.

**Comment by sipsorcery** [comment]
Yes the softphone sample will be kept up to date. #92 is also about adding new features to the softphone. I'm currently working on these two issues.

**Comment by daichan4649** [comment]
Thanks! I will continue to support you.

**Comment by sipsorcery** [comment]
On commit dbf760e4a6f6aae4f30061321a1db387404df5c2 the softphone project is using the most recent [4.0.3-rc NuGet package](https://www.nuget.org/packages/SIPSorcery/4.0.3-rc).

There will be more work done on the softphone in the coming week or two but the version on that commit should be reasonably stable.
