### ISSUE TITLE
Client is not registered

### ISSUE THREAD

**Issue by getsok** [sipsorcery/sipsorcery#118]
Hi!
First) tell me why SoftPhone stops sending Register message?
If you send the Register message a third time, the client will receive a 200 OK message(In the AuthResponseReceived event, I call ServerResponseReceived and the client registers).

![1](https://user-images.githubusercontent.com/36110367/70220919-71153e80-1758-11ea-807b-28e30e1805b9.JPG)

Second) By sending the first 401 P-CSCF, the UE forces it to send REGISTER with IMPI to the Authenticate SIP-header. Is it possible to configure registration in accordance with 3GPP TS 24.229 section 5.1.1.2 Initial registration. ?

**Comment by sipsorcery** [comment]
That's how SIP registrations are designed to work. The registrations don't stop they are instead waiting for the registration period to expire and then will repeat the whole process again. There expiry period can be set by the server in two different ways. It's either the `Expires` header on the response or if present and expiry attribute on the registered contact.

As far as the 3GPP specification goes it does sound like it's just a standard registration and is therefore supported.

 - Send initial `REGISTER` request without credentials,
 - If 401 response resend `REGISTER` request with credentials,
 - If Ok response wait the expiry period and then repeat the process,
 - If error response then it depends...

**Comment by getsok** [comment]
In the second screenshot, the registration process did not end with a 200 OK message. The client did not register on the sip server. If you wait a while, SoftPhone will try to register again (MAX_REGISTER_ATTEMPTS), but it will also not receive 200 OK messages.
But if you send a Register message after receiving the second 401 Unauthorized, then the client will receive 200 OK
![image](https://user-images.githubusercontent.com/36110367/70230012-77abb200-1768-11ea-967f-8f501e05de1a.png)

**Comment by getsok** [comment]
![image](https://user-images.githubusercontent.com/36110367/70230538-99596900-1769-11ea-90d0-100e11531b06.png)

**Comment by sipsorcery** [comment]
It could be the nonce in the 401 challenge response. If a nonce goes stale then the server will reject the authentication attempt and set a new nonce in the following response.

Other than that the standard procedure to track down issues like this is to find a device or piece of software that is working correctly and compare its packet capture to the failing one. That's the good thing about SIP being human readable.

**Comment by getsok** [comment]
To send the REGISTER for the third time, I call the ServerResponseReceived method...need to think

**Comment by sipsorcery** [comment]
Are you following the [UserAgentRegister example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/UserAgentRegister)? It should be taking care of `401` server responses for you.

**Comment by getsok** [comment]
I run SoftPhone on sipsorcery-3.5.0 sources.  I'll fix it for myself) thanks!
