### ISSUE TITLE
NullReferenceException in SIPClientUserAgent.Call

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#13]
ServerTransaction.CancelCall("Unresolvable destination " + callURI.Host);

ServerTransaction is null because DNS resolution fails.

Still looking for why DNS resolution is failing since it works for me in the softphone project

**Comment by rwil02** [comment]
Figured out the DNS failure - "Stop" was called because I was "using" the container class and the call was in another thread.

**Comment by sipsorcery** [comment]
Fixed.
