### ISSUE TITLE
Decoupling SIPUserAgent from RTPSession

### ISSUE THREAD

**Issue by Yitzchok** [sipsorcery/sipsorcery#132]
The addition of SIPUserAgent and the way it takes care or the whole call session is great!

One issue I am having with it is that it is tightly coupled with RTPSession and if I want to use another implementation to manage the RTP and process media I can't use SIPUserAgent.

What would be great is the ability to pass in an IMediaManager or the like so that we can use a custom media provider with SipSorcery.

**Comment by sipsorcery** [comment]
Can you elaborate a bit more? I normally decouple as much as possible but for the `SIPUserAgent` the goal is ease of use. Needing to wire up the `RTPSession` would be a burden.

And when you say "process media" do you mean processing the RTP packets? The `RTPSession` doesn't get anywhere near audio/video devices and it's still left up to the application to deal with those.

Is it this sort of code snippet from `SIPUserAgent` that's the problem.

````csharp
public void Call(SIPCallDescriptor sipCallDescriptor)
{
    RtpSession = new RTPSession((int)m_defaultAudioFormat, null, null, true);
    ...
}
````

I guess an overload could be added along the lines of below but are you really going to implement a custom `RTPSession`? What do you need to customise?

````csharp
public void Call(SIPCallDescriptor sipCallDescriptor, IRTPSession customSession)
{
    ...
}
````

**Comment by Yitzchok** [comment]
I am working on PR that will show the concept.

When I say process media I mean doing everything related to media including the RTP packets.


> RtpSession = new RTPSession
Is the problem but also the usage of RTPSession at all in this class is problematic if we want it to be used with other RTP implementations.

**Comment by sipsorcery** [comment]
The design now works like this:

 - 1RTPChannel1 deals with the sending and receiving packets over UDP sockets and also sending RTCP reports. The RTCP reports bit is not yet done. It's not much more that a UDP socket class.

- The 1RTPSession1 class is what you want to use for handling data received on the 1RTPChannel1. The 1RTPSession.RtpPacketReceived1 method is where raw data from the remote call party arrives. If you need to add extra processing that's where it needs to be done. There will need to be different methods added to `RTPSession` for different audio and video frame types and also for DTMF detection from the audio samples. I've already added a method to extract RFC2833 RTP events with DTMF.

Simplification was the goal here. The previous `RTPChannel` class was a monolith that handled everything: socket communications, RTCP reports, audio and video framing etc. The same functionality still largely exists it's now split between `RTPChannel` and `RTPSession`.

**Comment by Yitzchok** [comment]
I created a WIP Pull Request.

**Comment by sipsorcery** [comment]
Done in #133.
