### ISSUE TITLE
SoftPhone does not correctly hangup incoming calls

### ISSUE THREAD

**Issue by FrankPfattheicher** [sipsorcery/sipsorcery#143]
Hi,
testing the softphone i recognized that i can answer an incoming call,
but pressing Bye the call is terminated locally, but not on the remote site !?

using sipgate as provider

Anything missing?

**Comment by apdevelop** [comment]
I've tried to fix it, but it seems there is much more work: [Issue](https://github.com/sipsorcery/sipsorcery/issues/77)    [PR](https://github.com/sipsorcery/sipsorcery/pull/79/commits/390e84145ae3e7ecbe876b8ead8d1a283a423e3d)

**Comment by sipsorcery** [comment]
Any chance you could do a wireshark capture of the call?

@apdevelop the softphone has had some major surgery recently and the hangup call is made on the SIP `Dialogue` now rather than having to do the `uac` or `uas` test.

Here's the trace I get with a call direct from the softphone sample to the sipgate UK server. In my case the `Bye` button triggers the correct hangup sequence.

![sipgate_bye](https://user-images.githubusercontent.com/197660/71297015-9ff6fb80-2379-11ea-9606-b50561c8e9fa.png)

**Comment by FrankPfattheicher** [comment]
- Calling from remote
- Accept
- Hang up locally : **510**  :-(

![HangUp](https://user-images.githubusercontent.com/921532/71352444-a30b0b00-2576-11ea-9e60-4193f94b2b1a.png)

**Comment by sipsorcery** [comment]
That's a nasty looking `Route` header on the `BYE` request. I'll see if I get the same thing with an incoming call with sipgateuk.

Does the same thing work correctly on a different softphone like [microsip](https://www.microsip.org/)?

**Comment by FrankPfattheicher** [comment]
I will test....
Unfortunately it is x-mas now 😬

**Comment by sipsorcery** [comment]
I can't find a way to get an incoming call with sipgate. They've tightened up their policies since I last tested (which was probably 5 years ago). I'd like to have a look at the full SIP trace if you can email it to me at aaron@sipsorcery.com.

**Comment by FrankPfattheicher** [comment]
Tested with PhonerLite, works as expected.
https://lite.phoner.de/download_de.htm

**Comment by sipsorcery** [comment]
Thx for the traces. The PhonerLite and sipsorcery `Route` headers are different. Looks likes a bug in the sipsorcery code setting that header. I'm looking into it.

**Comment by sipsorcery** [comment]
I believe I found the problem causing this. Should be fixed on `master` now.

**Comment by rjaszek** [comment]
Hello,

It seems not working currently. I made a small console app going through information from website and incoming call is working, making call is working but hangup not. Is there any known reasong for that?
