### ISSUE TITLE
How to control microphone ON/OFF in attended transfer?

### ISSUE THREAD

**Issue by daichan4649** [sipsorcery/sipsorcery#145]
Please give me advice.

For example, in the following scenario:

1. UA1 and UA2 are talking
2. UA1 puts UA2 on hold
3. UA1 calls to UA3
4. UA1 and UA3 are talking
5. UA1 transfers UA2 to UA3

In case 4, I want to do this.

- UA1 <-> UA2 is microphone OFF
- UA1 <-> UA3 is microphone ON

But, in the current softphone sample, UA1's voice reaches both UA2 and UA3 when UA1 and UA3 are talking. I'm trying to customize Softphone and MediaManager, but I can't control it. 

In particular...

> UA1 <-> UA2 is microphone OFF

This was achieved by calling MediaManager#StopAudio().

> UA1 <-> UA3 is microphone ON

I tried tdo fix Softphone like this. Creating a new instance of MediaManager as shown below failed. Voice reaches both UA2 and UA3...

```
private MediaManager _mediaManagerForTransfer;

private void OnWindowLoaded(object sender, System.Windows.RoutedEventArgs e)
{
    Task.Run(() =>
    {
        _mediaManager = new MediaManager(this);
        _mediaManager.OnLocalVideoSampleReady += LocalVideoSampleReady;
        ・・・

        // add (same as above)
        _mediaManagerForTransfer = new MediaManager(this);
        _mediaManagerForTransfer.OnLocalVideoSampleReady += LocalVideoSampleReady;
        ・・・
    });
}

private void SIPCallAnswered(SIPClient client)
{
    // _mediaManager.StartAudio();
    // client.RtpSession.OnReceivedSampleReady += RemoteAudioSampleReceived;

    var transferCall = (client != _sipClients[0]);
    var mediaManager = _mediaManager;
    if (transferCall)
    {
        mediaManager = _mediaManagerForTransfer;
    }
    mediaManager.StartAudio();
    client.RtpSession.OnReceivedSampleReady += RemoteAudioSampleReceived;
}
```
I'm sorry for my poor English.

**Comment by sipsorcery** [comment]
There's a substantial change being worked on in #133 that affects the `RTPSession` management. For that reason it's better to wait before fixing this issue on `master`.

In the interim a manual fix can be done by changing the `LocalAudioSample` method in `Softphone.xaml.cs` to something like this:

````csharp
private void LocalAudioSampleReady(byte[] sample)
{
	SIPClient activeClient = null;

	if(_sipClients[1].IsCallActive)
	{
		activeClient = _sipClients[1];
	}
	else if(_sipClients[0].IsCallActive)
	{
		activeClient = _sipClients[0];
	}

	if(activeClient != null)
	{
		activeClient.RtpSession?.SendAudioFrame(activeClient.AudioTimestamp, sample);
		activeClient.AudioTimestamp += (uint)sample.Length; // This only works for cases where 1 sample is 1 byte.
	}
}
````

**Comment by daichan4649** [comment]
I see. I use this implementation until it is merged. Thank you for the advice!

**Comment by sipsorcery** [comment]
I've added a music on hold feature to the softphone. Now when you put a call on hold the remote party will hear music rather than still getting the microphone input.

**Comment by daichan4649** [comment]
Thanks for providing samples!

The following logic of RTPMediaSessionManager#UseMusicOnHold corresponds to microphone ON/OFF. I understand. Thank you.

```
// microphone OFF
_mediaManager.OnLocalAudioSampleReady -= LocalAudioSampleReadyForSession;

// microphone ON
_mediaManager.OnLocalAudioSampleReady += LocalAudioSampleReadyForSession;
```

**Comment by blendR8** [comment]
> I've added a music on hold feature to the softphone. Now when you put a call on hold the remote party will hear music rather than still getting the microphone input.

how can it be archived to use the sip-server default hold music instead of the sample music?
