### ISSUE TITLE
Regarding SIPTransport thread with Task usage

### ISSUE THREAD

**Issue by Yitzchok** [sipsorcery/sipsorcery#149]
From this code, it seems like the idea here is to have one thread running that will process all the SIP transport message

https://github.com/sipsorcery/sipsorcery/blob/e28136f6d90b9eb924835f8d11133da339e54922/src/core/SIP/SIPTransport.cs#L198-L205

awaiting the SIPMessageReceived task here means that once the task leaves the thread for real async work (e.g. SIPTCPChannel.ConnectClientAsync) it will be running on another thread on the thread pool.

https://github.com/sipsorcery/sipsorcery/blob/e28136f6d90b9eb924835f8d11133da339e54922/src/core/SIP/SIPTransport.cs#L685-L696

If this is what is expected then it's fine but it looks more like a bug.

**Comment by sipsorcery** [comment]
The purpose of the dedicated thread for the `SIPTransport.ProcesssReceiveQueue` thread is to queue receives from all the SIP channels and avoid the socket receive methods getting held up by processing a received message.

Typically the main blocker has been DNS lookups. For example a SIP message is received and requires a DNS lookup to be processed. In extreme circumstances that could take 10s or longer to process and during that time all incoming messages on the SIP channel will need to be buffered by the socket. For a client it probably won't matter but for a SIP Server application the socket buffer could be filled very quickly.

The `SIPTCPChannel.ConnectClientAsync` is not done on a dedicated thread. It will occur on whatever thread called the `SendAsync` method. The dedicated threads for the TCP and TLS channels are to accept and prune old connections.

````csharp
private void Initialise(IPEndPoint listenEndPoint)
{
	try
	{
		m_tcpServerListener = new TcpListener(listenEndPoint);

	        ...

		Task.Run(AcceptConnections);
		Task.Run(PruneConnections);

		logger.LogInformation($"SIP {ProtDescr} Channel created for {ListeningEndPoint}.");
	}
	catch (Exception excp)
	{
		logger.LogError("Exception SIPTCPChannel Initialise. " + excp.Message);
		throw excp;
	}
}        
````

> awaiting the SIPMessageReceived task here means that once the task leaves the thread for real async work (e.g. SIPTCPChannel.ConnectClientAsync) it will be running on another thread on the thread pool. If this is what is expected then it's fine but it looks more like a bug.

I don't understand this point. The `SIPMessageReceived` method has a try/catch block. It catches all exceptions and returns a SocketError result. How does the `await SIPMessageReceived` call introduce a problem?

**Comment by Yitzchok** [comment]
> The purpose of the **dedicated** thread for the SIPTransport.ProcesssReceiveQueue

That is the point. There is **no _dedicated_ thread!** That code will be running on the thread pool and will be queued on the thread pool on any real async call.

The problem will arise if the thread pool is congested for any reason (e.g. not enough threads, too many running tasks...)

**Comment by sipsorcery** [comment]
I don't understand? `Task.Run(ProcessReceiveQueue)` is starting a dedicated thread.

````
private async Task ProcessReceiveQueue()
{
     Thread.CurrentThread.Name = "siptrans-recv";
     ....
}
````

![siptransport_thread](https://user-images.githubusercontent.com/197660/71425184-d2fb0100-2691-11ea-84ab-af220263aa35.png)

**Comment by Yitzchok** [comment]
What about doing this 

```
private async Task ProcessReceiveQueue()
{
     Thread.CurrentThread.Name = "siptrans-recv";
     await Task.Delay(1000);
     string threadName = Thread.CurrentThread.Name;
}
```

What is threadName?

**Comment by sipsorcery** [comment]
Thread name is just an diagnostic field for logging/debugging. If you look at the highlighted thread in my screenshot you'll notice the thread name is `siptrans-recv`. The purpose being to illustrate there is a dedicated thread running the `ProcessReceiveQueue` method.

**Comment by Yitzchok** [comment]
Try this https://repl.it/repls/DopeyPristineFrontpage

```
using System;
using System.Threading.Tasks;
using System.Threading;

class MainClass {
  public static void Main (string[] args) {
    Task.Run(ProcessReceiveQueue).Wait();
  }

  private static async Task ProcessReceiveQueue()
  {
      Thread.CurrentThread.Name = "siptrans-recv";

      Console.WriteLine($"Start running on {Thread.CurrentThread.Name}");

      await Task.Delay(1);

      Console.WriteLine($"End running on {Thread.CurrentThread.Name}");
  }
}
```

**Comment by sipsorcery** [comment]
But the `ProcessReceiveQueue` has a while loop.

It's more like this:

````
using System;
using System.Threading.Tasks;
using System.Threading;

class MainClass {
  public static void Main (string[] args) {
    ManualResetEvent mre = new ManualResetEvent(false);
    Task.Run(ProcessReceiveQueue);
    mre.WaitOne();
  }

  private static async Task ProcessReceiveQueue()
  {
      Thread.CurrentThread.Name = "siptrans-recv";

      Console.WriteLine($"Start running on {Thread.CurrentThread.Name}");

      while(true)
      {
        Console.WriteLine("DoWork");
        await Task.Delay(2000);
      }

      Console.WriteLine($"End running on {Thread.CurrentThread.Name}");
  }
}
````

**Comment by Yitzchok** [comment]
As long as it's understood that this loop runs on the thread pool and every loop might be on another thread. And if there is no threads available you might be waiting for a while.

Then it's fine. But I am not sure that is the case.

Try it now https://repl.it/repls/DopeyPristineFrontpage

```
using System;
using System.Threading.Tasks;
using System.Threading;

class MainClass {
  public static void Main (string[] args) {
    ManualResetEvent mre = new ManualResetEvent(false);
    Task.Run(ProcessReceiveQueue);
    mre.WaitOne();
  }

  private static async Task ProcessReceiveQueue()
  {
      Thread.CurrentThread.Name = "siptrans-recv";

      Console.WriteLine();

      while(true)
      {
        Console.WriteLine($"DoWork - ThreadPool:{Thread.CurrentThread.IsThreadPoolThread}, Name:{Thread.CurrentThread.Name}, Id:{Thread.CurrentThread.ManagedThreadId}");
        await Task.Delay(2000);
      }
  }
}
```

**Comment by sipsorcery** [comment]
Ah got it now. It's the difference between using `await Task.Delay(2000);` and `Thread.Sleep(2000)`.

In the former case the thread you get back for the next loop iteration could be different. I wasn't aware of that. 

I don't think it matters in this case. The important thing is the `m_inMessageQueue` is getting serviced in a timely fashion. UNless you can see any gotchas with it?

Note that previously the dedicated thread was created with `ThreadPool.QueueUserWorkItem` and `Task.Run` is now the recommended replacement for it.

**Comment by Yitzchok** [comment]
Saying a timely fashion is to vague. And different usages might have a different timing requirements (proxy vs server vs client).

Does it deserve it's own thread? Or is running on the thread pool good enough?
Do we have to answer this or can we give a good default with a way the application using it to decide how to pump messages.


Regarding starting the task there is an option to start a task using TaskCreationOptions.LongRunning but in our case it's kind of useless because once you use await it can return on another thread. (Looks like he explains this http://blog.i3arnon.com/2015/07/02/task-run-long-running/)

For a dedicated thread it's probably best to create a regular new thread and not use any await (though .Wait() would be valid here because we don't have a synchronization context).

**Comment by sipsorcery** [comment]
Proposed guidelines to address in #164.
