### ISSUE TITLE
SIPRegistrationUserAgent: unused Members and Arguments

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#155]
Hey Aaron,
I'm currently looking at and extending SIPRegistrationUserAgent and I found some unused Members and (ctor)Arguments:

- m_owner: only used for logging
- m_realm: not used
- m_localEndpoint: not used (anymore)
- adminMemberId (ctor): not used
- realm (ctor): not used (see m_realm)
- owner (ctor): only used for logging (see m_owner)

is there any reason to keep them?

ciao Ralf

**Comment by sipsorcery** [comment]
The `realm` value is used but the other variables are hangovers from the past and can go.

**Comment by rj2Skipper** [comment]
m_realm isn't really used. 
There is an assignment in GetReistrationRequest, but the assigned value isn't used either

**Comment by sipsorcery** [comment]
Right missed that. 

The `realm` value should be being used in `GetAuthenticatedRegistrationRequest` for edge cases where the `realm` returned by the server needs to be overriden or in cases where the initial register request needs to be authenticated with a custom realm.

**Comment by rj2Skipper** [comment]
now I've added usage of m_realm to GetAuthenticatedRegistrationRequest
