### ISSUE TITLE
secure things in .appveyor.yml

### ISSUE THREAD

**Issue by bleissem** [sipsorcery/sipsorcery#159]
Hi there, 
in the file 
.appveyor.yml
should those auth_token, 
api_key:
      secure:
etc. keys
stored somewhere else  ? 
You might should change those keys by the way ( github, nuget etc.).

Regards 
Alex B.

**Comment by sipsorcery** [comment]
Those settings are [secure](https://www.appveyor.com/docs/build-configuration/#secure-variables). Only jobs running under my appveyor account can decrypt them.

Is that what you mean?

**Comment by bleissem** [comment]
Hi, 
ok I see that there exists this security concept behind the scenes. 
I was unaware of this concept. So I assume everything is fine. 
Regards Alex B.
