### ISSUE TITLE
NullReference Exception in SIPClientUserAgent.cs

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#16]
m_Logger.Debug("RTCC reservation was reallocated from CDR " + originalCallTransaction.CDR.CDRId + " to " + ServerTransaction.CDR.CDRId + " for owner " + Owner + ".");

SIPClientUserAgent.cs

originalCallTransaction.CDR may sometimes be null

**Comment by sipsorcery** [comment]
Fixed.
