### ISSUE TITLE
Save call to file

### ISSUE THREAD

**Issue by Almeonamy** [sipsorcery/sipsorcery#160]
Hello. Can anybody describe how can I record call and save it to file (e.g. mp3)?

**Comment by sipsorcery** [comment]
What sort of application? Desktop, console?

If you're using the [demo softphone](https://github.com/sipsorcery/sipsorcery/tree/master/examples/Softphone) in this project as a basis then the approach would be to hook up the [NAudio WaveFileWriter](https://markheath.net/post/how-to-use-wavefilewriter) and write each [decoded sample](https://github.com/sipsorcery/sipsorcery/blob/b29111807dde09207d110042b987fabd79ab7752/examples/Softphone/Media/AudioChannel.cs#L97) to it.

**Comment by Almeonamy** [comment]
Asp.net application. Thanks.

**Comment by sipsorcery** [comment]
This project can't help with audio recording in ASP.Net,

**Comment by Almeonamy** [comment]
Your example with NAudio will help me I think.
