### ISSUE TITLE
SIPRegistrationUserAgent: call Start() after a Stop() throws an exception

### ISSUE THREAD

**Issue by dxmann** [sipsorcery/sipsorcery#163]
Hello,
I want to notify that if I call
```
SIPRegistrationUserAgent regManager ...
...
regManager.Start() // works
regManager.Stop() // works
regManager.Start() // Causes exception: "SIPRegistrationUserAgent is already running, try Stop() at first!"
```

With the debugger I can check that when the Start method is called for the second time, the timer m_registrationTimer is != null, so the above exception is thrown.

I'm using the 40.0.13-pre version.

Thank you for your work!!
Regards

**Comment by sipsorcery** [comment]
Fixed on `master`. Will be included in next nuget package (which will also be a pre-release).

**Comment by dxmann** [comment]
Thanks a lot! :)
