### ISSUE TITLE
Threading and async/await (TAP)

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/sipsorcery#164]
It's taken a while (mainly for me to try and get a better grasp of Task Asynchronous Programming) to come up with a first attempt at dealing with #137 and #149. The result is the draft guidelines below and which have already been implemented in the code.

#### Long running background threads:

 - Use `Task.Factory.StartNew(SomeMethod, TaskCreationOptions.LongRunning)` to create a long running thread.
 - For calls on a long running thread don't use async/await. Instead use `.Wait` or `.Result`. This keeps all operations on the same thread.
 - ~~If async/await can't be avoided do NOT use `.ConfigureAwait(false)`. Doing so will result in threads resuming on an arbitrary threadpool thread. The long running threads are all designed to do their work sequentially and don't require work to be carried out on other threads.~~
 - The current long running threads are:
   - SIPClientWebSocket.MonitorReceiveTasks: Monitors any client web socket connections for a receive.
   - SIPTCPChannel.AcceptConnections: Listens for new client connections on a TCP/TLS SIP channel.
   - SIPTCPChannel.AcceptConnections: Monitors a TCP channels client list and removes clients that have timed out.
   - SIPUDPChannel.ExpireFailedSends: The UDP channel tracks send failure attempts. This thread will remove failures after a set period of time.
   - SIPTransport.ProcesssReceiveQueue: All incoming SIP messages from individual channels get queued by the SIPTransport. This thread is responsible for servicing that queue.
   - SIPTransactionEngine.ProcessPedningTransactions: Services transactions that need to send reliable requests and responses.
 
#### Internal method calls not on long running threads:

 - Avoid using `await`. Instead return the `Task` back up the call stack and let the application use `await`.
 - For cases where a method needs to make multiple async calls, and therefore can't return a task for multiple awaits, use await with `.ConfigureAwait(false)`. This will help avoid deadlocks in applications that use a synchronisation context (Windows Forms, WPF etc.). Without `.ConfigureAwait(false)` an async library call will be continue on the UI (or main thread). 
 - The method calls the application makes should NOT specify `.ConfigureAwait(false)`. It is required that the callback from the application method call does end back on the correct synchronisation context.

#### TaskCompletionSource:

 - There are a small number of cases where the following usage pattern is convenient:
   - Initiate an action (e.g. send a SIP REFER request to a remote party),
   - Wait for an external action within the same method (e.g. the REFER response or a timeout). The external action is received via a lambda event handler defined in the same method,
   - Once the required event has occurred inform the original caller the result of the overall operation.
 - The approach used in these cases (at the time of writing there are 3 such cases) is to use a `TaskCompletionSource`. For the same reason as specifying `.ConfigureAwait(false)` on await calls the `TaskCompletionSource` should be instantiated with `new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously)` to reduce the chance of deadlocks.
 - An alternative to `TaskCompletionSource` is a `ManualResetEvent` but currently there has not been a need to switch.

## Deadlock Example Program

````csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Deadlock
{
    class Program
    {
        private static Form _form;

        public static async Task Main(string[] args)
        {
            Console.WriteLine("Starting...");

            SynchronizationContext syncCtx = SynchronizationContext.Current;
            Console.WriteLine($"sync ctx ? {syncCtx != null}");

            await DoWork("a");
            await DoWork("b");
            await DoWork("c");

            // By creating a Windows Forms object a synchronisation context is
            // automatically created.
            _form = new Form();

            syncCtx = SynchronizationContext.Current;
            Console.WriteLine($"sync ctx ? {syncCtx != null}");

            Console.WriteLine("Background work starting...");
                       
            // Without this line there will be a deadlock as the new "await" call will
            // try and continue on a thread belonging to the Windows Forms context. There
            // is only a single thread on that context which is running the Windows message
            // pump and it's assumed it doesn't accept new jobs.
            // By calling an await operation with ConfigureAwait(false) dotnet knows it 
            // can grab a thread pool thread to continue on. At that point the synchronisation
            // context will no longer be on the current thread and no deadlock occurs.
            // Un/comment out this line to remove/get a deadlock.
            //await Task.Delay(1).ConfigureAwait(false);

            syncCtx = SynchronizationContext.Current;
            Console.WriteLine($"sync ctx ? {syncCtx != null}");

            await DoWork("x");
            await DoWork("y");
            await DoWork("z");

            ManualResetEvent mre = new ManualResetEvent(false);
            mre.WaitOne();
        }

        private static async Task DoWork(string name)
        {
            Console.WriteLine($"DoWork {name} - ThreadPool:{Thread.CurrentThread.IsThreadPoolThread}, Id:{Thread.CurrentThread.ManagedThreadId}");
            await Task.Delay(200);
        }
    }
}
````

## References

I don't want to provide a list of references as the amount of material on TAP is ridiculous. Unfortunately while async/await is great on the surface it quickly gets nasty for library code. Instead I'm recording a short list key references and the key points taken from them:

[https://devblogs.microsoft.com/dotnet/configureawait-faq/](https://devblogs.microsoft.com/dotnet/configureawait-faq/):

- > if you’re writing app-level code, do not use ConfigureAwait(false).
- > if you’re writing general-purpose library code, use ConfigureAwait(false)

[https://michaelscodingspot.com/c-deadlocks-in-depth-part-2/](https://michaelscodingspot.com/c-deadlocks-in-depth-part-2/):

 - > In library code, use  .ConfigureAwait(false)  if possible. You don’t know which Thread called you and what deadlocks you might cause.
 - > Having your entire call stack as async methods makes more readable code and it’s easier to avoid deadlocks.
  - >Be careful about using  .Result  or  .GetAwaiter().GetResult() . They can easily cause deadlocks, especially when called from the UI Thread.

**Comment by Yitzchok** [comment]
> Long running background threads:

> If async/await can't be avoided do NOT use .ConfigureAwait(false). Doing so will result in threads resuming on an arbitrary threadpool thread. The long running threads are all designed to do their work sequentially and don't require work to be carried out on other threads.

In this case calling ConfigureAwait(false) will be the same as not calling it and will most likely continue on another thread either way because this new long running thread doesn’t have a Sync context.

**Comment by sipsorcery** [comment]
Thanks for the feedback. You're right and I've removed that redundant guideline.

Thanks again for your help with this. I was a bit behind in keeping up to date with async/await/TAP.

**Comment by sipsorcery** [comment]
No synchronisation issues noticed since the guidelines have been implemented. Will continue to monitor but for now closing this issue.

**Comment by sipsorcery** [comment]
Still cropping up: https://stackoverflow.com/questions/63044015/how-to-make-a-deadlock-safe-async-library-method/63052650.

**Comment by Terricide** [comment]
Do you have specific tests you run to see the issue. I think Ive got a good handle on async await and I can do a pass through the code early next week in a branch.

**Comment by sipsorcery** [comment]
> Do you have specific tests you run to see the issue. I think Ive got a good handle on async await and I can do a pass through the code early next week in a branch.

There are no current known deadlock related issues. It's probably just my paranoia at this stage. I don't think it's worth spending too much time on.
