### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by DrunkenCub** [sipsorcery/sipsorcery#165]
Can we use this in Xamarin for iOS and Android development?

**Comment by sipsorcery** [comment]
I haven't tested it but in theory Xamarin can consume .net standard compatible libraries so the answer should be yes.

**Comment by DrunkenCub** [comment]
Awesome! Yes, if there are no windows specific ones then there should not be a problem. I will do a demo app and see. Thanks for the prompt response.

**Comment by sipsorcery** [comment]
The Windows specific logic has been confined to the [SIPSorceryMedia](https://github.com/sipsorcery/sipsorcery-media) library (unless I've missed something).

The caveat is that while this library gives you the signalling and media transmission to do anything with the media you'll need platform specific logic. The [SIPSorceryMedia](https://github.com/sipsorcery/sipsorcery-media) library provides a rudimentary implementation for Windows. It's not a trivial task to replicate for other platforms...

**Comment by DrunkenCub** [comment]
Yes, but Xamarin does provide wrappers for the audio handling, as atm i only need audio.

**Comment by sipsorcery** [comment]
Great. Be very interested to hear how you go if you're able to report back.

**Comment by DrunkenCub** [comment]
Yes, will update the progress here!

**Comment by hossam14102010** [comment]
@DrunkenCub have you made any progress?

**Comment by DrunkenCub** [comment]
@hossam14102010 Unfortunately no. We moved to native.
