### ISSUE TITLE
'RTPMediaSession' does not contain a definition for 'OnReceivedSampleReady'

### ISSUE THREAD

**Issue by DrunkenCub** [sipsorcery/sipsorcery#166]
I get following issue when trying with sample code given in the README.md

'RTPMediaSession' does not contain a definition for 'OnReceivedSampleReady' and no accessible extension method 'OnReceivedSampleReady' accepting a first argument of type 'RTPMediaSession' could be found (are you missing a using directive or an assembly reference?)	

DLL version = 4.0.13-pre

**Comment by sipsorcery** [comment]
`RTPMediaSession` is about to be removed (the whole RTP session interfaces are in a state of flux at the moment due to incorporating WebRTC). In your case if you are targeting a non-Windows platform then you should use `RTPSession`.

A new pre-release nuget package will be up today

**Comment by sipsorcery** [comment]
Nuget package version `4.0.28-pre` has been published. It removes the `RTPMediaSession` class. The [RTP Session](https://sipsorcery.github.io/sipsorcery/articles/rtpsession.html) article has been updated to describe the the `RtpAVSession` class.
