### ISSUE TITLE
Exception processing pending transactions. The type initializer for 'SIPSorcery.SIP.SIPChannel' threw an exception.

### ISSUE THREAD

**Issue by NikitaG** [sipsorcery/sipsorcery#168]
Looks like exception happens in static constructor in SIPChannel class, when it calls NetServices.GetLocalAddressForInternet();, because UdpClient unable to connect to Port: 0. 

**Repro:** 
- call static method: NetServices.GetLocalAddressForInternet(); 
- exception: Can't assign requested address 1.1.1.1:0.

**Environment:**
.NET Core SDK:
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64

https://github.com/sipsorcery/sipsorcery/blob/7fe2b506d1d5be050c46c4a043cdde70f3940a5c/src/sys/Net/NetServices.cs#L230

**Comment by sipsorcery** [comment]
Replicated with unit tests running on macos [here](https://github.com/sipsorcery/sipsorcery/runs/484353002?check_suite_focus=true).

Seems the `UdpClient.Connect` trick to do a lookup in the Kernel's IP routing table doesn't work on MacOS. Will investigate.

**Comment by sipsorcery** [comment]
Fixed. 

MacOS didn't like the use of port **0** when looking up local IP addresses with `UdpClient.Connect("1.1.1.1:0")` etc. Changed to `UdpClient.Connect("1.1.1.1:5060")` and MacOS is happy. Note that `UdpClient.Connect` is a NoOp as far as the network is concerned (UDP does not support connections). The call is being used to get a local IP address from the kernel's IP routing table. No packets or external network events are triggered from this call.
