### ISSUE TITLE
CodeBase exception in AppState.cs

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#17]
string localPath = new Uri(System.Reflection.Assembly.GetExecutingAssembly().CodeBase).LocalPath;
                CurrentDirectory = Regex.Replace(Path.GetDirectoryName(localPath), @"^file:\\", ""); // There's undoubtedly a better way!
However, also seems to be the "mscorlib" path so you might want GetEntryAssembly instead

**Comment by sipsorcery** [comment]
Switched to CurrentDirectory = Environment.CurrentDirectory;
