### ISSUE TITLE
SIPSorcery.Media

### ISSUE THREAD

**Issue by DrunkenCub** [sipsorcery/sipsorcery#170]
Is RtpAVSession class is Windows dependent?

**Comment by sipsorcery** [comment]
Yes.

The `NAudio` and `SIPSorceryMedia` dll's which are used by `RtpAVSession` are both Windows only.

**Comment by DrunkenCub** [comment]
in case I want to use the SIP only, is there another session class which I can use? ie. For Xamarin

**Comment by sipsorcery** [comment]
The `SIPUserAgent` class takes an implementation of `IMediaSession`. This allows alternative implementations other than `RtpAVSession` to be used.

If you want SIP only you could create a lightweight implementation of `IMediaSession` and supply that to `SIPUserAgent`. The main `SIPSorcery` library does not depend on any Windows specific libraries so you are free to plugin a higher level RTP session as you see fit.

**Comment by DrunkenCub** [comment]
Thank you Aaron for your prompt response.
