### ISSUE TITLE
Support for custom headers in RegistrationUserAgent

### ISSUE THREAD

**Issue by RoryRoberts** [sipsorcery/sipsorcery#171]
Hello,

I have a requirement to send a registration message with some custom headers. Sip sorcery's Client and Server user agents support setting custom headers through passing a string array into certain methods, but RegistrationUserAgent has no such support.

I resolved this in my own fork initially by making `GetRegistrationRequest` and `GetAuthenticatedRegistrationRequest` virtual so that I could override them, call the base methods and append my headers, but looking at how these other classes do it, it seems like passing them as a parameter in a method call to the user agent's `Start()` method might be more in line with the design of sip sorcery.

Are you happy for this to be added, and do you have any preferences/recommendations on how it should be achieved? I'm happy to submit a pull request to add this, but I wanted to post it as a discussion first.

**Comment by sipsorcery** [comment]
I think the best approach would be to add the custom headers parameter to the verbose `SIPRegistrationAgent` constructor (the one that already has 10 parameters).

**Comment by RoryRoberts** [comment]
Sounds good to me! I'll get a pull request for this submitted soon.
