### ISSUE TITLE
Constructor for UACInviteTransaction is internal

### ISSUE THREAD

**Issue by RoryRoberts** [sipsorcery/sipsorcery#174]
I want to send an INVITE request to a service which will reply with TRYING, followed by OK with an SDP body that I want to consume later.

Using the `SIPClientUserAgent.Call(...)` method doesn't really work for me from what I understand of it, I think I need a bit more control over the request headers than it offers and I don't need to account for some of the things it does for my specific case, and I think that's okay. The next best thing would be for me to create the invite request myself and then use the UACInviteTransaction class to handle it, but the constructor is internal. I'm not sure why so I hesitate to suggest just making it public, what do you think? I notice that the constructor for UASInviteTransaction used to be internal a while ago but was made public - so I'm wondering if this is a reasonable change to make for the UAC transaction class too?

Happy to submit a PR for whatever change seems appropriate (if any)

**Comment by sipsorcery** [comment]
The reason it's `internal` is to protect developers using the library from shooting themselves in the foot. It can be tricky to deal with INVITE transactions and in 99% of cases there is no need, the higher level classes such as `SIPClientUserAgent` or `SIPUserAgent` are much better options.

If you only need to add some custom headers to the INVITE request then you can do that by setting them on the `SIPCallDescriptor` that's passed to `SIPClientUserAgent.Call` or `SIPUserAgent.Call`. If you really do need to fiddle with the core SIP headers ('Via`, `To`, `From`, `CSeq` etc,) then perhaps that would justify using the `UACInviteTransaction` directly.

The `UASIniviteTransaction` is slightly different as it's used as the first step of answering a call and needs to be passed around a bit. 
 
All that being said I'm not that strongly attached to having it internal or public. If you do still need it public feel free to submit a PR.

**Comment by RoryRoberts** [comment]
That makes sense, and I think the ethos of "Protecting you from yourself" is sensible to follow, especially in the deeper parts of this library. I hadn't quite realised the power that `SIPCallDescriptor` had offered me, sorry! On review, it looks like the only thing I'm sorely missing is the ability to add parameters to the `Contact` header. Not sure it's worth making the transaction class open to public use just for that.

I'm happy to close this for now and have a think about this.
