### ISSUE TITLE
Receiving fragmented data with SIPClientWebSocketChannel

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#175]
Hey Aaron,
i've used your SIPClientWebSocketChannel as template in another project.
There surfaced an issue when receiving fragmented data over ws: every fragment fired the MessageReceived event and I had to guess if received data was complete or not.
Looking at the implementation in SIPSorcery i think there will be the same problem: if a buffer is received fragmented it can not be parsed as sipmessage.

when i used WebSocketSharp (as you implemented it for SIPWebSocketChannel) for my ws-client implementation, the MessageReceived event was fired with the whole data.

ciao Ralf

**Comment by rj2Skipper** [comment]
I've just verified my thoughts about SIP-Parsing-Error of fragmented data: allthough there is no parsing exception the received SIPMessage-Object is not complete

to reproduce i've added a SIPTransportUnitTest with SIPWebSocketChannel and SIPClientWebSocketChannel and added some silly x-header to the Options-OK-Response in the Server-Task.

ciao Ralf

**Comment by sipsorcery** [comment]
Hi Ralf, could you submit a PR with the unit test? Will make it easier to do the fix.

**Comment by sipsorcery** [comment]
This should be fixed on `master` now. Thanks again for the unit test it was a helpful starting point (I refactored it a bit).

**Comment by rj2Skipper** [comment]
this works in SIPSorcery now 

Ralf
