### ISSUE TITLE
How to fix System.runtime error

### ISSUE THREAD

**Issue by b0gdannn** [sipsorcery/sipsorcery#177]
![image](https://user-images.githubusercontent.com/62012231/77310891-caa17900-6d07-11ea-9214-3a2055f2c1e5.png)

**Comment by sipsorcery** [comment]
Is the main application targeting `netcoreapp3.1` and do you have the dotnet 3.1 SDK installed?

Other than that it seems to be a fairly common problem https://stackoverflow.com/questions/49929952/assembly-uses-version-x-which-has-a-higher-version-than-referenced-assembly-erro.

**Comment by sipsorcery** [comment]
Closing, can be re-opened if more info is available.
