### ISSUE TITLE
SIPSorcery,SoftPhone Example Project Errors

### ISSUE THREAD

**Issue by Charcsi** [sipsorcery/sipsorcery#179]
Hello

Sorry, my English is not good. :(

I would like to try the SoftPhone project in this example.
Download, 
Open .sln 
![SIPSoftPhoneState](https://user-images.githubusercontent.com/35832591/77433834-3525e800-6de0-11ea-8c6e-7f80de9da016.png)

Is there a solution?

Environment:
- VS 2019 Version 16.5.0
- NET Core SDK 2.1.202 - 3.1.200
Thanks for the answer

Charcsi

**Comment by sipsorcery** [comment]
Those are only warnings. The softphone application should still run properly if you have dotnet 3.1 installed.

**Comment by Charcsi** [comment]
I Try 
But not run :(
This Error
![error](https://user-images.githubusercontent.com/35832591/77437344-d747cf00-6de4-11ea-95b3-d47051548faf.png)

**Comment by sipsorcery** [comment]
The OpenGL Audio Scope I added to the softphone is causing the exception (and you are the second user to report it). It might be the OpenGL shader compilation fails if the system doesn't have a GPU. The Audio Scope was my first foray into OpenGL so I'm not familiar with all the things that can go wrong.

This is what it's supposed to do https://www.youtube.com/watch?v=FTRsYfujODk.

I'll need to disable the Audio Scope by default until I know why the OpenGL intialisation is failing.

**Comment by Charcsi** [comment]
Thx 
Watch Video! 
Try it.

**Comment by Charcsi** [comment]
I would likeI just want to create a SIP client.
Need OpenGL Audio Scope? 
Only voice and external VOIP provider.
Any solution?
thx
Charcsi

**Comment by sipsorcery** [comment]
> Any solution?

Yes you can just delete all references to the audio scope including the control in the XAML.

**Comment by sipsorcery** [comment]
Upstream https://github.com/dwmkerr/sharpgl/issues/169.

**Comment by sipsorcery** [comment]
The Audio Scope and associated OpenGL have been removed from the softphone example.
