### ISSUE TITLE
sipsorcery-simpleservers/Proxy Question

### ISSUE THREAD

**Issue by JimG777** [sipsorcery/sipsorcery#18]
Hi,

As per Issue #14, the simple proxy is a very helpful example to start using sipsorcery (so it seems). My goal is for a test endpoint, which acts as a simple registrar and SIP SIMPLE message router.

My question is that when I send a SIP MESSAGE request (to the proxy), it does not fire the SIPTransportRequestReceived() function. Is there something I need to do in order to handle such a request.

Thanks,

Jim

**Comment by sipsorcery** [comment]
It could be that there's a validation error parsing your SIP request. 

I've added some examples to the simple proxy app of wiring up the delegates to show the raw SIP messages flowing around as well as any messages that failed validation (you'll need to uncomment the ones you are interested in).
