### ISSUE TITLE
SIP server Answer and Record a call

### ISSUE THREAD

**Issue by ducdanganhit** [sipsorcery/sipsorcery#180]
Hello,
How can i answer and record a call to audio file? I registered the SIP server  IP to VoIP device. 
Can you give me a example for answering the call and/or way to record the call to audio file? I need your help. 
Thank you very much.

**Comment by sipsorcery** [comment]
TIt's straight forward to do this if you're on Windows? I'll add an example shortly.

**Comment by ducdanganhit** [comment]
> TIt's straight forward to do this if you're on Windows? I'll add an example shortly.

Yes, im using Window. Pease add the example. Thanks in advanced.

**Comment by sipsorcery** [comment]
Example now available [here](https://github.com/sipsorcery/sipsorcery/blob/master/examples/RecordCall/Program.cs).

**Comment by ducdanganhit** [comment]
Is this for incoming call? I see comments in the example "Place the call". How can i receive a call and record it? 
I mean that not outgoing call, incoming call to record.

**Comment by sipsorcery** [comment]
Record incoming call example available [here](https://github.com/sipsorcery/sipsorcery/blob/master/examples/RecordIncomingCall/Program.cs).

**Comment by ducdanganhit** [comment]
Thanks for your support. I will try it. :)
