### ISSUE TITLE
Consistent high CPU usage on sip-txengine thread

### ISSUE THREAD

**Issue by RobinsonWM** [sipsorcery/sipsorcery#182]
I'm using SIPSorcery in a testing application that receives bulk SIP calls generated by an application under test (the application under test is not using SIPSorcery.)  In my test app, I noticed consistent heavy CPU usage, and the CPU usage didn't correlate directly with the rate of incoming SIP messages.  I profiled the application and noticed a few hot spots in `SIPTransactionEngine.ProcessPendingTransactions()`.  This method appears to run on its own thread and loop through all transactions every 50 ms (or 250 ms when idle.)  Based on the profiling data, I made some slight changes that drastically reduced the CPU usage.  Would you consider accepting these changes or something similar to them?

I pushed the changes to a fork: https://github.com/sipsorcery/sipsorcery/compare/master...RobinsonWM:txengine-performance?expand=1

1. There were few places using `foreach (SIPTransaction transaction in m_pendingTransactions.Values)`.  It turns out `ConcurrentDictionary`'s implementation of `Values` is quite a thing, locking the whole dictionary and copying everything into a new list.  Since we didn't need list semantics here, it appears `foreach (var (_, transaction) in m_pendingTransactions)` is more efficient.
1. One spot was doing `if (m_pendingTransactions.Count == 0)`.  The implementation of `IsEmpty` has a short-circuit for cases where it can return `false` that makes it faster than `Count`.
1. `RemoveExpiredTransactions()` was calling `DateTime.Now` frequently - at least once per pending transaction.  This was the biggest hot spot I saw in the profiling report (I was surprised to learn that `DateTime.Now` spent more than half of its time figuring out whether daylight saving time is in effect.)  I changed it to call `DateTime.Now` before the loop.
1. I doubt this was significant, but I replaced `Task.Delay(...).Wait()` with `Thread.Sleep()`.  `Task.Delay()` sets a timer and has to process a callback on another thread before unblocking the waiting thread, which is more overhead than sleeping.

**Comment by sipsorcery** [comment]
That sounds like a great improvement! Please do submit a PR.

**Comment by apdevelop** [comment]
>  `Task.Delay()` sets a timer and has to process a callback on another thread...

Just wondering, why `Task.Delay`, which is intended for use in `async` methods, has appeared in non-async `void ProcessPendingTransactions()` :smiley:

**Comment by sipsorcery** [comment]
> Just wondering, why `Task.Delay`, which is intended for use in `async` methods, has appeared in non-async `void ProcessPendingTransactions()` 😃

Due to me still learning about the intricacies of [Task Asynchronous Programming](https://github.com/sipsorcery/sipsorcery/issues/164) when I recently refactored the `SIPTransactionEngine` class a few months ago. And you're right it should have been left as `Thread.Sleep`.

**Comment by RobinsonWM** [comment]
Thanks so much for the quick attention!
