### ISSUE TITLE
Convert via FFMPEG

### ISSUE THREAD

**Issue by TheSuunny** [sipsorcery/sipsorcery#184]
Hi, maybe someone faced the same problem, I'm trying to convert the received sound with OnRtpPacketReceived via FFMPEG, since I am on Linux and NAudio is not fully ported to .net standard, I convert the received mu-law to 16 bits and transfer them to FFMPEG with -f s16le, as a result, an acceleration effect occurs, the sound is correct, but this feeling is accelerated by 5 times, tell me please, maybe I'm doing something wrong?

FFMPEG Process: 

```
new ProcessStartInfo
{
    FileName = "ffmpeg",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    RedirectStandardInput = true,
    Arguments = $"-f s16le -i pipe: -vn -ar 44100 -ac 2 -b:a 192k output.mp3" //TODO: pipe:1
};
```

FFMPEG Log:

```
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, s16le, from 'pipe:':
  Duration: N/A, bitrate: 705 kb/s
    Stream #0:0: Audio: pcm_s16le, 44100 Hz, mono, s16, 705 kb/s
Output #0, mp3, to 'output.mp3':
  Metadata:
    TSSE            : Lavf57.56.101
    Stream #0:0: Audio: mp3 (libmp3lame), 44100 Hz, stereo, s16p, 192 kb/s
    Metadata:
      encoder         : Lavc57.64.101 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
^Csize=     161kB time=00:00:06.81 bitrate= 193.5kbits/s speed=0.0855x    
video:0kB audio:160kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.408504%
```
[output.zip](https://github.com/sipsorcery/sipsorcery/files/4415581/output.zip)

**Comment by apdevelop** [comment]
The PCMU (G.711 PCM µ-Law) audio format has 8000 Hz sample rate and single (mono) channel.

**Comment by sipsorcery** [comment]
The default RTP profile for PCMU/PCMA uses 8k, 8 bit and mono.

First thing to try is changing:
 - `-f s16le` to `-f s8`
 -  `-ar 44100` to `-ar 8k`
 - `-ac 2` to `-ac 1`

Perhaps:
` $"-f s8 -i pipe: -vn -ar 8k -ac 1 -b:a 192k output.mp3"`

For reference here are the ffmpeg commands I use for the opposite operation of converting an mp3 into a format that can be directly sent via RTP:

````
ffmpeg -i Macroform_-_Simplicity.mp3 -ar 8k -ac 1 -f mulaw Macroform_-_Simplicity.ulaw
ffmpeg -i Macroform_-_Simplicity.mp3 -ar 8k -ac 1 -f alaw Macroform_-_Simplicity.alaw
````

**Comment by apdevelop** [comment]
> 8 bit
Actually these isn't simple linear (LPCM) 8bits, but compressed using log function (A-law/µ-Law)

But received data is already converted to 16bit (common s16le)
> I convert the received mu-law to 16 bits

**Comment by TheSuunny** [comment]
It already gives a slightly different result, but it’s accelerated several times anyway, maybe I did something wrong here, to be honest, I’m not very good at audio codecs, and almost did not work with audio in my life.

From example, but I tried to convert immediately through FFMPEG, result is the same

``` 
short pcm = NAudio.Codecs.MuLawDecoder.MuLawToLinearSample(sample[index]);
byte[] pcmSample = new byte[] { (byte)(pcm & 0xFF), (byte)(pcm >> 8) };

FFmpeg.StandardInput.BaseStream.Write(pcmSample, 0, 2);
```

FFMPEG Process: 

```
new ProcessStartInfo
{
    FileName = "ffmpeg",
    UseShellExecute = false,
    RedirectStandardOutput = true,
    RedirectStandardInput = true,
    Arguments = "-f s8 -i pipe: -vn -ar 8k -ac 1 -b:a 192k output.mp3"
};
```

FFMPEG Log:

```
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, s8, from 'pipe:':
  Duration: N/A, bitrate: 352 kb/s
    Stream #0:0: Audio: pcm_s8, 44100 Hz, mono, u8, 352 kb/s
Output #0, mp3, to 'output.mp3':
  Metadata:
    TSSE            : Lavf57.56.101
    Stream #0:0: Audio: mp3 (libmp3lame), 8000 Hz, mono, s16p, 192 kb/s
    Metadata:
      encoder         : Lavc57.64.101 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s8 (native) -> mp3 (libmp3lame))
^Csize=     109kB time=00:00:13.61 bitrate=  65.5kbits/s speed=0.177x    
video:0kB audio:107kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.349804%
Exiting normally, received signal 
```
[output.zip](https://github.com/sipsorcery/sipsorcery/files/4415881/output.zip)

**Comment by sipsorcery** [comment]
Ah I missed that you're setting some of your ffmpeg parameters for the output rather than the input. All parameters after your input of  `-i pipe` are applying to the output whereas you need them on the input. Try:

`$"-f s8 -ar 8k -ac 1 -i pipe: -vn-b:a 192k output.mp3"`

The output from ffmpeg should report something close to this:

````
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, s8, from 'pipe:':
  Duration: N/A, bitrate: 64 kb/s
    Stream #0:0: Audio: pcm_s8, 8000 Hz, mono, u8, 64 kb/s
````

**Comment by apdevelop** [comment]
> -f s8

Not sure...  maybe `-f mulaw` or `-f s16le` (if converted `µ-Law` to `PCM` by own code)  will be proper format?

**Comment by sipsorcery** [comment]
Actually I think I've still got it wrong. If you're piping RTP payloads directly then your packets will be in mulaw or alaw format not pcm. Try:

`$"-f mulaw -ar 8k -ac 1 -i pipe: -vn -b:a 192k output.mp3"`

Expected output should be along the lines of:

````
Input #0, mulaw, from 'the_simplicity.ulaw':                                                                              Duration: 00:04:39.01, bitrate: 64 kb/s                                                                                   
 Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s   
````

**Comment by sipsorcery** [comment]
@apdevelop ahead of me by 40 seconds 🥇 . I should have run my ffmpeg test before posting...

**Comment by TheSuunny** [comment]
@sipsorcery @apdevelop Oh yes, thank you very much for your help :)
