### ISSUE TITLE
Conversion from 16hkz PCM to PCMA/U

### ISSUE THREAD

**Issue by paulnearney** [sipsorcery/sipsorcery#186]
I have a file containing 16khz, 16 bit PCM that I need to encode/decode to PCMA or PCMU. I'm using this as an audio source, as per the SendMusicSample method in RTPAudioSession.

I'm encoding using the following code:

```
var inputBufferSize = 320;
var outputBufferSize = 160;
byte[] pcm = _reader.ReadBytes(inputBufferSize);
byte[] encodedSample = new byte[outputBufferSize];

var outputIndex = 0;
for (int inputIndex = 0; inputIndex < inputBufferSize; inputIndex += 2)
{
    if (_sendingFormat.FormatCodec == SDPMediaFormatsEnum.PCMA)
    {
        encodedSample[outputIndex] = ALawEncoder.LinearToALawSample(BitConverter.ToInt16(pcm, inputIndex));
    }
    else
    {
        encodedSample[outputIndex] = MuLawEncoder.LinearToMuLawSample(BitConverter.ToInt16(pcm, inputIndex));
    }
    outputIndex++;
}

SendAudioFrame((uint)encodedSample.Length, (int)_sendingFormat.FormatCodec, encodedSample);
```

The quality of the audio that gets played to the caller is great, but it runs at half speed. From what I can make out, there seems to be an assumption that the source audio is sampled at 8khz.

Is this correct? If so, how would I go about changing this assumption? I've tried dropping every other sample from the source, but I end up with poorer quality audio playing at half speed.

**Comment by apdevelop** [comment]
The conversion you need to perform on source audio is called **resampling** and it can use various algorithms. `NAudio` library contains several classes and methods to perform this task, see [Resampling Audio](https://github.com/naudio/NAudio/blob/master/Docs/Resampling.md).

**Comment by sipsorcery** [comment]
Can you use ffmpeg to resample the file down to 8KHz and then play it? That's what I did for all the sample music files in the examples.

**Comment by paulnearney** [comment]
> Can you use ffmpeg to resample the file down to 8KHz and then play it? That's what I did for all the sample music files in the examples.

Thanks, but I'm working with on-the-fly data, so there's no file to encode. As @apdevelop mentioned, resampling would be the way forward. Fortunately for me, I'm also able to change my source stream to a 16khz format, so that sidesteps the need for resampling.
