### ISSUE TITLE
ObjectDisposedException in RTPChannel.ControlSocketReceive

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#19]
The probable cause is the use of .Close() rather than .Shutdown(how) in RTPChannel.Close()

But I'm working on 3rd hand advice for that.

**Comment by sipsorcery** [comment]
The most obvious cause I could see for this was a 0 byte read in the ControlSocketReceive method. I've added  and committed a check for that condition.

**Comment by sipsorcery** [comment]
The `RTPChannel` is a humungous beast that will be removed in the near future. 

WebRTC introduced a number of additional protocols that need to be multiplexed on RTP sockets and attempting to do all that in a single class such as the `RTPChannel` exacerbates an already poor design.

I'm hoping to have a better alternative available in the coming weeks.
