### ISSUE TITLE
Finding sipClient problem

### ISSUE THREAD

**Issue by b0gdannn** [sipsorcery/sipsorcery#193]
![image](https://user-images.githubusercontent.com/62012231/79109844-d968d200-7d81-11ea-9e33-c98177627fdc.png)

This project is based on your Sotftphone , when i try to call CallButton_Click from usercontrol form(is works like notification)
 its shows me error,but when i call it from main form it works perfectly.
Plz help.

**Comment by sipsorcery** [comment]
The way the softphone example works is to create two SIP clients to demonstrate how two simultaneous calls can be managed. Each SIP client is independent.

If you are refactoring the example into a user control (which is a good idea) then it's likely you only want a single SIP client instance for each user control. To manage simultaneous calls you could instantiate a new instance of your control.

If that is the case then you can get rid of the `_sipClients` list and just manage an instance of `SIPClient`. All the logic where the softphone is choosing between one of the two SIP clients based on which button is pressed can be removed from your user control and just use the `SIPClient` instance.

**Comment by sipsorcery** [comment]
Please re-open if still a probelm.
