### ISSUE TITLE
UASInviteTransaction does not retransmit provisional responses

### ISSUE THREAD

**Issue by RobinsonWM** [sipsorcery/sipsorcery#194]
I believe SIPSorcery when acting as a UAS for an `INVITE` transaction does not conform with a requirement in [rfc3261#section-17.2.1](https://tools.ietf.org/html/rfc3261#section-17.2.1):
> If a request retransmission is received while in the "Proceeding" state, the most recent provisional response that was received from the TU MUST be passed to the transport layer for retransmission.

When my application receives an `INVITE` request, I create a new `UASInviteTransaction` and `SIPServerUserAgent`, and I call `UserAgent.Progress()` to send a provisional response.  If the remote client retransmits the `INVITE` request (for example because the provisional response was sent over UDP and was dropped on the network,) SIPSorcery's UAS does not retransmit the provisional response.  This forces the remote client to continue retransmitting the `INVITE` request until the UAS decides to answer.

Each time the UAS receives the client's retransmission of the `INVITE` request, I see the UAS hit this log statement: https://github.com/sipsorcery/sipsorcery/blob/448a8d7ceba43cc8dffd73ba997d42e115c34425/src/core/SIP/SIPTransport.cs#L849

I believe the correct behavior, if no final response has been sent, but a provisional response has been sent, is to retransmit the provisional response.

**Comment by sipsorcery** [comment]
Thanks for the bug report. Should be fixed on `master`.
