### ISSUE TITLE
SIPSorcery examples with .NET Framework

### ISSUE THREAD

**Issue by alinoob** [sipsorcery/sipsorcery#195]
I am trying to make the GetStarted example work on .NET Framework but I always get the following exception: „System.IO.FileNotFoundException“ File or Assembly „System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a“ not found.
 
I am using Visual Studio 2019 with .NET Framework 4.7 and SIPSorceryMedia -v 4.0.28-pre.
With .NET Core I can run the examples without any issue. Can you help me finding out a solution?
Thanks in advance.

**Comment by sipsorcery** [comment]
I've added an [example](https://github.com/sipsorcery/sipsorcery/blob/master/examples/GetStartedNetFramework/Program.cs) for the .Net Framework.

It uses NAudio for audio capturing and rendering so is Windows specific.

**Comment by alinoob** [comment]
Its not working for me.

When I run your example, I get an error on line 33 where the AddConsoleLogger is called with the following exception: 
System.IO.FileNotFoundException: File or Assembly "netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" not found.

After commenting it out, I get this exception: 
System.TypeInitializationException: "demo.NAudioRtpSession"." FileNotFoundException: File or Assembly "netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" not found.

**Comment by sipsorcery** [comment]
Are you sure you're not targeting an earlier version of the .Net Framework?

You need at least [4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) to support the netstandard2.0 target that the library is built for.

**Comment by alinoob** [comment]
![image](https://user-images.githubusercontent.com/33087350/80636355-9edb8680-8a5d-11ea-9e6c-284d0a37f007.png)

This shoudn't be the problem I think.

**Comment by alinoob** [comment]
BTW: After commenting out the Console Logger, the exception occurs on line 38 where a NAudioRtpSession is instanciated.

**Comment by sipsorcery** [comment]
Have you done a "Restore Nuget Packages" on the solution?

![netframework](https://user-images.githubusercontent.com/197660/80636827-f4139a00-8a55-11ea-8975-73b020a26c86.png)

**Comment by alinoob** [comment]
If this is what you mean:

![image](https://user-images.githubusercontent.com/33087350/80637255-fb8b7100-8a5e-11ea-951d-2851bc61e202.png)

I will try to make it run on a fresh Visual Studio Installation. Strange.

**Comment by sipsorcery** [comment]
No. As below:

![nugetrestore](https://user-images.githubusercontent.com/197660/80638010-b6b00c00-8a57-11ea-92b8-360dd1979616.png)

**Comment by alinoob** [comment]
I tried restoring NuGet Packages and running the example on a fresh installation, none of them worked.

**Comment by alinoob** [comment]
May I ask which version of SIPSorcery and other packages are you running for this framwork example?

**Comment by sipsorcery** [comment]
The package versions can be seen in the project file.

Have you tried to update some of them? I recall there is a reason the Microsoft.Extensions.Logging version must be a lower version, possibly because later versions target a newer .netstandard version that is not compatible with the .Net framework.

````
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging">
      <Version>3.1.3</Version>
    </PackageReference>
    <PackageReference Include="NAudio">
      <Version>1.10.0</Version>
    </PackageReference>
    <PackageReference Include="Serilog">
      <Version>2.9.0</Version>
    </PackageReference>
    <PackageReference Include="Serilog.Extensions.Logging">
      <Version>3.0.1</Version>
    </PackageReference>
    <PackageReference Include="Serilog.Sinks.Console">
      <Version>3.1.1</Version>
    </PackageReference>
    <PackageReference Include="SIPSorcery">
      <Version>4.0.42-pre</Version>
    </PackageReference>
  </ItemGroup>
````

**Comment by alinoob** [comment]
OK, now its working.

I had the following:
`    <PackageReference Include="SIPSorcery">
      <Version>4.0.42-pre</Version>
    </PackageReference>`

Then tried to install version 4.0.42 as you have but there is no stable version of 4.0.42. So I installed version 4.0.42-pre and now its working. 0o

**Comment by alinoob** [comment]
I just edited my comment. Now I hope it makes sense. I had 4.0.43-pre installed and it didn't work. With 4.0.42-pre it works. Hope that helps you aswell.
