### ISSUE TITLE
About DTMF problem in incoming call

### ISSUE THREAD

**Issue by sduzcay** [sipsorcery/sipsorcery#199]
Hi,

First of all, thanks for your great work on SipSorcery.

We want to use SipSorcery in our call center Project and we downloaded the version 4.0.41-pre via Nuget. We have registered a VoIP line (ITSP-Sip Service Provider) and calls arrive when we call this line, it's ok, no issues.

We initiate a call from a mobile phone, and a call is received on our registered line. We can play music with an audio file or send audio over the microphone. But we can not get the dials (DTMF) from the phone we call.

Here are the issues;

- RTPEvent is not triggered.
- Since the RTPEvent event was not triggered, we tried to receive DTMFs sent using the OnRtpPacketReceived event (with **rtpPacket.Header.PayloadType** == 100 control ?? I'm not sure)
But we couldn't get them using this event. Shouldn't we be able to get DMTF in RTP events? (With RFC2833 support)

VoIP number (0850XXXXXXX) is registered, it's ok;

var regUserAgent = new SIPRegistrationUserAgent(objSIPTransport, userName, password,
registerIPAddress, expireTime);
regUserAgent.Start();

When we call it from a mobile phone, the call is received, it's ok;

  var userAgent = new SIPUserAgent(_sipTransport, null);
  var rtpSession = new RtpAVSession(
            new AudioOptions
            {
              AudioSource = AudioSourcesEnum.Microphone,
              AudioCodecs = new List<SDPMediaFormatsEnum> { SDPMediaFormatsEnum.PCMU, 				SDPMediaFormatsEnum.PCMA }
            },
            null);

  **rtpSession.OnRtpEvent += OnRtpEvent;
  rtpSession.OnRtpPacketReceived += OnRtpPacketReceived;**

   var uas = userAgent.AcceptCall(sipRequest);
    _ = await userAgent.Answer(uas, rtpSession);
   if (userAgent.IsCallActive)
          await rtpSession.Start();

We are starting the call from 0555XXXXXXX(mobil phone) to 0850XXXXXXX(sip based service provider phone) and the call is arriving. We send an audio file (or we can get voice from the microphone), but we cannot get the dtmf from 0555XXXXXXX.

Our connection structure is attached.

What are we doing wrong in our code?

Thanks.

![connection-structure](https://user-images.githubusercontent.com/20154144/79639799-884c4a00-8196-11ea-820c-183a4fbd4163.png)

**Comment by sipsorcery** [comment]
There are 3 ways that I know of to transmit DTMF events with SIP;

 - [RFC2833](https://tools.ietf.org/html/rfc2833): RTP Events which is the only mechanism currently implemented in this library,
 - Using [SIP INFO](https://tools.ietf.org/html/rfc6086). While there is no explicit handling in the library an event could be added to [SIPClient.DialogRequestReceivedAsync](https://github.com/sipsorcery/sipsorcery/blob/4132ae301078ac940ddd690416cfc2b9f80be52f/src/app/SIPUserAgents/SIPUserAgent.cs#L683) if required,
 - The final mechanism is the DTMF tones being sent in the audio stream. In that case your application will have to add logic to process the incoming stream to monitor for DTMF. It's actually not that tricky as DTMF tones are relatively easy to extract from an audio signal, see this [SO question](https://stackoverflow.com/questions/7598445/detect-dtmf-tones-c-sharp).

Your first step is to work out what DTMF mechanism the remote party is using. Your SIP Provider may even have a setting which allows you to choose.

**Comment by sduzcay** [comment]
Thank you for your quick response.

rtpPacket.Header.PayloadType can sometimes the DTMF tones are being captured in the onrtpPacketReceived event. 
It seems that when calls come from certain carriers that the DTMF tones don't work all the time.  
We will try to detect DTMF tones in the live audio stream.
