### ISSUE TITLE
No Sequence Elements in SIPTransport.GetDefaultEndPoint

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#20]
Cause is elements being added to m_sipChannels dictionary while collection is being enumerated.

Suggest changing dictionary to concurrent, or putting locks around the add and remove steps and a method of just grabbing the collection of values inside the same lock.

Suspect this is timing dependent / DNS resolution as a retry usually succeeds

**Comment by rwil02** [comment]
SIPClient.InitialiseSIP() is done on a new thread.
It starts by assigning SIPClientTransport, then configuring it,
Should create a local variable, configure it, then assign it to SIPClientTransport.

And I should check my "configured" flag that I added

**Comment by sipsorcery** [comment]
The only times the m_sipChannels dictionary is modified are when a SIP channel is added or removed. In all the cases I've used the SIPTransport class I've only ever added channels when the application initialises and removed channels when it shuts down.

I'd rather not add a lock as that's a fair bit of overhead for the GetDefaultEndPoint and other methods that are called frequently.

Those things aside the exception in the issue title looks like it wasn't to do with concurrent access to m_sipChannels but that GetDefaultEndPoint was called before a channel had been added to the SIPTransport class. A check could be made for that condition and an ApplicationException thrown butthat wouldn't gain much as the exception that did get thrown is pretty explanatory.

**Comment by rwil02** [comment]
Yeah, I ended up adding a "Configured" flag and setting it at the end of the InitialiseSIP function, then just waiting until it was set before continuing.

I was mostly getting the "No Sequence" error and sometimes "the collection was modified", which is what lead me to it in the end.

**Comment by sipsorcery** [comment]
I was able to reproduce this exception by calling `GetDefaultSIPEndPoint` on a `SIPTransport` instance with no SIP channels added. I've added an extra check and now throw a more appropriate exception.

````
try
{
	SIPTransport transport = new SIPTransport();
	var defaultEndPoint = transport.GetDefaultSIPEndPoint();
}
catch (Exception excp)
{
	logger.LogError(excp.Message);
}           
````

results in

````
[15:50:57 ERR] No SIP channels available.
````
