### ISSUE TITLE
Cannot run webrtc examples due to missing pfx file

### ISSUE THREAD

**Issue by japj** [sipsorcery/sipsorcery#201]
The  WEBSOCKET_CERTIFICATE_PATH = "certs/localhost.pfx" file is missing from the repository.
(probably due to the .gitignore file)

This causes the examples to not work "out of the box".

Also, the samples check for the existence of the other cert files, perhaps they should also check for the websocket one.

**Comment by sipsorcery** [comment]
Should be fixed.

**Comment by japj** [comment]
Unfortunately I now get the following in WebRTCTestPatternServer:
20-4-2020 17:52:28|Error|<>c__DisplayClass71_0.<receiveRequest>b__0|Authentication failed, see inner exception.

and in chrome devtools:
webrtc.html:16 WebSocket connection to 'wss://localhost:8081/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

**Comment by sipsorcery** [comment]
Welcome to the World of Pain that is getting modern day browsers to accept `localhost` certificates.

I put some detailed "notes for self" last time I went through it in the comments at the top of this [source file](https://github.com/sipsorcery/sipsorcery-media/blob/master/examples/WebRtcDaemon/WebRTCDaemon.cs).
