### ISSUE TITLE
STUN Server

### ISSUE THREAD

**Issue by maddinthegreat** [sipsorcery/sipsorcery#203]
Hello,

where to set a STUN server uri in client code like in SIPClientUserAgent or SIPUserAgent ?

Regards
Martin

**Comment by sipsorcery** [comment]
You can't set the STUN server. Instead you need to manage the STUN task in your app (see [here](https://github.com/sipsorcery/sipsorcery/blob/master/examples/Softphone/Signalling/STUNClient.cs) for a simple example client) and then set the public IP address as and when you need. The two places you are likely to want to set the public IP address are:

 - `SIPTransport.ContactHost`. This will result in the public IP being set in the SIP `Contact` header of requests and responses generated by a `SIPTransport` instance.

 - `IMediaSession.CreateOffer` and  `IMediaSession.CreateAnswer` (most likely with the `RtpAVSession` implementation). This will result in the public IP being set as the connection address in the SDP.

In both cases you need to be a little bit careful. If all you care about is calls to/from your network to the Internet it's fine to set the public IP address everywhere.

But if you need to mix calls to/from the Internet and to/from your private network then you only want to set the public IP on the Internet calls.

**Comment by maddinthegreat** [comment]
Hi Aaron,

1. Request the IP my public IP by a STUN server
2. Then connect to the remote SIP-server

Right?

Regards

**Comment by maddinthegreat** [comment]
Thanks!
