### ISSUE TITLE
OnCallHungup

### ISSUE THREAD

**Issue by maddinthegreat** [sipsorcery/sipsorcery#204]
Hi,

the event "OnCallHungup" gets only called when I call userAgent.Hangup(), but not when the remote party hung up.
How to detect if the remote party hung up?

Regards

**Comment by sipsorcery** [comment]
I tested a couple of calls and the event was getting fired when the remote party did the hangup.

Which app are you using? The `SIPCallServer` is a good app to troubleshoot and get logs with. It can call out or receive calls and is generating a log message to indicate which party hungup.

**Comment by maddinthegreat** [comment]
Hi,

when is just use: `ua.Call(DEFAULT_CALL_DESTINATION, null, null, rtpSession);`
i always get: 

> [02:53:42 DBG] Response 407 Proxy Authentication Required for sip:493066405156@1und1.de.
[02:53:42 DBG] Forward leg failed, authentication was requested but no credentials were available.
[02:53:42 WRN] Call attempt to sip:493066405156@1und1.de failed with Authentication requested when no credentials available.
[02:53:42 WRN] sip:493066405156@1und1.de:5060 Failed: Authentication requested when no credentials available, Status code: 407

When i use the SIPCallDescriptor then this works.

Generally, I use my router AVM FritzBox as a server. I'm the client and i'll get no Hangup-Event triggered.
With PJSIP this works. Must be something in your code.

Martin

**Comment by sipsorcery** [comment]
The `ua.Call` is failing because you haven't set the username and password fields and your server wants credentials.

> Generally, I use my router AVM FritzBox as a server/proxy/forwarder. I'm the client and i'll get no HangUp-Event triggered.
With PJSIP this works. Must be something in your code.

Yes that could certainly be the case. It helps a lot to track it down if I can get a SIP trace which the console log messages of the `SIPCallServer` example will provide.

**Comment by maddinthegreat** [comment]
Hi,

i provided my credentials explicitly with:

`ua.Call(DEFAULT_CALL_DESTINATION, "4930xxxxxxxxx", "xyz123", rtpSession);`
It does not work.

When using the CallDescriptor i'll get:
`Call attempt was answered with failure response INVITE 403 Private IP im Contact-Header`

Regards

**Comment by sipsorcery** [comment]
In that case the same thing must happen if you use either of the `uac.Call` overloads.

Looks like the solution to use your SIP Provider is to set both your credentials and the `SIPTransport.ContactHost` with your public IP as we touched on in this [issue](https://github.com/sipsorcery/sipsorcery/issues/203#issuecomment-618012574).

**Comment by maddinthegreat** [comment]
Hmm, set ContactHost to my public IP (router) like so:

`sipTransport.ContactHost = "23.122.96.66";`

hasn't worked either.

Let it be for a while, later try it again.

Martin
