### ISSUE TITLE
"BYE" not sending on hangup if DNS cache is out of date

### ISSUE THREAD

**Issue by paulnearney** [sipsorcery/sipsorcery#208]
I'm seeing in issue which is reproducible with the SipCallServer example. When a call is hung up, the BYE intermittently (but quite frequently) doesn't get sent.

It seems to be related to the DNS manager. If it has to refresh the cache, the BYE doesn't get sent. In the screenshot below, the first hangup resulted in no BYE being sent. On the second hangup, the BYE was sent just fine:

![image](https://user-images.githubusercontent.com/50833925/80282473-afac9500-8709-11ea-8e3b-c076e6924b53.png)

Is this a known way to work around this?

**Comment by sipsorcery** [comment]
When you say second BYE do you mean the next send attempt on the same call or a completely different call?

The SIP transport layer copes with DNS caches misses by proceeding without blocking and letting the next request/response retransmit use the DNS lookup result returned in the interim. 

The SIP retransmit mechanism works by attempting to re-send at 0.5s, 1s, 2s, 4s, 8s, 12s... up to 32s for a total of 11 re-send attempts. As long as the DNS resolution succeeds within 32s one of the re-send attempts will be able to use the lookup result.

**Comment by paulnearney** [comment]
Thanks Aaron, the second BYE is on a completely different call. From what I can make out, that was sent successfully because the DNS cache lookup succeeded.

Thanks for the retransmission info - looking at the screenshot, it looks like the DNS result was returned within a second, so I’m not sure why the BYE doesn’t get sent. That at least gives me something to investigate.

On 25 Apr 2020, at 17:25, Aaron Clauson <notifications@github.com> wrote:

﻿

When you say second BYE do you mean the next send attempt on the same call or a completely different call?

The SIP transport layer copes with DNS caches misses by proceeding without blocking and letting the next request/response retransmit use the DNS lookup result returned in the interim.

The SIP retransmit mechanism works by attempting to re-send at 0.5s, 1s, 2s, 4s, 8s, 12s... up to 32s for a total of 11 re-send attempts. As long as the DNS resolution succeeds within 32s one of the re-send attempts will be able to use the lookup result.

**Comment by sipsorcery** [comment]
How was the hangup being initiated when you were using the `SIPCallServer` example?

If you were pressing the 'H' or 'h' keys then a SIP transaction gets created which should send the BYE request reliably and retry in the event of a DNS lookup not being ready.

The block of code that create the hangup request is [here](https://github.com/sipsorcery/sipsorcery/blob/12c5e724d9f60b60eb733afe0cd2d11f4f63d96e/src/core/SIP/SIPDialogue.cs#L329).

````
SIPRequest byeRequest = GetInDialogRequest(SIPMethodsEnum.BYE);
SIPNonInviteTransaction byeTransaction = new SIPNonInviteTransaction(sipTransport, byeRequest, byeOutboundProxy);
byeTransaction.SendRequest();
````

If that code path does not result in an attempt to resend the BYE request then there's a bug somewhere.
