### ISSUE TITLE
WebRTC DataChannel support

### ISSUE THREAD

**Issue by Terricide** [sipsorcery/sipsorcery#209]
I was just curious to know if WebRTC DataChannel support is on the roadmap to implement?

**Comment by sipsorcery** [comment]
I'd say it'd be more of a nice to have. It'd be great to have a dotnet WebRTC implementation that's functionally equivalent to Google's libwebrtc. It's unclear if/when I'll get around to it. On the plus side I see there's now at least one project with a dotnet [SCTP](https://github.com/forestrf/sctp4cs) implementation so theoretically it may not be a big job to intergrate. PR's welcome.

**Comment by Terricide** [comment]
That would be awesome to have a full webrtc stack for c# like pion webrtc for golang.

**Comment by Terricide** [comment]
I'm curious if I could get my boss to sponsor this feature how much would it cost to implement it? Maybe I could get a few people in on it.

**Comment by sipsorcery** [comment]
I'd say at this particular time a sponsorship donation to the project would get some good mileage on a feature request :).

The first step for anyone, including me, looking at WebRTC data channels is to find a working SCTP implementation, either the one I linked above or an alternative. TBH I don't know how long it would take to do that or the subsequent wiring up of the WebRTC logic. It could be a couple of days or a couple of weeks.
