### ISSUE TITLE
Attended transfer SIP/2.0 404 Not found

### ISSUE THREAD

**Issue by blendR8** [sipsorcery/sipsorcery#211]
I have a problem when trying to to an attended transfer. Here is my log:

`[14:03:27 DBG] Request Sent udp:10.10.10.25:5060<-udp:10.10.10.5:5060: REFER sip:+493*******@10.10.10.5:5060 SIP/2.0.
[14:03:27 DBG] Request sent: udp:10.10.10.25:5060->udp:10.10.10.5:5060
[14:03:27 DBG] REFER sip:+493*******@10.10.10.5:5060 SIP/2.0
Via: SIP/2.0/UDP 10.10.10.25:5060;branch=z9hG4bK8b14e8b3deac4af29049cecfab33bfb9;rport
To: "Durchwahl: +493*******" <sip:+493*******@10.10.10.5>;tag=as0e332af4
From: <sip:10.10.10.25:5060>;tag=UOWVAIMFMQ
Call-ID: 680242e01e0d4aff685836eb6140cd72@10.10.10.5:5060
CSeq: 105 REFER
Contact: <sip:10.10.10.25:5060>
Max-Forwards: 70
Content-Length: 0
Refer-To: <sip:+493*******@10.10.10.5:5060?Replaces=680242e01e0d4aff685836eb6140cd72%4010.10.10.5:5060%3Bto-tag%3Das0e332af4%3Bfrom-tag%3DUOWVAIMFMQ>
Referred-By: "Durchwahl: +493*******" <sip:+493*******@10.10.10.5>

[14:03:27 DBG] Response Received udp:10.10.10.25:5060<-udp:10.10.10.5:5060: REFER 202 Accepted.
[14:03:27 DBG] Response received: udp:10.10.10.25:5060<-udp:10.10.10.5:5060
[14:03:27 DBG] SIP/2.0 202 Accepted
Via: SIP/2.0/UDP 10.10.10.25:5060;branch=z9hG4bK8b14e8b3deac4af29049cecfab33bfb9;received=10.10.10.25;rport=5060
To: "Durchwahl: +493*******" <sip:+493*******@10.10.10.5>;tag=as0e332af4
From: <sip:10.10.10.25:5060>;tag=UOWVAIMFMQ
Call-ID: 680242e01e0d4aff685836eb6140cd72@10.10.10.5:5060
CSeq: 105 REFER
Contact: <sip:+493*******@10.10.10.5:5060>
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH
Supported: replaces, timer
Content-Length: 0
Server: Asterisk PBX 11.3.0

[14:03:27 INF] Call transfer was accepted by remote server.
[14:03:27 DBG] Request Received udp:10.10.10.25:5060<-udp:10.10.10.5:5060: NOTIFY sip:10.10.10.25:5060 SIP/2.0.
[14:03:27 DBG] Request received: udp:10.10.10.25:5060<-udp:10.10.10.5:5060
[14:03:27 DBG] NOTIFY sip:10.10.10.25:5060 SIP/2.0
Via: SIP/2.0/UDP 10.10.10.5:5060;branch=z9hG4bK0fbba21c;rport
To: <sip:10.10.10.25:5060>;tag=UOWVAIMFMQ
From: "Durchwahl: +493*******" <sip:+493*******@10.10.10.5>;tag=as0e332af4
Call-ID: 680242e01e0d4aff685836eb6140cd72@10.10.10.5:5060
CSeq: 103 NOTIFY
Contact: <sip:+493*******@10.10.10.5:5060>
Max-Forwards: 70
User-Agent: Asterisk PBX 11.3.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH
Supported: replaces, timer
Content-Length: 23
Content-Type: message/sipfrag;version=2.0
Event: refer;id=105
Subscription-State: terminated;reason=noresource

SIP/2.0 404 Not found

[14:03:27 DBG] Response Sent udp:10.10.10.25:5060<-udp:10.10.10.5:5060: NOTIFY 200 Ok.
[14:03:28 DBG] Response sent: udp:10.10.10.25:5060->udp:10.10.10.5:5060
[14:03:28 DBG] SIP/2.0 200 Ok
Via: SIP/2.0/UDP 10.10.10.5:5060;branch=z9hG4bK0fbba21c;rport=5060;received=10.10.10.5
To: <sip:10.10.10.25:5060>;tag=UOWVAIMFMQ
From: "Durchwahl: +493*******" <sip:+493*******@10.10.10.5>;tag=as0e332af4
Call-ID: 680242e01e0d4aff685836eb6140cd72@10.10.10.5:5060
CSeq: 103 NOTIFY
Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, PRACK, REFER, REGISTER, SUBSCRIBE
Content-Length: 0

[14:03:28 DBG] Transfer failed NotFound
[14:03:28 DBG] True
[14:03:28 DBG] Request Received udp:10.10.10.25:5060<-udp:10.10.10.5:5060: NOTIFY sip:10.10.10.25:5060 SIP/2.0.
[14:03:28 DBG] Request received: udp:10.10.10.25:5060<-udp:10.10.10.5:5060
[14:03:28 DBG] NOTIFY sip:10.10.10.25:5060 SIP/2.0
Via: SIP/2.0/UDP 10.10.10.5:5060;branch=z9hG4bK0fbba21c;rport
To: <sip:10.10.10.25:5060>;tag=UOWVAIMFMQ
From: "Durchwahl: +493*******" <sip:+493*******@10.10.10.5>;tag=as0e332af4
Call-ID: 680242e01e0d4aff685836eb6140cd72@10.10.10.5:5060
CSeq: 103 NOTIFY
Contact: <sip:+493*******@10.10.10.5:5060>
Max-Forwards: 70
User-Agent: Asterisk PBX 11.3.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH
Supported: replaces, timer
Content-Length: 23
Content-Type: message/sipfrag;version=2.0
Event: refer;id=105
Subscription-State: terminated;reason=noresource

SIP/2.0 404 Not found

[14:03:28 DBG] Response Sent udp:10.10.10.25:5060<-udp:10.10.10.5:5060: NOTIFY 200 Ok.
[14:03:28 DBG] Response sent: udp:10.10.10.25:5060->udp:10.10.10.5:5060
[14:03:28 DBG] SIP/2.0 200 Ok
Via: SIP/2.0/UDP 10.10.10.5:5060;branch=z9hG4bK0fbba21c;rport=5060;received=10.10.10.5
To: <sip:10.10.10.25:5060>;tag=UOWVAIMFMQ
From: "Durchwahl: +493*******" <sip:+493*******@10.10.10.5>;tag=as0e332af4
Call-ID: 680242e01e0d4aff685836eb6140cd72@10.10.10.5:5060
CSeq: 103 NOTIFY
Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, PRACK, REFER, REGISTER, SUBSCRIBE
Content-Length: 0

[14:03:28 DBG] Call transfered.
[14:03:28 DBG] Transfer failed NotFound
[14:03:37 WRN] RTCP session for local ssrc 575766542 has not had any activity for over 30 seconds.
[14:03:40 DBG] Request Received udp:10.10.10.25:5060<-udp:10.10.10.5:5060: OPTIONS sip:10.10.10.25:5060 SIP/2.0.
[14:03:40 DBG] Request received: udp:10.10.10.25:5060<-udp:10.10.10.5:5060
[14:03:40 DBG] OPTIONS sip:10.10.10.25:5060 SIP/2.0
Via: SIP/2.0/UDP 10.10.10.5:5060;branch=z9hG4bK78c59ad8;rport
To: <sip:10.10.10.25:5060>
From: "asterisk" <sip:asterisk@10.10.10.5>;tag=as6ea95c0e
Call-ID: 108ea45d7cf38c955445cdd62763b4a1@10.10.10.5:5060
CSeq: 102 OPTIONS
Contact: <sip:asterisk@10.10.10.5:5060>
Max-Forwards: 70
User-Agent: Asterisk PBX 11.3.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH
Date: Wed, 29 Apr 2020 12:03:40 GMT
Supported: replaces, timer
Content-Length: 0`

why I get a not found?

bool wasAccepted = await activeClient.AttendedTransfer(holdClient.Dialogue); is true

**Comment by sipsorcery** [comment]
Because the Asterisk server you asked to transfer, which means create a new call, doesn't permit transfers to `sip:+493*******@10.10.10.5:5060`.

Asterisk (and I guess other PBX'es) have special rules around transfers and they can be a security and billing headache. 

For example if an authorised user places a call to a guest user and that guest user then asks Asterisk to transfer the call to a premium rate number who pays for it?

**Comment by blendR8** [comment]
I did the same test in PhonerLite with the same numbers. So no, there should be anything else. The number I try to transfer to is no special number.

**Comment by sipsorcery** [comment]
Ok might be a bug then. Can you send me the SIP traces of the xfer attempt with both so I can compare? You can email them to me directly at aaron@sipsorcery.com if they are sensitive.

**Comment by blendR8** [comment]
done!

**Comment by sipsorcery** [comment]
In the trace the refer to (transfer) destinations are different for the phoner and sipsorcery traces. In the sipsorcery trace the transfer destination seems to be the same as the original caller's address. Which example app or code are you using to do the transfer?

**Comment by blendR8** [comment]
you totally wight. I had a error in my script. Thank you for the hint and sry for the additional work.
