### ISSUE TITLE
SIPClient IsOnLocalHold is true after call ended

### ISSUE THREAD

**Issue by blendR8** [sipsorcery/sipsorcery#212]
If I putt a caller in hold and the caller canceled the call after that, the IsOnLocalHold is still true. Can this be changed?

**Comment by sipsorcery** [comment]
Yep, done.

**Comment by blendR8** [comment]
thank you...when will it be available in nuget?

**Comment by sipsorcery** [comment]
It already is in `v4.0.44-pre`.
