### ISSUE TITLE
Cannot use the SIPRegistrationUserAgent over TCP

### ISSUE THREAD

**Issue by qwetboy10** [sipsorcery/sipsorcery#215]
I have this very simple program that is trying to connect to a server using version 3.6.0.
```csharp
var transport = new SIPTransport();
transport.AddSIPChannel(new SIPTCPChannel(new IPEndPoint(IPAddress.Any, 15060)));
var agent = new SIPRegistrationUserAgent(transport, "200", "password", "domain:port", 5 * 60);
agent.Start();
//If we aren't registered after 5 seconds assume registration failed
agent.RegistrationFailed += (sipuri, s) =>
{
    Log.Information("Registration Failed");
};
agent.RegistrationSuccessful += sipuri =>
{
    Log.Information("Registration Succeeded");
};
var mre = new ManualResetEvent(false);
mre.WaitOne();
```
However, I'm getting the below exception:
```
Unhandled exception. System.ApplicationException: The SIP transport layer does not have any SIP channels available for protocol udp.
   at SIPSorcery.SIP.SIPTransport.GetDefaultSIPEndPoint(SIPProtocolsEnum protocol)
   at SIPSorcery.SIP.App.SIPRegistrationUserAgent..ctor(SIPTransport sipTransport, String username, String password, String server, Int32 expiry)
   at Runner.Program.Main(String[] args) in C:\Users\wiese\Desktop\Momentum\Runner\Program.cs:line 22
```
I looked at the source code, and it seems like SIPRegistrationUserAgent has been hardcoded to use UDP. Is there anyway around this, or can I just not use SIPRegistrationUserAgent with TCP?

**Comment by sipsorcery** [comment]
The trick is you need to make sure the server you are registering with specifies TCP as the transport otherwise it defaults to UDP.

For example to register to a SIP server with a TCP transport
````
var regUserAgent = new SIPRegistrationUserAgent(sipTransport,"softphonesample", "password", "sipsorcery.com;transport=tcp", 120);
````

With the key parameter being `sipsorcery.com;transport=tcp`.

**Comment by qwetboy10** [comment]
That doesn't seem to have solved it. The format would be `something.com:port;transport=tcp` right?

**Comment by sipsorcery** [comment]
Yep that's correct. You can verify by using [UserAgentRegister](https://github.com/sipsorcery/sipsorcery/blob/master/examples/UserAgentRegister/Program.cs) example and replacing the `DOMAIN` constant at the top with:

`private const string DOMAIN = "sipsorcery.com:5060;transport=tcp";`

**Comment by qwetboy10** [comment]
If I run the UserAgentRegister example with the domain, username, and password values changed I get a No SIP channels available error. If I manually add a sip channel to the example I get the same `The SIP transport layer does not have any SIP channels available for protocol udp.` error.

**Comment by sipsorcery** [comment]
If you don't allocate a SIP channel the [default behaviour](https://github.com/sipsorcery/sipsorcery/blob/a27e7f2a504f380314dfc8fbd659fa25a28039c4/src/core/SIP/SIPTransport.cs#L946) is to try and add one for you. That's most likely what you want if you aren't expecting any SIP clients to initiate connections to your app.

But adding the SIP TCP channel manually should work fine as well. Using the same example I linked above if I make these two changes I'm able to register:

`private const string DOMAIN = "sipsorcery.com:5060;transport=tcp";`

````
// Set up a default SIP transport.
var sipTransport = new SIPTransport();
sipTransport.AddSIPChannel(new List<SIPChannel> { new SIPTCPChannel(IPAddress.Any, 7060) });
````

If it still doesn't work for you post as much of your code as you can so I can test it out.

**Comment by qwetboy10** [comment]
```csharp
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading;
using Microsoft.Extensions.Logging;
using Serilog;
using SIPSorcery.SIP;
using SIPSorcery.SIP.App;

namespace Runner
{
    class Example
    {
        private const string USERNAME = "200";
        private const string PASSWORD = "password";
        private const string DOMAIN = "domain:15060;transport=tcp";
        private const int EXPIRY = 120;

        private static Microsoft.Extensions.Logging.ILogger Log = SIPSorcery.Sys.Log.Logger;

        static void Main()
        {
            // Set up a default SIP transport.
            var sipTransport = new SIPTransport();

            sipTransport.AddSIPChannel(new List<SIPChannel> {new SIPTCPChannel(IPAddress.Any, 15060)});
            
            // Create a client user agent to maintain a periodic registration with a SIP server.
            var regUserAgent = new SIPRegistrationUserAgent(sipTransport, USERNAME, PASSWORD, DOMAIN, EXPIRY);

            // Event handlers for the different stages of the registration.
            regUserAgent.RegistrationFailed += (uri, err) => Log.LogError($"{uri.ToString()}: {err}");
            regUserAgent.RegistrationTemporaryFailure += (uri, msg) => Log.LogWarning($"{uri.ToString()}: {msg}");
            regUserAgent.RegistrationRemoved += (uri) => Log.LogError($"{uri.ToString()} registration failed.");
            regUserAgent.RegistrationSuccessful += (uri) => Log.LogInformation($"{uri.ToString()} registration succeeded.");

            // Start the thread to perform the initial registration and then periodically resend it.
            regUserAgent.Start();

            ManualResetEvent exitMRE = new ManualResetEvent(false);
            Console.CancelKeyPress += delegate (object sender, ConsoleCancelEventArgs e)
            {
                e.Cancel = true;
                SIPSorcery.Sys.Log.Logger.LogInformation("Exiting...");
                exitMRE.Set();
            };

            exitMRE.WaitOne();

            regUserAgent.Stop();
            sipTransport.Shutdown();
            SIPSorcery.Net.DNSManager.Stop();
        }
    }
```
This causes me to have the error ` The SIP transport layer does not have any SIP channels available for protocol udp.` I'm using SIP Sorcery 3.6.0 and targeting the framework netcoreapp3.1. If I change the TCP Channel to a UDP Channel it works fine.

**Comment by sipsorcery** [comment]
> I'm using SIP Sorcery 3.6.0 and targeting the framework netcoreapp3.1. 

Ah there's been a lot of fixes since then. If you're writing a new application and don't need to keep API compatibility then use the latest pre-release packet (v4.0.46-pre) that'll most likely fix the problem. TCP channels were one of the first things that got improved.

**Comment by qwetboy10** [comment]
That fixed the problem, but I'm using this for an application where stability is important. Do you have a recommendation for the most stable release that has the TCP fixes?

**Comment by sipsorcery** [comment]
The `v4.0.46-pre` release has been the result of a week of bug fixes so I'd rate it as the current best option for stability.

The main reason for the current pre-release versioning is the public interfaces are in a bit of a state of flux to accommodate WebRTC. If you're only interested in SIP there you shouldn't see much change, if any, between the pre-release versions and the next stable release (which could be 1, 2, 3 or 6 months away).

**Comment by qwetboy10** [comment]
Ok. Thanks so much for the help!
