### ISSUE TITLE
Timeout Error on GetStarted Example

### ISSUE THREAD

**Issue by alinoob** [sipsorcery/sipsorcery#217]
I am experiencing this error in my office:

`Call attempt to sip:time@sipsorcery.com failed with Timeout, no response from server.
Call result failure.`

on the GetStarted example which usually works on my PC at home but not in the office. I have already opened 5060 port for SIP. Is there a problem with more complex network topology? Or do I simply have to open more ports?

Thanks in advance!

**Comment by sipsorcery** [comment]
Almost certainly a firewall issue on your network. To get a timeout on the SIP part of the call means program couldn't reach the sipsorcery.com server on UDP 5060.

If your firewall is blocking UDP you'll probably also have issues with the RTP packets but the first step is getting SIP working.

**Comment by alinoob** [comment]
It was a router issue. Some routers from ISPs in Germany (Telekom) natively block 5060 for SIP usage, since they want you to pay for it.

**Comment by sipsorcery** [comment]
Good to hear you found the issue.
