### ISSUE TITLE
Managing ICECandidates for WebRTC

### ISSUE THREAD

**Issue by acscorrea** [sipsorcery/sipsorcery#218]
Is there a way to create my own ICECandidate for WebRTC connection?
I'm trying to receive audio stream recorded in the browser. The connection works following the `WebRTCReceiver` example, but the ICE candidates are choosen automactily. Is there a way to send my RTP Listener created in the application as a candidate?

**Comment by sipsorcery** [comment]
Good to hear it works at all. That code is hot off the presses!

What's your goal:
 - To be able to dictate which UDP socket is used for receiving the RTP media packets?
 - To be able to "fork" the RTP media packets so you can forward a copy to a different UDP socket?
 - Something else?

But no matter what your goal you don't want to set custom ICE candidates. If the ICE candidates don't match the RTP socket you're listening on the connection set up isn't going to work.

**Comment by acscorrea** [comment]
The code works, I just change the signaling method, can't use WebSockets in my application.

My goal is dictate the UDP port to be used to receive the packages.
I have my app opening some ports on firewall, but now I'd realise this is not necesary with WebRTC, rigth?

**Comment by sipsorcery** [comment]
Only this week I switched the RTP UDP port range from a pseudo random select in the range 10000-20000 to instead relying on the [OS ephemeral port range](https://en.wikipedia.org/wiki/Ephemeral_port). The main motivation for the change is that's what Chrome does and they are pretty much running the WebRTC show. 

The code doing the socket creation can be seen [here](https://github.com/sipsorcery/sipsorcery/blob/346de756cc60e5e85dec45c9fb5a66e1738b8b69/src/sys/Net/NetServices.cs#L141).

If you wanted to switch back to a hard coded range you could switch the call [here](https://github.com/sipsorcery/sipsorcery/blob/346de756cc60e5e85dec45c9fb5a66e1738b8b69/src/net/RTP/RTPChannel.cs#L269) back to `NetServices.CreateRtpSocketInRange`.

But despite all that the answer to your question is that no you generally shouldn't need to modify your firewall to establish a WebRTC connection unless UDP is blocked by default. An advantage of the change to the OS ephemeral port range is that if you can get a WebRTC connection with a browser such as Chrome or Firefox then you should be able to with this library as well.

**Comment by acscorrea** [comment]
I changed things up a bit and added the listener for the UDP port after the status of the PeerConnection changed to connected, using the port decided in IceCandidates exchange.

The listener reveice some packages and suddenly it stop receiving. First I thought it was a client problem, but investigating `chrome://webrtc-internals`, I found the line `dtlsState | connecting`.

I tried to debug the code and I having a problem with the DTLS handshake. 
`dtls.DoHandshakeAsServer((ulong)peerConnection.GetRtpChannel(SDPMediaTypesEnum.audio).RtpSocket.Handle)` aways return `-1`. I'm trying with self-signed certificates, generated as was said here [here](https://github.com/sipsorcery/sipsorcery-media/blob/master/examples/WebRtcDaemon/WebRTCDaemon.cs).

Also, dtls.IsHandshakeComplete() is hiting `System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`
I Don't know if this is a local error or if it's related to a bug

**Comment by sipsorcery** [comment]
Can you share your code?

I'm not sure why you need to do things like add a UDP listener. With WebRTC the sequence has to be done in the right order from the same socket or it's not going to work:
 - STUN exchange,
 - DTLS handshake,
 - Media.

**Comment by acscorrea** [comment]
My goal is to record audio on client-side browser, receive the packages on server and send the packages to another app. I've tried to use the listener to send the packages directly to the 3rd app.

If WebRTC needs the sequence, maybe the problem is my signaling solution, used HTTP Requests because the server is already implemented that way.

**Comment by acscorrea** [comment]
I change the signalig to websockets, but no sucess yet.
My logger is showing:
`2020-05-11 19:52:28.580 -03:00 [DBG] CreateRtpSocket start port using OS default ephemeral port range on ::.
2020-05-11 19:52:28.602 -03:00 [DBG] Successfully bound RTP socket on [::]:60134 (dual mode True).
2020-05-11 19:52:28.728 -03:00 [DBG] Adding remote audio track to session.
2020-05-11 19:52:28.728 -03:00 [DBG] Remote audio end RTP and RTCP points set from remote description to 0.0.0.0:9 and 0.0.0.0:10.
2020-05-11 19:52:28.728 -03:00 [DBG] Audio stream status set to inactive based on connection address of 0.0.0.0 in remote offer.
2020-05-11 19:52:28.889 -03:00 [DBG] Adding peer reflex ICE candidate for [2804:14d:9083:82a2:984b:91a7:4e7b:7b61]:60132.
2020-05-11 19:52:29.014 -03:00 [DBG] Adding peer reflex ICE candidate for [2804:14d:9083:82a2:6d03:7467:fa7b:1813]:60132.
2020-05-11 19:52:29.161 -03:00 [DBG] Adding peer reflex ICE candidate for 192.168.0.26:60131.`

**Comment by sipsorcery** [comment]
I've added a new [WebRTC no signalling required example](https://github.com/sipsorcery/sipsorcery/blob/master/examples/WebRTCNoSignalling/README.md), although it would be more correct to call it copy/paste signalling.

It's somewhat annoying to use compared to connecting with web sockets but if you're having difficulties getting a localhost certificate trusted it might be useful for you.

I'd recommend getting either the no signalling or [WebRTC Test Pattern](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCTestPatternServer) example working as your first step. They are the simplest examples and if you can get one of them working it's not much further for full audio/video streaming.

**Comment by acscorrea** [comment]
The certificate is not the problem, I can get bot examples working with mine certificates.
Something is breaking when I try to put the examples together with my WebAPI.

I'm running the Main method of the WebRTC Receiver on my WebAPI Startup. The inicialization seems right, the remote description is received and set properly, the answer is send and received on the browser. Right after that, the code dosen't work as expected.

```
                peerConnection.oniceconnectionstatechange += (state) =>
                {
                    if (state == RTCIceConnectionState.connected)
```
Is always hit with `state = checking`. When execute as a console application, `state = connected`.
Then, on the log it never hit the `ICE session remote credentials set.`

Maybe I'm missing something really basic, I'm new to .Net development.
Thank you for you time

**Comment by sipsorcery** [comment]
It might be something little on your send or it might be a bug in the library (as mentioned above the WebRTC code is a work in progress).

But to be able to help I really need to see your code. Doesn't matter how clean or dirty it is. You can send it me via email or an invite to a private repo if that helps.

**Comment by sipsorcery** [comment]
So after the investigation it looks like the problem is this:

````
ICE Candidate: candidate:934711376 1 udp 2113937151 9e1c6ec7-6e2d-4cf1-bc7f-721f93c7f840.local 54283 typ host generation 0 ufrag 3rYO network-cost 999
Exception WebSocketMessageReceived. An invalid IP address was specified.
ICE Candidate: candidate:269726124 1 udp 2113939711 bc8376a8-878e-4c9e-a056-7974e746b8cb.local 54284 typ host generation 0 ufrag 3rYO network-cost 999
Exception WebSocketMessageReceived. An invalid IP address was specified.
````

I haven't implemented `.local` address handling. I'll have a look at it in the near future.

In Chrome it's possible to disable `.local` addresses although be aware they are designed to provide a level of anonymity when using WebRTC. Disabling them is a privacy concern not a security one.

To disable enter `chrome://flags/#enable-webrtc-hide-local-ips-with-mdns` in the address bar and change the `Anonymize local IPs exposed by WebRTC.` to `Disabled`.

![chrome_settings](https://user-images.githubusercontent.com/197660/81786835-17c7ed00-94f8-11ea-9e4c-7033da7ec0de.png)

**Comment by sipsorcery** [comment]
@acscorrea I've added a [WebRTC ASP.Net Example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCAspNetMvc) which you may find useful. I'm using it to serve as the basis for fixing the `.local` addresses (which is not yet done but the above example will filter them out). One big difference between my example and yours is that I used HTTP GET/POST requests for the signalling instead of web sockets. Keeps things a bit simpler if you know you're going to have a web server.

**Comment by acscorrea** [comment]
Thank you for the reply,

In the example you are using `WebRTCHostedService ` for the connection, when I'm trying to handle the RTCPeerConnection the same way I did in the console app. Mayba that was the problem, I will look into it
