### ISSUE TITLE
[Help Needed] Call two users and connect calls inside app

### ISSUE THREAD

**Issue by Shadoweh** [sipsorcery/sipsorcery#219]
Greetings
Sorry if this is a duplicate. I went through examples and issues, haven't found solution.
I call two users from the application and want to connect them, so the first user will hear the second and vice versa. I can't use blind transfer from the first user, because there are many users who can receive transfer and If one doesn't answer, I should transfer to the next. I've tried to call to the second user and if one answers, use attended transfer. But I have FreeSwitch, so there is a chance that calls to the users will be done on different switches and I won't be able to use attended transfer. There can be solution: I call two users and than connect them inside app, maybe by some channels, but I haven't found examples. Could you please advice?

**Comment by sipsorcery** [comment]
So you want to do the transfer without the use of any server?

For example:
 - Alice's softphone calls Bob's softphone directly,
 - Alice puts Bob on hold and calls Charlie's softphone directly.
 - Alice does an attended transfer so that Bob and Charlie are in a call together and Alice has no call.

**Comment by Shadoweh** [comment]
Yes, it is like what I want

**Comment by sipsorcery** [comment]
The feature [doesn't yet exist](https://github.com/sipsorcery/sipsorcery/blob/346de756cc60e5e85dec45c9fb5a66e1738b8b69/src/app/SIPUserAgents/SIPUserAgent.cs#L795) at least not without having to manually process the `REFER` request.

I'll see if I can get it added this weekend.

**Comment by Shadoweh** [comment]
I think I explained it is not clear
I'm looking for something like :

- Application calls Bob's softphone directly,
- Application calls Charlie's softphone directly.
- Application connects Bob and Charlie by moving Bob's voice stream to the Charlie's listen stream and vice versa.

**Comment by sipsorcery** [comment]
Yep that's what I understood. It needs the application, in this case the softphone example, to be able to process `REFER` requests. It's missing functionality I've been meaning to get around to any way.

One word of caution is that often even if the call signalling is processed correctly the RTP audio packets will not be able to get through. If Alice or Bob or Charlie are behind a NAT getting the media set up with SIP is a real challenge (verging on nightmare). 

If they're all on the same internal private network it should work fine once I implement the `REFER` processing.

**Comment by Shadoweh** [comment]
Hello
Is there a chance, that this functionality will appear in the next two days? It's critical and I'm looking for possible solutions.
Anyway thanks a lot for the excellent library and answers.

**Comment by sipsorcery** [comment]
I've added some very early/experimental support for handling `REFER` requests in the `SIPUserAgent`. I was able to successfully do some transfers. I've added a new example [AttendedTransferee](https://github.com/sipsorcery/sipsorcery/blob/master/examples/AttendedTransferee/Program.cs) but it's pretty basic so far.

If you test it out expect to have difficulties. I do my testing with 3 different SIP softphones: sipsorcery, Bria and MicroSIP. Attended transfers fail in some respect 3/4 of the time. To get them to work often takes a particular combination of call legs.

The experimental support has been released in nuget package `v4.0.47-pre`.

**Comment by Shadoweh** [comment]
First of all thanks a lot for your help.
I will check if it works stably, will add to my app.
I've also found some third party solutions related to the Kazoo modules.
Hope any of this works.

**Comment by sipsorcery** [comment]
I've spent a bit of time on the blind and attended transfer logic in the `SIPUserAgent` class over the last few days and an now happy with the way it's working.

I was having difficulty testing transfers as you need 3 call legs and each softphone has its own set of quirks/bugs when dealing with transfers. In the end I resorted to writing some small console apps to test each of the [attended transfer](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/AttendedTransferScenario) and [blind transfer](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/BlindTransferScenario) scenarios. They may be useful if you're attempting to use this library to perform transfers.

**Comment by Shadoweh** [comment]
Thank you for your work.
The task was critical and I had to choose another solution. But now I have time and will check it.
