### ISSUE TITLE
Issue in initiating a call from a Xamarine android app

### ISSUE THREAD

**Issue by rexzing** [sipsorcery/sipsorcery#220]
When I use following code snippet with .net windows desktop application, code worked without any issues and call received to the other end. But when I try this with Xamarin android I couldn't make the call initiate and I saw following messages in my _logDelegate function. 

First time I got error message "DNS error resolving mydomain.com, Object reference not set to an instance of an object.. Call cannot proceed.". So I replaced my domain name with server IP. After that I got another message "Transaction send request reliable INVITE sip:002@0.0.0.0 SIP/2.0". After this message nothing happens and keep trying to send invite. "Transaction send request retransmit 2 INVITE sip:002@0.0.0.0 SIP/2.0" .

Is there something wrong with my code? How can I fix this issue?

            // Create a SIP user agent client that can be used to initiate calls to external SIP devices and place a call.
            SIPTransport sipTransport = new SIPTransport();
            SIPUDPChannel udpChannel = new SIPUDPChannel(new IPEndPoint(IPAddress.Any, 0));
            sipTransport.AddSIPChannel(udpChannel);
            SIPClientUserAgent uac = new SIPClientUserAgent(sipTransport, null, null, null, _logDelegate);

            SIPCallDescriptor callDescriptor = new SIPCallDescriptor("001", "password", "sip:002@mydomain.com", "<sip:001@mydomain.com>", null, null, null, null, SIPCallDirection.Out, "application/sdp", null, null);
            uac.Call(callDescriptor);`

**My development environment:**
sipsorcery version:  4.0.44-pre
Xamarin forms version: 4.3.0.908675
android version: 9P 
development machine: windows 10

**Comment by sipsorcery** [comment]
I'm pretty much a complete noob when it comes to Xamarin on Android.

Can it be checked or tested reliably in a Visual Studio emulator or is hardware needed?

**Comment by rexzing** [comment]
I checked it with emulator and also with actual device. Same result. It re-transmit the invite.

**Comment by rexzing** [comment]
Is there anything that I can do to debug the issue?

**Comment by rj2Skipper** [comment]
Hey rex,
Retransmit only happen if the SIP-Application does not receive a SIP-Response to the SIP-Request, so you might want to check first if the packets even go out of your test-device and coming into your targeted server.
 and then check if the server is sending the SIP-Response to the correct address (of your test-device)

you may want to check if the test-device even has a network connection (to your sip-trunk), and if so, if there is a firewall blocking incoming packets to the device and if IP-Addresses in the SIP-Messages are targeting the right computers/devices

ciao Ralf

**Comment by sipsorcery** [comment]
I installed the Android emulator and was able to get SIP requests sent. 

@rexzing I think you'd be better adjusting your code to something closer to:

````
// Create a SIP user agent client that can be used to initiate calls to external SIP devices and place a call.
SIPTransport sipTransport = new SIPTransport();
SIPUDPChannel udpChannel = new SIPUDPChannel(new IPEndPoint(IPAddress.Any, 0));
sipTransport.AddSIPChannel(udpChannel);
SIPUserAgent ua = new SIPUserAgent(sipTransport, null);

IMediaSession dummySession = new RtpAudioSession(new DummyAudioOptions { AudioSource = DummyAudioSourcesEnum.SineWave }, new List<SDPMediaFormatsEnum> { SDPMediaFormatsEnum.PCMU });
Task.Run(async () => await ua.Call("time@67.222.131.147", null, null, dummySession));
````
The SIP INVITE request the emulator generated was:

````
Proxy Request Received: udp:67.222.131.147:5060<-udp:37.228.2xx.xx:12654
INVITE sip:time@67.222.131.147 SIP/2.0
Via: SIP/2.0/UDP 192.168.232.2:57844;branch=z9hG4bK4d77ee8e2ac64a27826fd0b491af6037;rport
To: <sip:time@67.222.131.147:5060>
From: <sip:thisis@anonymous.invalid>;tag=IETTNWIPOU
Call-ID: dbc4c75f895a40928c8242e0c6825b61
CSeq: 1 INVITE
Contact: <sip:Anonymous@192.168.232.2:57844>
Max-Forwards: 70
User-Agent: www.sipsorcery.com
Supported: norefersub,100rel
Content-Length: 191
Content-Type: application/sdp

v=0
o=- 1431715259 0 IN IP4 127.0.0.1
s=-
c=IN IP4 192.168.232.2
t=0 0
m=audio 42474 RTP/AVP 101 0
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:0 PCMU/8000
a=sendrecv
````
The problem is the response from the server is not getting through to the Android emulator. I can see it arriving in a Wireshark capture on my Windows PC. I'd guess it's aNAT issue somewhere between Windows and the emulator software.

So instead of UDP I tried switching to TCP by appending `;transport=tcp` to the SIP address and had more success:

````
SIPTransport sipTransport = new SIPTransport();
SIPUserAgent ua = new SIPUserAgent(sipTransport, null);

IMediaSession dummySession = new RtpAudioSession(new DummyAudioOptions { AudioSource = DummyAudioSourcesEnum.SineWave }, new List<SDPMediaFormatsEnum> { SDPMediaFormatsEnum.PCMU });
Task.Run(async () => await ua.Call("3@192.168.11.50;transport=tcp", null, null, dummySession));         
````

The SIP messages now get through correctly without any retransmits. There was no audio played since the `RtpAudioSession` is a dummy class that can only generate algorithmic signals and cannot interface with real audio devices.

I do not know what's involved in connecting to audio capture and playback devices with Xamarin/Android.

**Comment by rexzing** [comment]
> I checked it with emulator and also with actual device. Same result. It re-transmit the invite.

**Comment by rexzing** [comment]
@sipsorcery Thanks for the suggestion. I will try this and let you know.

**Comment by rexzing** [comment]
Code u suggested work with 0 errors with minor modifications since my server required authentication. Thank u very much for your help. Now I'm going to implement a IMediaSession class to capture android audio. 
BTW, could you tell me what is the procedure u used to capture network traffic of the android emulator.

**Comment by sipsorcery** [comment]
Great to hear!

> Now I'm going to implement a IMediaSession class to capture android audio.

It'd be great to see this when you get it done. Cross platform audio is a requested feature and seeing how it's done on Android would be useful.

> BTW, could you tell me what is the procedure u used to capture network traffic of the android emulator.

With WireShark and selecting the `Adapter for loopback traffic capture`.

![wireshark_loopback](https://user-images.githubusercontent.com/197660/82025903-e2eb9f80-9689-11ea-8c7e-703d150fd412.png)

**Comment by rexzing** [comment]
I will share a sample code of how I implemented the cross platform audio management after my implementation. Another thing can u pls explain me how to recieve th SIP call? It is bit confusing in the sample codes. First do we need to register using  SIPRegistrationUserAgent?

**Comment by sipsorcery** [comment]
To receive a SIP call you simply respond to an incoming `INVITE` request.

What's trickier is getting the `INVITE` request to you program. That's the purpose of registering. When you register with a SIP server you are telling it where you want `INVITE` requests for your incoming calls to be sent.

 - If you want to receive calls directly via an IP address and/or on your own network you don't need to register.

 - If you want to receive calls from a public SIP server you most likely do need to register.

**Comment by rexzing** [comment]
> ```
> The problem is the response from the server is not getting through to the Android emulator. I can see it arriving in a Wireshark capture on my Windows PC. I'd guess it's aNAT issue somewhere between Windows and the emulator software.
> 
> So instead of UDP I tried switching to TCP by appending `;transport=tcp` to the SIP address and had more success:
> 
> ```
Actually SIPUserAgent .call only works with TCP in android. I tried udp with an actual device. It still didn't work.

**Comment by rexzing** [comment]
I need your help again. Since there is something wrong with UDP in Xamarin android and sip sorcery I was unable to register with my SIP server. I need a way do the SIP REGISTRATION using TCP protocol. I tried several things to accomplish that but no luck. I will describe my attempts If it helps. In the current implementation registration call from Xamarin go through UDP protocol like following header.
`SIP/2.0/UDP 192.168.137.181:45433;branch=z9hG4bKc1158b505df641aea8adaf90cfbeae50;rport`
Since it didn't work I analyzed registration request from another softphone android app which was able to register properly.It was like following.
`SIP/2.0/TCP 192.168.137.181:37325;rport;branch=z9hG4bKPj2deee544-0431-4d71-afd4-3597d0e9d5f4;alias`

I think the main difference is the transport method. How can I change this transportation method?

**Comment by sipsorcery** [comment]
Same way as for call URI's, append `;transport=tcp` to the end of the URI you are registering.

**Comment by rexzing** [comment]
I used following code to register. Where I can put the tcp. 
` 
            
           SIPURI accountAOR = new SIPURI(SIPUsername, SIPServer, null, SIPSchemesEnum.sip, SIPProtocolsEnum.tcp);

            _sipRegistrationClient = new SIPRegistrationUserAgent(
                 _sipTransportManager.SIPTransport,
                   null,
                 accountAOR,
                SIPUsername,
                SIPPassword,
                null,
                SIPServer,
                new SIPURI(accountAOR.Scheme, IPAddress.Any, 0),
                REGISTRATION_EXPIRY,
                _logDelegate, null);`

**Comment by rexzing** [comment]
When I used above code I got registration packet as follows.

![Annotation 2020-05-18 134109](https://user-images.githubusercontent.com/25826165/82189704-71238800-990d-11ea-8888-ca809c2ef8a6.png)

**Comment by sipsorcery** [comment]
Try adding the transport to the to the `SIPServer` parameter instead of the `accountAOR`.

**Comment by rexzing** [comment]
I will try

**Comment by rexzing** [comment]
Oh yeehh.. It worked.. Thank you for your support. But why accountAOR tcp config didnt work? It ads transport=tcp to the request line. Now I have two transport=tcp params in request line.

**Comment by ramazan199** [comment]
hi @rexzing could you tell me how you were able to use rtp session with xamarin forms(android app)? which library did u use for that?
