### ISSUE TITLE
How to unregister with RegistrationUserAgent

### ISSUE THREAD

**Issue by qwetboy10** [sipsorcery/sipsorcery#221]
I was trying to unregister from a SIP server by sending a REGISTER with an expiry of zero. However, after some troubleshooting, I found that SIPRegistrationUserAgent refuses to set the expiry below 10. Is there a better way to unregister from a server, or do I just need to send the REGISTER manually?

**Comment by rj2Skipper** [comment]
There is a method called "Stop" in SIPRegistrationUserAgent, that will send a zero-expiry registration request and end the registration thread

Ralf

**Comment by qwetboy10** [comment]
I see the Stop method, however, that request doesn't seem to show up on wireshark. This might be because my application is exiting before the register is sent? How can I know when the unregistration is done

**Comment by rj2Skipper** [comment]
you might want to wait for the final RegistrationSuccessful-event ?

**Comment by qwetboy10** [comment]
That worked for me. Thanks for the help, this project is amazing about answering questions quickly

**Comment by qwetboy10** [comment]
For anyone looking at this in the future, you should wait for the RegistrationRemoved event, not the RegistrationSuccessful event
