### ISSUE TITLE
DTMP event multiplied and duration

### ISSUE THREAD

**Issue by lordrak007** [sipsorcery/sipsorcery#224]
Hello,
i would like ask for help.
When i listening SipUserAgent.OnDtmfTone event it returns three times same information.
It looks this problem starts here:
private void OnRemoteRtpEvent(RTPEvent rtpEvent, RTPHeader rtpHeader)
        {
            OnRtpEvent?.Invoke(rtpEvent, rtpHeader);
            if (rtpEvent.EndOfEvent)
            {
                    OnDtmfTone?.Invoke(rtpEvent.EventID, rtpEvent.Duration);
            }
        }
OnRemoteRtpEvent called many times that is correct but it is propably mitiplied three more times.
Because i don't undestand i have solved it by ugly solution like that
        uint timestamp = 0;
        private void OnRemoteRtpEvent(RTPEvent rtpEvent, RTPHeader rtpHeader)
        {
            OnRtpEvent?.Invoke(rtpEvent, rtpHeader);

            if (rtpEvent.EndOfEvent)
            {
                if (timestamp != rtpHeader.Timestamp)
                {
                    OnDtmfTone?.Invoke(rtpEvent.EventID, rtpEvent.Duration);
                    timestamp = rtpHeader.Timestamp;
                }
            }
        }

Also duration complete lying. Time is multiplied from 3 to 7 times compated to time of pressed button on my cell phone.
Thanks

**Comment by sipsorcery** [comment]
Yes the RTP Event/DTMF handling has always been a bit lacking. The raw information is provided but it it was always left up to the calling application to extract what it needed.

Coincidentally I wanted to use DTMF handling for some testing I was doing and had a need to extract the individual DTMF tones. The logic has now been added to the [SIPUserAgent](https://github.com/sipsorcery/sipsorcery/blob/d5223ec3500fdf41bb8e776844503270ffdf8ddd/src/app/SIPUserAgents/SIPUserAgent.cs#L1456) for the `OnDtmfTone` events.

As for the duration there are no measurements taking palace so there is nothing to lie about. The volume and duration of the tones are provided in the payloads for the RTP event. You can handle the `SIPUserAgent.OnRtpEvent` to get the data exactly as provided by the remote party.
