### ISSUE TITLE
Attended Transfer not working

### ISSUE THREAD

**Issue by sduzcay** [sipsorcery/sipsorcery#225]
Hi,

We're using SIPSorcery in one of our projects and we're having issues with call transfers (attended and blind).

We tried to transfer a call to a registered agent but we couldn't do it.

We have registered a VoIP line (ITSP-Sip Service Provider) and calls arrive when we call this line, no issues.
We registered a few clients to our SIP server (e.g. lines with virtual numbers like 1200, 1300 and we've defined on softphone. - we used the SIPClientUserAgent class)

We can receive calls from the outside line(via ITSP-Sip Service Provider)  and send sound files as follows:  (incoming call **Session A**)

userAgent = new SIPUserAgent(sipTransport, null);
...
sipClient.Accept(sipRequest);
sipClient.Answer(waveFiles);
PlayWavefiles(waveFiles);
...

 no issues.

When the caller sends a DTMF, we would like to transfer the call to a registered agent. We're using the following structure to do that but currently it doesn't work:

1- To transfer(Session A), we first initiate a call to the registered agent (e.g. sip:1200@192.168.1.34:5060, we tried both Zoiper and MicroSIP)
  
...
callURI = sip:1200@192.168.1.34:5060 (registered and looks online on MicroSIP)
SIPCallDescriptor callDescriptor = new SIPCallDescriptor("", ", callURI.ToString(), fromHeader, callURI.ToString(),null, null, null, SIPCallDirection.Out, sdpMimeContentType, null, null);
               
 userAgent.Call(callDescriptor, MediaSession);  -> **Session B**
...

Issue: We couldn't receive the call on the softphone.

2- When the call is somehow successfully initiated(Session B), we would like to transfer this call to the original caller.(Attended TRANSFER between Session A and Session B.)
...
targetCall=Session B
userAgent.AttendedTransfer(targetCall.Dialogue, TimeSpan.FromSeconds(10), cancellationTokenSource.Token);
...

But we couldn't make the transfer as well. How we can solve this problem?

Thanks.

**Comment by sipsorcery** [comment]
Which version of the sipsorcery library/code are you using? 

I've been working on blind and attended transfers this very week and nuget package `v4.0.49-pre` or `master` should both be working properly.

Take a look at the [Attended](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/AttendedTransferScenario) and [Blind](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/BlindTransferScenario) transfer scenarios to see an example of how the 3 user agents interact.

**Comment by sipsorcery** [comment]
It's also worth noting I did not have much luck testing attended transfers with MicroSIP. It crashes every time for me if is used in the `Transferee` role (I did fill in their web form about it but got no response).

I successfully tested both Attended and Blind Transfer with CounterPath's Bria softphone. I haven't tested with Zoiper.

**Comment by sduzcay** [comment]
We are using v4.0.49-pre

We couldn't receive the call on the softphone (sip:1200@192.168.1.34:5060 (registered and looks online on MicroSIP).

**Comment by sipsorcery** [comment]
Troubleshooting the SIP signalling involved in transfers is tricky (Attended Transfers are probably the most complicated scenario in common SIP usage).

I'm happy to look at a Wireshark trace of your calls and see if I can decipher anything (you can email it to me directly if its sensitive). Failing that you'll need to simplify your scenario to the most basic possible, get it working and then add the components one by one. Another example of what can go wrong is a lot of ITSP's don't even support Blind Transfers as they are can be a big security headache.

See if you can get the transfer scenarios I linked to working. You can then remove one of the dotnet console apps and use a softphone instead and build from there.

**Comment by sduzcay** [comment]
ok, We will try with Bria and get back to you with the Wireshark logs if we can't make it work. Thanks a lot!

**Comment by sipsorcery** [comment]
I made some screenshot videos running the test attended transfers but didn't polish them up. They may help you as they are so I've uploaded them to [here](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/AttendedTransferScenario/DemoVideos). There's an obscure little trick to doing Attended Transfers on the Bria UI so I'd recommend watching that one.

**Comment by sduzcay** [comment]
What we want to do is to transfer the incoming call (from 7000@192.168.1.34-**Session A**) to an agent (1200@192.168.1.34) inside.  We used the SIPClientUserAgent class for the agent registered on the softphone (zoiper / microsip).

We first initiate a call to the registered agent, and when the call is successfully initiated(**Session B**), we would like to connect this call to the original caller (with AttendedTransfer)
Connection between Transferee(the incoming call from ITSP-Session A) and Transfer Target(Agent-Session B).

In the first step (session A), the softphone needs to receive a call, but the call is not coming. 

Is this the correct way to do this?

**Comment by sduzcay** [comment]
How can I make a call to an internal softphone, e.g. sip:1200@127.0.0.1? When I make a call to an internal line, the softphone won't ring and we cannot see the call.

![image](https://user-images.githubusercontent.com/20154144/82222748-63c8c680-992a-11ea-832a-7dc251fbf7fe.png)

**Comment by sipsorcery** [comment]
You may not be able to if your ITSP does not support it. ITSP SIP servers will typically be configured to block transfers. Do a WireShark SIP capture on the machine running the softphone. It will reveal what's happening.

**Comment by sduzcay** [comment]
How can I make an empty call to an internal softphone on sipsorcery?
(the softphone connected to sipsorcery)

**Comment by sipsorcery** [comment]
I'm sorry but I can't really get what you're asking. Could you take a look at https://tools.ietf.org/html/rfc5589#section-7.3 and then describe your scenario in terms of the `Transferor`, `Transferee` and `Target`?

Which one is your ITSP and which one is the sipsorcery softphone?

**Comment by sduzcay** [comment]
No ITSP. I want to connect a softphone to Sipsorcery, and make a call to this softphone (e.g. sip: 1200@127.0.0.1). I want to see the softphone ringing.

**Comment by sduzcay** [comment]
We solved the calling problem. We'll test the attended transfer. Thanks a lot!

**Comment by sduzcay** [comment]
I've sent the Wireshark logs to your email. 
Thanks a lot for taking the time and helping us!

**Comment by sipsorcery** [comment]
I've had a look at your WireShark traces and I'd advise you to try and find an alternative approach what you are attempting is going to take a lot of effort to even get working and even if you do will then be extremely fragile.

The big problem you have is you are requesting your ITSP out on the Internet to place a new call to a private IP address on your network:

````
REFER sip:0xxxx@213.xx.xx.xx:5065 SIP/2.0
....
Refer-To: <sip:xxx@192.168.1.34:5060;gr=yyyy?Replaces=aaa%3Bto-tag%3D802abc513b98ea11995ee2e1ef609ff9%3Bfrom-tag%3DDDYGCCIOIE>
````

How will the ITSP be able to reach `192.168.1.34`? That's a private network address.

So you could set off down the route of setting up a STUN server and getting your SIP agents to use public IP addresses in their `Contact` header. But then you have the hassle of making sure that you can still communicate internally on the private IP addresses and only use the public IP address for external communications.

It's nasty and that's even before getting to the audio path which involves more private IP addresses in the Session Descriptions.

This issue is a major design flaw in SIP and their are endless additional SIP specifications to overcome none of which properly do.

So what are your options if you do still want to proceed?

 - You could look into using IPv6. If your ITSP and the machines with your softphones all had publicly accessible IPv6 addresses it could work.

 - The common solution for this sort of case is to place a PBX (such as Asterisk, FreeSWITCH etc) on your internal network. It gets used to place and receive calls with your ITSP and then any transfers are done via it. The PBX will be able to do transfers amongst SIP user agents on your private network since it is on the same network.

 - Something else I can't think of.

**Comment by sduzcay** [comment]
Can we bridge the calls together as follows?

192.xx.xx.xx --> 213.xx.xx.xx

**Comment by sduzcay** [comment]
how can we merge these 2 calls?

**Comment by sipsorcery** [comment]
Bridging normally means something different to transferring and I'm still not sure what you're trying to do.

You would be better off trying to get your scenario working with a full softphone (Bria, Zoiper, MicroSIP etc) and once you're happy with that then try and do it programatically.

**Comment by sduzcay** [comment]
We want to transfer the call from the outside line to an internal ext. A call center project.

**Comment by sipsorcery** [comment]
This discussion is going around in circles. Your main issue at the moment is getting a better  understanding of SIP and whether your call scenario can be accomplished with it.

If/when you have the answer to that then you'll be ready to attempt it programatically. At that point feel free to come back with implementation questions regarding this library. In the meantime I'm closing this issue,
