### ISSUE TITLE
How to capture the microphone audio on Linux

### ISSUE THREAD

**Issue by riccardobrue** [sipsorcery/sipsorcery#226]
Hi, I would like to use this library to send microphone input audio through webrtc on a Debian system. Something like capturing from "hw:0" (alsa) input device. Can someone explain how can I create a media source track to add to my RTC peer connection? I am not finding any examples about this.

**Comment by sipsorcery** [comment]
You're right there are no examples on how to deal with audio IO on linux with .net core. It's been requested, see #196, but as of yet I haven't found an obvious way. If you are able to do so please share the code and with it I should be able to use it in an example for this library.

As far as integrating with different capture and rendering devices the approach will be to create a new class that inherits from `RTPSession` for VoIP or `RTCPeerConnection` for WebRTC. The new class needs to wire up sending/receiving RTP packets with capturing/rendering to the system device(s). An example is [NAudioRTPSession](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/GetStartedNetFramework/NAudioRtpSession.cs). But as mentioned if you can share the code to use audio devices on Linux I can write an example of this class.

**Comment by sipsorcery** [comment]
#266 works with PortAudio on my Ubuntu 20.04 machine.

[PortAudio Example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/GetStartedPortAudio).

**Comment by sipsorcery** [comment]
Feel free to re-open if there's any further feedback.
