### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by BronwenZ** [sipsorcery/sipsorcery#229]
Hey,
I'm having a few memory issues when creating lots of calls.
The first one I've found is in the SIPUserAgent -> Call .  Herer the ClientCallAnswered/Fail subscriptions are left attached so unable to dispose of the agent properly. 

I did a local test changing it to the following which fixed those particular ones but I think there's a few other objects hanging around.

````
public async Task<bool> Call(SIPCallDescriptor callDescriptor, IMediaSession mediaSession)
        {
            TaskCompletionSource<bool> callResult = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);

            SIPCallResponseDelegate clientCallAnsweredHandler = null;
            SIPCallFailedDelegate clientCallFailedHandler = null;
            
            clientCallAnsweredHandler = (uac, resp)  =>
            {
                callResult.TrySetResult(true);
                ClientCallAnswered -= clientCallAnsweredHandler;
            };

            clientCallFailedHandler = (uac, errorMessage, result) =>
            {
                callResult.TrySetResult(false);
                ClientCallFailed -= clientCallFailedHandler;
            };

            ClientCallAnswered += clientCallAnsweredHandler;
            ClientCallFailed += clientCallFailedHandler;

            await InitiateCallAsync(callDescriptor, mediaSession).ConfigureAwait(false);
            return callResult.Task.Result;
        }
````

**Comment by sipsorcery** [comment]
I don't think the event logic in the `SIPUserAgent.Call` method are causing the leak. Are you assigning any other event handlers to the `SIPUserAgent` events? Particularly any that could be assigning a static delegate?

The lambda methods in the `SIPUserAgent.Call` method (and elsewhere) in the same class should all be creating weak references which do not stop the instance being [garbage collected](https://stackoverflow.com/questions/298261/do-event-handlers-stop-garbage-collection-from-occurring?noredirect=1&lq=1).

I do load testing with the [sipcmdline](https://github.com/sipsorcery/sipsorcery/tree/master/examples/sipcmdline) example program. The Visual Studio profiler after 1000 calls looks like:

![sipcmdline-profile](https://user-images.githubusercontent.com/197660/83398951-426edc80-a3f8-11ea-927b-2e8ec23f8b29.png)

To emulate this you need to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and install [SIPp](https://github.com/SIPp/sipp) using `sudo apt install sip-tester`.

For `SIPp` to run to run the User Agent Server scenario use:

`sipp -sn uas`

Then to run a load test with the sipsorcery library using the `sipcmdline` utility use a debug command line of:

`-d 127.0.0.1 -c 1000 -x 5 -s uac -b true`

which if run at a Console command line translates to:

`examples\sipcmdline>dotnet run -- -d 127.0.0.1 -c 1000 -x 5 -s uac -b true`

In the screenshot below the top pane is `SIPp` and the bottom `sipcmdline`:

![sipcmdline](https://user-images.githubusercontent.com/197660/83399713-94643200-a3f9-11ea-8777-de9ff8c1d793.png)

**Comment by sipsorcery** [comment]
Feel free to re-open if any further info is available.
