### ISSUE TITLE
Softphone from GitHub-example doesn't transmit a voice.

### ISSUE THREAD

**Issue by RomanPlekhanov** [sipsorcery/sipsorcery#230]
Hi!
I downloaded the example from Github. Launched a softphone. After answering the call, there is no voice exchange. The phone is silent. Although using microsip, voice is transmitted. This indicates that the network, server, and audio devices are working accurately.

**Comment by sipsorcery** [comment]
Can you try the same call with the [Getting Started](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/GetStarted) console application and attach the console log messages. You'll need to edit the `DESTINATION` constant at the top to set your call destination.

**Comment by RomanPlekhanov** [comment]
For authorization, I changed the code so (like softphone example):

![image](https://user-images.githubusercontent.com/31315091/83513615-c8635400-a4da-11ea-8fe7-93e80f35be2d.png)
[CallLog.txt](https://github.com/sipsorcery/sipsorcery/files/4716731/CallLog.txt)
I changed actual destination number in logfile :)

**Comment by sipsorcery** [comment]
Thanks for getting the log.

As well as the lack of audio issue you reported there's also an issue with the SIP signalling and the ACK request not getting through to the FreePBX server.

The root cause for both issues looks to be networking related. Observations:

 - Initial INVITE request is from 10.10.30.84 to 10.10.11.22.
 - On the FreePBX answer response the contact and SDP address is 172.74.13.110 (different from the original 10.10.11.22).
 - The ACK request sent to 172.74.13.110 does not get accepted and FreePBX continues to retransmit the response.

My guess is there is a NAT or ALG somewhere on the SIP path that's mangling the FreePBX responses and swapping 10.10.11.22 to 172.74.13.110.

What's your network set up? Is the FreePBX server on your local network?

**Comment by RomanPlekhanov** [comment]
Yes, my local network has FreePBX server with IP 10.10.11.22. I've attached server's logfile. Maybe it help. About network settings I'll wrote some later.
[FreePBX.log](https://github.com/sipsorcery/sipsorcery/files/4717161/FreePBX.log)

**Comment by sipsorcery** [comment]
With the `Getting Started` example you can try confining the SIP and RTP sockets to a single IP address and see if that helps. Change the code to use the lines below.

````
IPAddress localAddress = IPAddress.Parse("192.168.0.105");

var sipTransport = new SIPTransport();
var udpChannel = new SIPUDPChannel(localAddress, 0);
sipTransport.AddSIPChannel(udpChannel);

EnableTraceLogs(sipTransport);

var userAgent = new SIPUserAgent(sipTransport, null);
var rtpSession = new RtpAVSession(new AudioOptions { AudioSource = AudioSourcesEnum.CaptureDevice}, null, localAddress);
````

If that doesn't help try changing the IP address on the first line to your alternative `10.10.11.22`.

**Comment by RomanPlekhanov** [comment]
If I use IP "192.168.0.105" then retrieve error: SocketException SIPUDPChannel EndSendTo (10051). "An attempt was made to perform an operation on a socket with the network disconnected."
If I use IP "10.10.11.22" then retrieve socket error "AddressNotAvailable".

I've discard NAT settings but it not help.
About network:
- 172.74.13.110 - gateway.
- 10.10.11.ХХ - internal network.
- 10.10.30.XX - VLAN for VPN clients.

Maybe I need a STUN-server?

**Comment by sipsorcery** [comment]
Sorry the IP addresses you need to try are the ones on the interfaces on the machine you are running the `Getting Started` example code.

I read one of them from your log incorrectly. Also try `10.10.30.84`.

The siporcery logic asks the OS to give it the interface to use to send to an external IP address. In your case the OS has said use `192.168.0.105` to get to the FreePBX server at `176.74.13.110` but then `192.168.0.105` probably can't route to `10.10.11.22`. It all seems a bit messed up. Is your FreePBX server meant to be switching IP addresses? Or should you always call it using the  `176.74.13.110` and not the `10.10.11.22` address.

If MicroSIP does work for the exact same call I'd be interested to see the log from it to see what local IP address it picks.

**Comment by RomanPlekhanov** [comment]
Thanks for the help! We reconfiged ouer network and now the SIP client is working fine. :)
