### ISSUE TITLE
TLS with certificate on server side

### ISSUE THREAD

**Issue by qwetboy10** [sipsorcery/sipsorcery#232]
Is it possible to connect to a server over TLS without having a certificate on the client-side? Shouldn't you be able to initiate a connection using the server's certificate only? Sorry if I'm misunderstanding something, but I couldn't find a way to do this in the documentation.

**Comment by sipsorcery** [comment]
You are right you shouldn't need to supply a certificate if you only want to use the TLS channel for client connections. I recall my thinking at the time was more geared towards server applications and a TLS channel would always need a certificate to be able to accept client connections.

It shouldn't be too hard for me to adjust the channel so it can work as client only.

**Comment by qwetboy10** [comment]
Thanks! Tell me if there is anything I could help with

**Comment by sipsorcery** [comment]
This is fixed on `master` now. Turns out I had coded client only connections at some point and all that was needed was to remove the null certificate check.
