### ISSUE TITLE
Allow SIPConstants overriding

### ISSUE THREAD

**Issue by sr-petrov** [sipsorcery/sipsorcery#235]
It would be helpful to be able to override default sip constants like username, password, fromuri etc.
It is especially important for processing transfer requests (REFER) when you can't pass your own SIPCallDescriptor with required credentials.

**Comment by sipsorcery** [comment]
Can you provide some more description or perhaps pseudo-code of how this would work?

With request like REFER they are in-dialog which means most of the core header need to be the same as the ones that created the dialog. It means there's not a lot of latitude to change things like the `From`, `To` etc. headers.

**Comment by sr-petrov** [comment]
Yeah, I agree, credentials and other parameters like `From` for REFER requests could be "borrowed" from current `m_callDescriptor` (instead of getting them from default constants). I can make a pull request, if you happy with that.

Another related issue I found (probably I need to open another issue for that?) is that method `Call` in the `SIPUserAgent` which takes `username` and `password` as parameters, doesn't really work ... I get _Response 403 Forbidden_ back even when I send correct `username` and `password`, only when parameter `From` in the SIPCallDescriptor is populated correctly (not default `thisis@anonymous.invalid`) it works. So to me it make more sense either to add a parameter `from`, or remove parameters `username` and `password` to make it clear that for authenticated call another method (with descriptor) should be used.

**Comment by sipsorcery** [comment]
A PR would be useful to help clarify the use case.

For the second authentication issue you've raised does that occur on the an INVITE request or on the REFER sent as part of a transfer?

**Comment by sipsorcery** [comment]
Feel free to re-open if there is more information.
