### ISSUE TITLE
Simultaneous outbound calls

### ISSUE THREAD

**Issue by arashkey** [sipsorcery/sipsorcery#237]
Hello
I am just wondering how to create simultaneous outbound calls. I didn't find any appropriate examples and sipsorcery seems to be not thread safe.
I would be thankfull if you help me 
with the best regards

**Comment by sipsorcery** [comment]
The easiest way is to create an instance of the `SIPUserAgent` class for each outbound call. The [SIPCallServer](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/SIPCallServer/Program.cs) example can handle multiple simultaneous inbound and outbound calls.

> sipsorcery seems to be not thread safe

Based on?

**Comment by sirajmansour** [comment]
Right, so i've been testing this, a sipuseragent & transport per thread. everything works beatiful until calling useragent.Hangup() it doesn't seem to work, as the calls stay open on the SIP server.

**Comment by sipsorcery** [comment]
Various different things can cause hangup requests not to succeed:

 - If the Contact address in the INVITE request or response contained a private or unreachable address then the BYE request will never reach the remote party,
 - If there's a NAT on the path it can cause timeout and block the connection,
 - etc. etc.

It's a big leap of faith to attribute a SIP signalling issue to thread concurrency.

By all means please provide a description of any issue you are facing plus logs or sample code to replicate it.

**Comment by arashkey** [comment]
Is there any sample for calling outbound calls? It could be appreciated if you provide me a sample for simultaneous outbound calls. 
I tried to use SipCallServer sample project. I defined an array of numbers to use them each time user press the "C" key.
private static List NUMBERS = new List { ... , ... ... }
Then
`                    if (keyProps.KeyChar == 'c')
                    {
                        // Place an outgoing call.
                        var ua = new SIPUserAgent(_sipTransport, null);
                        ua.ClientCallTrying += (uac, resp) => Log.LogInformation($"{uac.CallDescriptor.To} Trying: {resp.StatusCode} {resp.ReasonPhrase}.");
                        ua.ClientCallRinging += (uac, resp) => Log.LogInformation($"{uac.CallDescriptor.To} Ringing: {resp.StatusCode} {resp.ReasonPhrase}.");
                        ua.ClientCallFailed += (uac, err, resp) => Log.LogWarning($"{uac.CallDescriptor.To} Failed: {err}, Status code: {resp?.StatusCode}");
                        ua.ClientCallAnswered += (uac, resp) => Log.LogInformation($"{uac.CallDescriptor.To} Answered: {resp.StatusCode} {resp.ReasonPhrase}.");
                        ua.OnDtmfTone += (key, duration) => OnDtmfTone(ua, key, duration);
                        ua.OnRtpEvent += (evt, hdr) => Log.LogDebug($"rtp event {evt.EventID}, duration {evt.Duration}, end of event {evt.EndOfEvent}, timestamp {hdr.Timestamp}, marker {hdr.MarkerBit}.");
                        ua.OnCallHungup += OnHangup;
                        var rtpSession = CreateRtpSession(ua, null);
                        var callResult = await ua.Call(NUMBERS[COUNTER], null, null, rtpSession);
                        COUNTER++;
                        if (callResult)
                        {
                            await rtpSession.Start();
                            _calls.TryAdd(ua.Dialogue.CallId, ua);
                        }
                    }`
I am not sure this line is ok to use due to AWAIT phrase.
`var callResult = await ua.Call(NUMBERS[COUNTER], null, null, rtpSession);`
instead, using ua.InitiateCallAsync without AWAIT is right??? a working code with at least 2 simultaneous calls will be very handy.

**Comment by arashkey** [comment]
Address already in use exception attempting to bind UDP socket, attempt 0.
Unhandled exception. System.ApplicationException: Unable to bind UDP socket using end point 0.0.0.0:5060.
   at SIPSorcery.Sys.NetServices.CreateBoundUdpSocket(Int32 port, IPAddress bindAddress, Boolean requireEvenPort, Boolean useDualMode)

**Comment by sipsorcery** [comment]
> Address already in use exception attempting to bind UDP socket, attempt 0.
Unhandled exception. System.ApplicationException: Unable to bind UDP socket using end point 0.0.0.0:5060.

Another process is already listening on port 5060.

Placing simultaneous calls using the same `SIPTransport` does not require any special magic:

````
for (int i = 0; i < 2; i++)
{
	_ = Task.Run(async () =>
	{
		var userAgent = new SIPUserAgent(sipTransport, null);
		var rtpSession = new WindowsAudioRtpSession();
		await userAgent.Call(DESTINATION, null, null, rtpSession);
	});

	await Task.Delay(1000);
}         
````

**Comment by sirajmansour** [comment]
@sipsorcery Ohh of course, i was not giving a definite judgement here but rather my problem led me here.

I've written code as simple as this :

``` 
        private Dictionary<string, Task> activeDiallers = new Dictionary<string, Task>();

        public Form1()
        {
            InitializeComponent();
            AddLogger();
        }

        private static void AddLogger()
        {
            var loggerFactory = new Microsoft.Extensions.Logging.LoggerFactory();
            loggerFactory.AddProvider(new DebugLoggerProvider());
            SIPSorcery.Sys.Log.LoggerFactory = loggerFactory;
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            await LaunchDialWatch("9999",TimeSpan.FromSeconds(39));
        }

        private Task LaunchDialWatch(string number, TimeSpan duration)
        {
            var runner = Task.Factory.StartNew(async () =>
            {
                var sipTransport = new SIPTransport();
                var client = new SIPUserAgent(sipTransport, null);
                var session = new RtpAudioSession(new AudioSourceOptions() { AudioSource = AudioSourcesEnum.None }, new List<SIPSorcery.Net.SDPMediaFormatsEnum> { SDPMediaFormatsEnum.PCMU, SDPMediaFormatsEnum.PCMA, SDPMediaFormatsEnum.G722 });

                ManualResetEvent resetEvent = new ManualResetEvent(false);
                CancellationTokenSource cts = new CancellationTokenSource();
                var token = cts.Token;

                client.ClientCallAnswered += (agent, resp) =>
                {
                    resetEvent.Set();
                    textBox1.Invoke(new Action(() => { textBox1.AppendText($"answered {number}" + Environment.NewLine); }));
                };

                client.OnCallHungup += (sd) =>
                {
                    cts.Cancel();
                    textBox1.Invoke(new Action(() => { textBox1.AppendText($"hungup {number}" + Environment.NewLine); }));
                };

                client.ClientCallTrying += (agent, resp) =>
                {
                    textBox1.Invoke(new Action(() => { textBox1.AppendText($"trying {number}" + Environment.NewLine); }));
                };

                bool success = await client.Call(number + "@MY.SER.VER.IP:PORT", "USER", "PASS", session).ConfigureAwait(true);

                if (success)
                {
                    resetEvent.WaitOne(TimeSpan.FromSeconds(30)); //Wait before call answered
                    Stopwatch sw = new Stopwatch();
                    sw.Start();

                    while (!token.IsCancellationRequested)
                    {
                        if (!client.IsCallActive)
                        {
                            break;
                        }

                        if (sw.Elapsed >= duration)
                        {
                            client.Dialogue.Hangup(sipTransport, null);  //Tried client.Hangup(); , didn't work also
                            sipTransport.Shutdown();
                            textBox1.Invoke(new Action(() => { textBox1.AppendText($"hanging up on {number} after {sw.Elapsed.TotalSeconds} seconds" + Environment.NewLine); }));
                            break;
                        }
                    }

                }
                else
                {
                    textBox1.Invoke(new Action(() => { textBox1.AppendText($"failed {number}" + Environment.NewLine); }));
                }

                if (client.IsCallActive)
                {
                    client.Hangup();
                    sipTransport.Shutdown();
                }

                
                textBox1.Invoke(new Action(() => { textBox1.AppendText($"finishing up {number}" + Environment.NewLine); }));
            }, TaskCreationOptions.LongRunning).ContinueWith(t => activeDiallers.Remove(number));

            activeDiallers.Add(number, runner);

            return runner;
        }
```

**Comment by arashkey** [comment]
Dear Aaron,
I am not a threading expert but using "await" will hold all process till next loop, right?. By term of "simultaneous", i mean real-time synchronous calls.

**Comment by arashkey** [comment]
Thanks @sirajmansour for your sample. I will give it a try and let you know the result. By the way, i have problem using "await", looking for synchronous calling process.

**Comment by sipsorcery** [comment]
@sirajmansour the likely reason your hangup call is failing is because you are shutting down the `SIPTranpsort` immediately after calling hangup. You need to give the transport time a chance to send the `BYE` request.

````
//client.Dialogue.Hangup(sipTransport, null);  //Tried client.Hangup(); , didn't work also
client.Hangup()
await Task.Delay(1000);
sipTransport.Shutdown();
````
Minor point but you seem to be using a `ManualResetEvent` to add a delay, why not use `await Task.Delay` which is better suited,

It depends on what your app but often it's better to have a single `SIPTransport` instance (singleton) rather than creating a new instance on demand for every call. Both ways will work but if you want to receive incoming call requests you will need to listen on a static port and that is best achieved with a long-lived `SIPTransport` instance.

**Comment by sipsorcery** [comment]
@arashkey 

> I am not a threading expert but using "await" will hold all process till next loop, right?

The `await` call will not "hold the process". It will typically create a callback on the current thread that will run when the awaited method call completes (it may also do nothing if the awaited operation returns quickly).

I'd highly recommend getting a good high level understanding of Asynchronous Programming with `async` and `await` if you're going to be more than the simple C# apps. If you don't understand how it works at a high level you will run the risk of deadlocking your application.

It wasn't that long ago that I had to go through the same [learning exercise](https://github.com/sipsorcery/sipsorcery/issues/164) and I'm very glad I did.

**Comment by sirajmansour** [comment]
@sipsorcery  Ohh works like a charm now, thanks 👍  probably worth documenting.

> Minor point but you seem to be using a ManualResetEvent to add a delay, why not use await Task.Delay which is better suited

I use it to wait until CallAnswered is fired or until it hits timeout rather than just a delay. I'll probably move to this [library](https://github.com/StephenCleary/AsyncEx/wiki/AsyncManualResetEvent)

> It depends on what your app but often it's better to have a single SIPTransport instance (singleton) rather than creating a new instance on demand for every call. Both ways will work but if you want to receive incoming call requests you will need to listen on a static port and that is best achieved with a long-lived SIPTransport instance.

I don't assume this applies to multiple simultaneous calls running on background threads ?

**Comment by sipsorcery** [comment]
> I don't assume this applies to multiple simultaneous calls running on background threads ?

Yes it does. The `SIPTransport` class is capable of running server applications with thousands of concurrent transactions. A client application with a few concurrent calls will be easily handled by a single `SIPTransport` instance.
