### ISSUE TITLE
Replace DnsClient.Net to Net-mDNS (Cross-Platform Solution)

### ISSUE THREAD

**Issue by rafcsoares** [sipsorcery/sipsorcery#238]
Hello again @sipsorcery , i saw in your last commit a referente to DnsClient.net

This DnsClient solutions only works in Windows and Linux because it uses "p/invokes" to call native libraries to handle the task.

My sugestion is to replace to Net-mDNS (https://github.com/richardschneider/net-mdns)

This solution can handle mDNS discovery and DNS discovery. You can use my class below to perform a DNS and mDNS discover in same function

```
using Makaretu.Dns;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace SharpMdns
{
    public static class DnsIpAddressUtils
    {
        /// <summary>
        /// This function can parse:
        /// - Local Addresses (mDNS) ended with ".local" like "d324e0ef-e3e9-4489-bc82-b3734b9238f3.local"
        /// - DNS Addresses like "www.google.com"
        /// - Default Ipv6 or Ipv4 addresses like 127.0.0.1
        /// </summary>
        public static async Task<IPAddress> ParseAsync(string unknownAddress)
        {
            IPAddress address = null;
            if (string.IsNullOrEmpty(unknownAddress))
            {
                return null;
            }
            //Parse mDNS
            else if (unknownAddress.EndsWith(".local"))
            {
                var mdns = new MulticastService();
                try
                {
                    // Ask for the host IP addresses.
                    mdns.Start();
                    mdns.SendQuery(unknownAddress);

                    var ended = false;
                    mdns.AnswerReceived += (s, e) =>
                    {
                        ended = true;
                        // Is this an answer to host addresses?
                        var addresses = e.Message.Answers.OfType<AddressRecord>();
                        foreach (var addressRecord in addresses)
                        {
                            address = addressRecord.Address;
                            break;
                        }
                    };

                    //Wait while end
                    while (!ended)
                    {
                        await Task.Delay(25);
                    }
                }
                catch { }
                finally
                {
                    mdns.Dispose();
                }
            }
            //Try parse as Ipv4 or Ipv6 address
            else if (!IPAddress.TryParse(unknownAddress, out address))
            {
                //Failed to parse as Ipv4 or Ipv6 format so we can try parse as DNS
                var dns = new DnsClient();
                try
                {

                    var addresses = await dns.ResolveAsync(unknownAddress);
                    foreach (var addressRecord in addresses)
                    {
                        address = addressRecord;
                        break;
                    }
                }
                catch { }
                finally
                {
                    dns.Dispose();
                }
            }

            return address;
        }
    }
}
```

**Comment by rafcsoares** [comment]
Here my extension to AddIceCandidate with mDNS discover support

public static async Task<RTCIceCandidate> AddIceCandidate(this RTCPeerConnection peerConnection, RTCIceCandidateInit candidateInit)
        {
            RTCIceCandidate candidate = new RTCIceCandidate(candidateInit);

            //Try Convert to MDNS Address to IPV4 or IPV6 Address
            var resultAddress = await SharpMdns.DnsIpAddressUtils.ParseAsync(candidate.address);
            if (resultAddress != null)
            {
                if (resultAddress.AddressFamily == AddressFamily.InterNetwork)
                    resultAddress = resultAddress.MapToIPv6();
                var newAddress = resultAddress.ToString();
                if (newAddress != candidate.address)
                {
                    Debug.Log($"Candidate address converted from {candidate.address} to {newAddress} (mDNS Discovery)");
                    candidate.address = newAddress;
                }
            }

            if (peerConnection.IceSession.Component == candidate.component)
            {
                peerConnection.IceSession.AddRemoteCandidate(candidate);
            }
            else
            {
                Debug.Log($"Remote ICE candidate not added as no available ICE session for component {candidate.component}.");
            }

            return candidate;
        }
```

**Comment by sipsorcery** [comment]
Thx for taking a look at this.

[DnsClient.NET](https://github.com/MichaCo/DnsClient.NET) is passing the CI tests that run on Windows, Ubuntu and MacOS. I take it you need to support a Unity app? On what OS? Could you check if the [STUNDnsUnitTests](https://github.com/sipsorcery/sipsorcery/blob/master/test/net/STUN/STUNDnsUnitTest.cs) can run on it?

The reason I'm keen to stick with DnsClient.NET is it has a nice, simple approach for `SRV` -> `AAAA` or `A` lookups. These lookups are required for SIP and for STUN & TURN. The `Makaretu` library doesn't have that functionality which means the all the extra plumbing that's currently in [SIPDNSManager](https://github.com/sipsorcery/sipsorcery/blob/master/src/app/SIPDNS/SIPDNSManager.cs) needs to hang around and be updated to cope with `_stun` and `_turn` SRV lookups. In your example code above you are only doing a `A` or `AAAA` lookup on an ICE server hostname which is missing the `SRV` step.

It is worth considering adding the `Makaretu` dependency for the `mdns` lookups. My initial thinking, as documented in the code, was to avoid an additional dependency but that's not a strong inclination.

**Comment by sipsorcery** [comment]
#253 and will keep an eye out for mdns solutions.

**Comment by rafcsoares** [comment]
@sipsorcery sorry, got really busy with some another complex tasks.

I will test this new push request soon as possible, and try to figure out a good and simple mDNS solution for netstandard.

thanks in advance for this improvement
