### ISSUE TITLE
Use with MS teams/Skype for Business

### ISSUE THREAD

**Issue by ilogixxDE** [sipsorcery/sipsorcery#246]
Is it possible to connect to MS teams/Skype for Business to make and receive calls? We tried this with other sdks without success. Do you have any idea if and how this can be possible with sipsorcery?
Thank you

**Comment by sipsorcery** [comment]
I don't know about Skype for Business (isn't it being shut down soon?) but it is possible to place and receive calls with Teams. This library won't help a lot though as there are no SIP or WebRTC avenues to access Teams. Instead you need to write a Bot using the [Microsoft Graph Communications API](https://github.com/microsoftgraph/microsoft-graph-comms-samples).

I'd recommend starting by getting your Bot to receive a call based on the [PolicyRecordingBot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot) sample. Get ready for lots of frustration. The API documentation is skin deep and getting answers on the github repo is a major challenge (if you search the issues for my user you'll find some relevant posts).

And no unfortunately I can't publish the code at this stage as I the work I did with Teams was part of a paid project under NDA. I could maybe help with answers to questions though. If you do end up posting related questions on the Microsoft Graph forum feel free to ping me in the question.
