### ISSUE TITLE
Early Media Playback

### ISSUE THREAD

**Issue by mohammadb77** [sipsorcery/sipsorcery#247]
Hi,

I have successfully used function "OnRTPPacketRecieved" to capture media (payload) of a call. but have problems with recording RBT.
by any chance, is there any way to help me detect and capture early media (RBT)?

**Comment by sipsorcery** [comment]
What does RBT stand for?

**Comment by mohammadb77** [comment]
Ring Back Tone. 
actually, ringing part of a call, is inside the RTP payload. but it's refered to as early media. when I capture a call, I can only listen from when the callee answers the phone. but I need to record the ringing part as well.

**Comment by sipsorcery** [comment]
Ok got it now, just another name for early media.

I never got around to wiring up early media in the `SIPUserAgent` class. I'll add it to the the todo list and track with this issue.

**Comment by mohammadb77** [comment]
That's right. 
Thank you. I'll look forward to.

**Comment by sipsorcery** [comment]
Should now be working in the `SIPUserAgent` class on `master`.

**Comment by mohammadb77** [comment]
Thanks for your effort. 
Correct me if i am wrong. By using your changes, i will be able to capture Early Media or Ring Back Tone, right? Should i search for "OnRtpPacketReceived"-liked event to capture and convert the RBT packet into a usable file or not?

**Comment by sipsorcery** [comment]
Yes that's correct. The [RecordIncomingCall](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/RecordIncomingCall/Program.cs) example should also catch any early media.

**Comment by mohammadb77** [comment]
ok. just another quick question. What about outgoing calls?

**Comment by sipsorcery** [comment]
Yes early media will get recorded for an outgoing call.

**Comment by mohammadb77** [comment]
could you please give a sample with outgoing call that captures early media? I can't get around it my self.

**Comment by sipsorcery** [comment]
[RecordCall](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/RecordCall/Program.cs).

It should just work. If it doesn't please post up logs and ideally a WireShark capture of the call.

**Comment by mohammadb77** [comment]
![image](https://user-images.githubusercontent.com/68064809/87664207-1c1fb900-c77a-11ea-8684-6e1cf7f21ad6.png)
Thanks. I'll check. 
btw, the references in our project is shown in the attached image. is that the right version? isn't there any update?

**Comment by sipsorcery** [comment]
Yes that's the latest available nuget package.

**Comment by mohammadb77** [comment]
Thank you. 
eagerly looking forward to the new nuget package version. it would be awesome if you let me know when the new package was out. 
again I appreciate what ever you done. thanks man.

**Comment by mohammadb77** [comment]
Dear Aaron,
Any change for new nugget package?

**Comment by sipsorcery** [comment]
Should be ready later today.

**Comment by mohammadb77** [comment]
Thank you in advance for your effort.

**Comment by mohammadb77** [comment]
Dear Aaron,
I have just check your new nugget, version 4.0.50-pre. I really appreciate it.
Correct me if i am wrong, To capture Early media, we have to use RtpAVSession instead of RtpAudioSession. In my project, i am using RtpAudioSession and still no capturing happened for Early Media, only RTP was recorded.

On the other hand, for capturing Early Media we need a reference to SipSorceryMedia and RtpAVSession, right? just like your sample project of [RecordCall](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/RecordCall/Program.cs)
![image](https://user-images.githubusercontent.com/68064809/88295628-ec8d2580-cd12-11ea-8d75-0c9beafe5d24.png)

**Comment by sipsorcery** [comment]
Yes that will work. You could use the example WindowsAudioRtpSession as
well.

I made a small change to the record call example so that it finalises the
mp3 file if the call is cancelled. Maybe that was your problem. My test
call recorded the early media to output.mp3.

**Comment by mohammadb77** [comment]
Thanks for your effort, I really appreciate it.

I was thinking if we could be able to save Early Media (RBT) separately from main RTP payload, Something like "OnEarlyMediaPacketReceived" event which could help to have Early Media payload. Separating RBT from RTP is really helpful.

Regards

**Comment by sipsorcery** [comment]
Catch the `userAgent.ClientCallAnswered` and close your wave file. That will result in the file only containingany early media. If you also want to record the audio once the call is established then create a new wave file at the same time and hook it up to the `rtpSession.OnRtpPacketReceived` event.

**Comment by mohammadb77** [comment]
Dear team,
I am just wondering if the latest version of SipSorcery is compatible with Early Media's capturing stuffs. Using VoIPMediaSession instead of WindowsAudioRtpSession can lead us into successful early media access.

**Comment by sipsorcery** [comment]
Yes early media capture should still work correctly with `VoIPMediaSession`.
