### ISSUE TITLE
SIPRegistrationUserAgent - Cannot reset expiry after creation

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#25]
I'll blame the client for this one :)

Set up registration, successful, but device does not receive calls after < 4 minutes, registration happens every 5 minutes.
So I pass in 180 for the expiry interval.
Behaviour does not change.
On investigation, the OK response from the server is setting the Expiry to 300 again.

However, because I can't reset the expiry externally, I can't reset it to a value that will work.

**Comment by sipsorcery** [comment]
When a SIP server responds with an expiry that's higher than that requested by the client it means that's the minimum value it supports. Of course the server can't stop the client using a lower value but some SIP Registrars will block clients that register too frequently.

Apart from the above I have added a new `SetExpiry` method to the registration agent. It was a very minor addition and will potentially save having to stop an existing agent and re-create it with a different expiry.
