### ISSUE TITLE
Multiple execution of program using sipsorcery

### ISSUE THREAD

**Issue by w0rt4** [sipsorcery/sipsorcery#250]
Hi,
I'm sorry if that question was asked earlier, but I didn't see anything like it. I have a console program that uses a SipSorcey to call the list of numbers passed as an execution parameter. All these calls will be cancelled by the client hosts. I have a problem with repeated execution of this program. I use the single user and sip port for this.On first run there is no problem and the program will call each number from passed list, but when I try to run this program again immediately with another list of numbers, I get an exception when trying to create SIPUDPChannel : "Only one use of each socket address (protocol/network address/port) is normally allowed".  Is there a way to get an existing udp channel in a second execution or another approach in this situation.

Thanks in advance,
Kacper

**Comment by sipsorcery** [comment]
First thing is to double check your application is closing the `SIPTransport` when it exits. To do that make sure ` sipTransport.Shutdown()` is called. If it's not then your SIP channel sockets get killed without a call to `Socket.Close` and you have to wait for the Operating System to time out the socket before the same `address:port` combination can be used again.

If that doesn't solve the problem then as it sounds like your app is initiating calls without needing to receive then perhaps you don't need to use a statis UDP port and can get the OS to assign a new one each time. To do that you should omit any calls to `sipTransport.AddSIPChannel(sipChannel);`. By not adding a SIP channel to your transport you tell it to create a new one on demand with an OS assigned dynamic port number.

**Comment by w0rt4** [comment]
I'm sorry I'm writing off so late. I was on vacation. Your advice solved my problem. Thank you very much for your help.
