### ISSUE TITLE
Transaction timeout and retransmit count

### ISSUE THREAD

**Issue by Educsys** [sipsorcery/sipsorcery#260]
Good day, can I somehow affect the number of request retransmission attempts and the response timeout in the SIPNonInviteTransaction and SIPClientUserAgent classes

**Comment by sipsorcery** [comment]
You can't do it from your application. If you build from source you can adjust the [timing parameters](https://github.com/sipsorcery/sipsorcery/blob/99f3dbfebd2a8d968554369180f274e651a0bee8/src/core/SIP/SIPConstants.cs#L103) .

The `SIPTiming` constants should probably be adjustable but I've erred on the side of caution and left them as constants. If they are set with incorrect values then it's possible that all SIP transactions will fail.

**Comment by Educsys** [comment]
Is it possible to change timings if they are constants?
Can I cancel a transaction of the SIPNonInviteTransaction class forcibly?

**Comment by sipsorcery** [comment]
> Is it possible to adjust timings if they are constants?

You currently can't (unless you edit the source code and remove the constant qualifier yourself). I'll change this for the next release.

> Can I cancel a transaction of the SIPNonInviteTransaction class forcibly?

Yes set the `IsDeliveryPending` property to false.

**Comment by Educsys** [comment]
Thanks for the help. DeliveryPending worked properly
