### ISSUE TITLE
RTSPSession session missing

### ISSUE THREAD

**Issue by lnksnk** [sipsorcery/sipsorcery#274]
When I compile code from master from github I get RTSPSession missing. I also dont see it in same package as RTSPServer

**Comment by sipsorcery** [comment]
Are you sure you've pulled the latest changes? Or do you mean you need `RTSPSession` and it's missing? 

Some of the RTSP classes were removed from the library as they weren't being actively maintained and were never properly finished.

**Comment by lnksnk** [comment]
If its possible I actauly need RTSPSession

**Comment by sipsorcery** [comment]
If you really want it here's the most recent commit I could find that it exists in. But again don't expect it to work out of the box. There are probably better C# projects around to work with RTSP.

`git checkout f4daf813d3ee8e70f94fd7d6967484bcb03acad4`

**Comment by lnksnk** [comment]
Thanks Ill check it out you can close the ticket
