### ISSUE TITLE
Sip register contact header

### ISSUE THREAD

**Issue by NemtsevSergey** [sipsorcery/sipsorcery#279]
Hello, contact header fills with <sip:10.1.21.116:5060>, but should be like: <sip:303@10.1.21.116:5060>.
Is it bug or i miss some?

**Comment by sipsorcery** [comment]
Both are valid `Contact` headers. If you leave it up to the `SIPTransport` layer it will add a `Contact` header with sufficient information for subsequent in-dialog requests to be correctly routed.

You can always set a custom `Contact` header depending on your needs but be careful; if it doesn't match a listening socket on your `SIPTransport` then you won't be able to receive in-dialog requests, such as ACK, BYE, re-INVITE.

**Comment by NemtsevSergey** [comment]
May be it will be cool to add some parameter to add user name in header, because our sip provider say that in common case we must add username.

**Comment by sipsorcery** [comment]
Instead of:

````
var regUserAgent = new SIPRegistrationUserAgent(sipTransport, USERNAME, PASSWORD, DOMAIN, EXPIRY);
````

use:

````
SIPURI aor = SIPURI.ParseSIPURIRelaxed($"{USERNAME}@{DOMAIN}");
SIPURI contact = new SIPURI(USERNAME, IPAddress.Any.ToString(), null);
var regUserAgent = new SIPRegistrationUserAgent(sipTransport, null, aor, USERNAME, PASSWORD, null, DOMAIN, contact, 180, null, null);
````

````
REGISTER sip:sipsorcery.com SIP/2.0
Via: SIP/2.0/UDP 192.168.11.50:51981;branch=z9hG4bK4829767a4f314d269b38bf982cffd6af;rport
To: <sip:softphonesample@sipsorcery.com>
From: <sip:softphonesample@sipsorcery.com>;tag=SFINGORHDP
Call-ID: 4eabb1d4c214407190849d974a81b02a
CSeq: 1 REGISTER
Contact: <sip:softphonesample@192.168.11.50:51981>
Max-Forwards: 70
User-Agent: sipsorcery_v4.0.60.0
Expires: 180
Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, PRACK, REFER, REGISTER, SUBSCRIBE
Content-Length: 0
````

**Comment by NemtsevSergey** [comment]
Thank you. Work great. Provider confirmed that all work just like they waiting.
