### ISSUE TITLE
PutOnHold and mute voice

### ISSUE THREAD

**Issue by NemtsevSergey** [sipsorcery/sipsorcery#283]
Hello, when we call and make command PutOnHold - we can hear voice from caller. May be it is ok in some situation, but when we make parallel call, it is unreal to hear second user, when user on hold continue to speak (not with operator). Is it ok to solve this by modifiing following code like this:

        public void PutOnHold()
        {
            CallStatus = CallStatusEnumFlag.OnHold;
            _mUserAgent.PutOnHold();
            _mUserAgent.MediaSession.SetMediaStreamStatus(SDPMediaTypesEnum.audio, MediaStreamStatusEnum.Inactive);
            // At this point we could stop listening to the remote party's RTP and play something 
            // else and also stop sending our microphone output and play some music.
            StatusMessage?.Invoke(this, "Local party put on hold");
        }

        /// <summary>
        /// Takes the remote call party off hold.
        /// </summary>
        public void TakeOffHold()
        {
            _mUserAgent.MediaSession.SetMediaStreamStatus(SDPMediaTypesEnum.audio, MediaStreamStatusEnum.SendOnly);
            _mUserAgent.TakeOffHold();
            CallStatus = CallStatusEnumFlag.CallAnswered;
            // At this point we should reverse whatever changes we made to the media stream when we
            // put the remote call part on hold.
            StatusMessage?.Invoke(this, "Local party taken off on hold");
        }`

**Comment by sipsorcery** [comment]
> Is it ok to solve this by modifiing following code like this:

You shouldn't need to call `_mUserAgent.MediaSession.SetMediaStreamStatus` explicitly. It should already be called from within the `SIPUserAgent` class when you call ` _mUserAgent.PutOnHold()` or `_mUserAgent.TakeOffHold`.  But if you really want to you can, it shouldn't do any harm.

The bigger question is how you should get the `MediaSession` class that's controlling the audio source to do what you want.

If you look at the Softphone example you'll see two spots where I've made reference to that exact thing. When [putting on hold](https://github.com/sipsorcery/sipsorcery/blob/46c1931606285ebd5dacfd64c38608ea98399f6c/examples/Softphone/Signalling/SIPClient.cs#L279) and [taking off hold](https://github.com/sipsorcery/sipsorcery/blob/46c1931606285ebd5dacfd64c38608ea98399f6c/examples/Softphone/Signalling/SIPClient.cs#L307).

Putting calls on and off hold can be done in different ways, sometimes music on hold will be played, sometimes audio will be cut off etc. In the `SIPSorcery Softphone's` case it sends a re-INVITE request with a media stream status of `sendonly`. it expects the remote party to then stop sending RTP. If the remote party keeps sending RTP then the softphone will play it. It's tricky what to do in this situation. If you're putting a call on hold and then placing a new call you need the RTP socket to stay listening to get the audio from the new call. Once the new call is answered it should be the only audio played but until that happens any RTP from the original call will be.

Does that makes sense? I realise the explanation is a bit convoluted.

**Comment by NemtsevSergey** [comment]
Not, it is ok, explanation is ok, it is make sance. But i do not anderstand how to control call with one instanse of SipClient. I checked that it is real, and if i make call command, it will call, but how can i switch between this two calls and get status of each one in one SipClient? Is there something like call manager? So i decided to create second instanse of SipClient to control second call, and i think it is the reason why i can hear first call voice. But now i can switch between this calls, put on hold, transfer and so on.

**Comment by sipsorcery** [comment]
Is there still something you need help with or has this question been answered?

**Comment by NemtsevSergey** [comment]
This question is answered, but have question about two call and how to control it in one SIPUserAgent

**Comment by sipsorcery** [comment]
> but have question about two call and how to control it in one SIPUserAgent?

The `SIPUserAgent` class is designed to handle a single call at a time. If you want to transfer calls the recommendation is to use multiple `SIPUserAgent` instances.

The [Attended Transfer](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/AttendedTransfer) example demonstrates how to use two separate instances to perform an attended transfer.

To control which audio is currently played on your speaker you may need to add functionality to whichever `IMedaSession` class you are using. If you only case about audio on Windows I'd recommend switching to the [WindowsAudioRtpSession](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/Common/Devices/WindowsAudioRtpSession.cs), it's the simplest. If you have multiple media sessions you can hook and unhook the event handlers to determine which one gets access to the microphone and speakers.

**Comment by NemtsevSergey** [comment]
In my case we use multiple SipClient with its SIPUserAgent. And mute audio by calling SetMediaStreamStatus, thanks, it is solved.

**Comment by sipsorcery** [comment]
Seems all done here.
