### ISSUE TITLE
[WebRTC] How to make a stream in pc's event ontrack like browsers

### ISSUE THREAD

**Issue by CCMeta** [sipsorcery/sipsorcery#284]
`peer_connection.ontrack = function (e) {} ` sth like that.. 
Do i must need FFMPEG or others to decode RTPPacket in event  OnRtpPacketReceived
Sorry i don't know how to handle RTPPacket.Payload.

**Comment by sipsorcery** [comment]
Yes this is where it gets tricky...

What type of stream do you need? Audio or video? And how do you need to capture or play the stream with the application that is using the sipsorcery library (in your case your Xamarin Android app)?

The sipsorcery library can encode and decode G711 audio streams with a browser and without needing `ffmpeg` etc. But the sipsorcery library doesn't know anything about how to interface with microphones or speakers.

**Comment by CCMeta** [comment]
So the normal way to continue is give payloadType and payload byte[] to ffmpeg and a player lib. Is that right?

**Comment by sipsorcery** [comment]
> So the normal way to continue is give payloadType and payload byte[] to ffmpeg and a player lib. Is that right?

Yes.

I have done a little bit of prototyping work to wire ffmpeg up with the [WebRTCTestPatternServer](https://github.com/sipsorcery/sipsorcery/tree/ffmpeg/examples/WebRTCExamples/WebRTCTestPatternServer) (note the `ffmpeg` branch) which might help you.

The [VideoEncoder](https://github.com/sipsorcery/sipsorcery/blob/ffmpeg/src/ffmpeg/VideoEncoder.cs) class uses `ffmpeg` to decode the RTP packets.

I haven't gotten to the stage of attempting to use `ffmpeg` to interface with any devices.

I'd be very interested to hear if you can get `ffmpeg` working on Android in any form.

**Comment by CCMeta** [comment]
Aha this is just my next target. Thanks . When it is work. I'll tell you

**Comment by CCMeta** [comment]
hello come again...
when a use this ice Server got this.  Looks like when I use same IP address and port, Stun Server's port will missing?

but when I change  `"stun:137.220.233.101:3478"` to  `"stuns:137.220.233.101:3478"` , it will works.

```
                var IceServersStun = new RTCIceServer
                {
                    urls = "stun:137.220.233.101:3478",
                };
                var IceServersTurn = new RTCIceServer
                {
                    urls = "turn:137.220.233.101:3478",
                    username = "username1",
                    credential = "key1",
                };
                var presetIceServers = new List<RTCIceServer> { IceServersStun, IceServersTurn };
```

```
 (2203):[0:] [20:41:18 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on 0.0.0.0:0.
  (2204):[0:] [20:41:18 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on 0.0.0.0:0.
  (2205):[0:] [20:41:18 DBG] CreateBoundUdpSocket successfully bound on 0.0.0.0:35864.
  (2206):[0:] [20:41:18 DBG] Successfully bound RTP socket 0.0.0.0:35864.
  (2207):[0:] [20:41:18 DBG] Adding ICE server for stun:137.220.233.101.
  (2208):[0:] [20:41:18 DBG] Adding ICE server for turn:137.220.233.101:3479.
  (2209):[0:] [20:41:18 DBG] RTPChannel for 0.0.0.0:35864 started.
  (2235):[0:] [20:41:18 DBG] RTP ICE Channel discovered 1 local candidates.
  (2236):[0:] [20:41:18 DBG] Adding ICE server for stun:137.220.233.101.
  (2237):[0:] [20:41:18 DBG] Adding ICE server for turn:137.220.233.101:3479.
  (2238):[0:] [20:41:18 DBG] Attempting to resolve STUN server URI turn:137.220.233.101:3479.
  (2239):[0:] [20:41:18 DBG] ICE server turn:137.220.233.101:3479 successfully resolved to 137.220.233.101:3479.
  (2240):[0:] [20:41:19 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2241):[0:] [20:41:19 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2242):[0:] [20:41:19 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2243):[0:] [20:41:19 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2244):[0:] [20:41:19 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2245):[0:] [20:41:19 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2246):[0:] [20:41:19 WRN] Connection attempt to ICE server turn:137.220.233.101:3479 timed out after 6 requests.
  (2247):[0:] [20:41:19 DBG] Attempting to resolve STUN server URI stun:137.220.233.101.
  (2248):[0:] [20:41:19 DBG] ICE server stun:137.220.233.101 successfully resolved to 137.220.233.101:3478.
  (2249):[0:] [20:41:19 DBG] Sending STUN binding request to ICE server stun:137.220.233.101.
  (2250):[0:] [20:41:19 DBG] Sending STUN binding request to ICE server stun:137.220.233.101.
  (2251):[0:] [20:41:19 DBG] Sending STUN binding request to ICE server stun:137.220.233.101.
  (2252):[0:] [20:41:19 DBG] Sending STUN binding request to ICE server stun:137.220.233.101.
  (2253):[0:] [20:41:19 DBG] Sending STUN binding request to ICE server stun:137.220.233.101.
  (2254):[0:] [20:41:19 DBG] Sending STUN binding request to ICE server stun:137.220.233.101.
  (2255):[0:] [20:41:19 WRN] Connection attempt to ICE server stun:137.220.233.101 timed out after 6 requests.
  (2256):[0:] [20:41:19 DBG] RTP ICE Channel all ICE server connection checks failed, stopping ICE servers timer.
  (2257):[0:] [20:41:19 WRN] Connection attempt to ICE server stun:137.220.233.101 timed out after 6 requests.
```

**Comment by sipsorcery** [comment]
There seems to be a difference between your comment and the log messages. The log messages don't have any reference to `stuns:137.220.233.101:3478`. The `stuns` (note the 'S' at the end) should be rejected by the sipsorcery code since it doesn't support secure STUN or TURN connections.

As for the port number if you leave it off then the default value of `3478` gets used. That's part of the STUN standard. See [STUNUri](https://github.com/sipsorcery/sipsorcery/blob/master/src/net/STUN/STUNUri.cs#L27).

**Comment by CCMeta** [comment]
yes .this log is the time of when this is not work well. 

 I try to find a wired thing..

when I use same IP address with stun and turn.. Both of two give me Timeout...
But Just use Single One unexpectedly Works well. No timeout again.
Let me check again .😭 
thanks

**Comment by CCMeta** [comment]
I am take a point . let us discuss.
https://github.com/sipsorcery/sipsorcery/blob/a62850a88f7bf46d12945325090e9abd5bac56ae/src/net/ICE/RtpIceChannel.cs#L610
In this place when I take two element to the List <RTCIceServer>. The second foreach loop counter  `iceServerID  `  will declare twice to cover first RTCIceServer.  Then this two guys will get same TransactionID. 
And this column https://github.com/sipsorcery/sipsorcery/blob/a62850a88f7bf46d12945325090e9abd5bac56ae/src/net/ICE/RtpIceChannel.cs#L1551
seems will get a exception cause SingleOrDefault.

Do you think the MINIMUM_ICE_SERVER_ID counter should out of foreach loop . 
Perhaps this counter is for all Ice urls. Not Single RTCIceServer .
`UTC8 Night. `

**Comment by sipsorcery** [comment]
The `iceServerID` variable is [getting incremented](https://github.com/sipsorcery/sipsorcery/blob/a62850a88f7bf46d12945325090e9abd5bac56ae/src/net/ICE/RtpIceChannel.cs#L641) within the loop.

Are you seeing an exception anywhere? If so could you paste in the log messages.

**Comment by CCMeta** [comment]
![QQ截图20200826154325](https://user-images.githubusercontent.com/3390228/91277700-c3e6c880-e7b5-11ea-88e3-7420a38e0bc3.jpg)

No end logger. I do not know how to catch a Monitor Exception in Lib on C# now yet.
Perhaps you change SingleOrdefault to FirstOrDefault it will be print Both start and end log. 
No Matter Single or First, Seems You just want to pick just one element ,Right?

**Comment by sipsorcery** [comment]
The reason to use `SingleOrDefault` is that each ICE server (and checklist entry) needs to use a unique transaction ID when sending STUN requests. The transaction ID is used to match the STUN responses back to an ICE server or checklist entry.

If a transaction ID matches multiple ICE servers or checklist entries then it's an important bug and needs to be fixed. If the matching is done incorrectly the wrong ICE candidate could get nominated and connection won't work.

I think the issue may be to do with timing rather than anything to do with the above. Your log shows the attempt to connect to the STUN servers timing out very quickly. I think I might need to adjust some of the timing parameters to allow more time.

As an experiment you can adjust the period between connection attempts by changing [Ta](https://github.com/sipsorcery/sipsorcery/blob/a62850a88f7bf46d12945325090e9abd5bac56ae/src/net/ICE/RtpIceChannel.cs#L125), maybe change it from 50ms to 1000ms.

Also [MAX_REQUESTS](https://github.com/sipsorcery/sipsorcery/blob/a62850a88f7bf46d12945325090e9abd5bac56ae/src/net/ICE/IceServer.cs#L64) to set how many connection attempts will be made to an ICE server. Maybe set as 12.

You can adjust these two parameters depending on how long you want to try and connect to an ICE server before moving onto the next one.

**Comment by CCMeta** [comment]
> The reason to use `SingleOrDefault` is that each ICE server (and checklist entry) needs to use a unique transaction ID when sending STUN requests. The transaction ID is used to match the STUN responses back to an ICE server or checklist entry.
> 
> If a transaction ID matches multiple ICE servers or checklist entries then it's an important bug and needs to be fixed. If the matching is done incorrectly the wrong ICE candidate could get nominated and connection won't work.
> 
> I think the issue may be to do with timing rather than anything to do with the above. Your log shows the attempt to connect to the STUN servers timing out very quickly. I think I might need to adjust some of the timing parameters to allow more time.
> 
> As an experiment you can adjust the period between connection attempts by changing [Ta](https://github.com/sipsorcery/sipsorcery/blob/a62850a88f7bf46d12945325090e9abd5bac56ae/src/net/ICE/RtpIceChannel.cs#L125), maybe change it from 50ms to 1000ms.
> 
> Also [MAX_REQUESTS](https://github.com/sipsorcery/sipsorcery/blob/a62850a88f7bf46d12945325090e9abd5bac56ae/src/net/ICE/IceServer.cs#L64) to set how many connection attempts will be made to an ICE server. Maybe set as 12.
> 
> You can adjust these two parameters depending on how long you want to try and connect to an ICE server before moving onto the next one.

Yes I am get your point. Not disagrees you. I am not want to change SingleOrDefault to FirstOrDefault ...
Just want to tell you. Because MINIMUM_ICE_SERVER_ID is duplicate assign to 0. 
That is why disappear SingleOrDefault is crash.

**Comment by CCMeta** [comment]
```

  (2105):[0:] [19:19:29 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on 0.0.0.0:0.
  (2106):[0:] [19:19:29 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on 0.0.0.0:0.
  (2107):[0:] [19:19:29 DBG] CreateBoundUdpSocket successfully bound on 0.0.0.0:53232.
  (2108):[0:] [19:19:29 DBG] Successfully bound RTP socket 0.0.0.0:53232.
  (2109):[0:] [19:19:29 DBG] Adding ICE server for stun:137.220.233.101:3479.
  (2110):[0:] [19:19:29 DBG] Adding ICE server for turn:137.220.233.101:3479.
  (2111):[0:] [19:19:29 DBG] RTPChannel for 0.0.0.0:53232 started.
  (2137):[0:] [19:19:29 DBG] RTP ICE Channel discovered 1 local candidates.
  (2138):[0:] [19:19:29 DBG] Adding ICE server for stun:137.220.233.101:3479.
  (2139):[0:] [19:19:29 DBG] Adding ICE server for turn:137.220.233.101:3479.
  (2140):[0:] [19:19:29 DBG] Attempting to resolve STUN server URI turn:137.220.233.101:3479.
  (2141):[0:] [19:19:29 DBG] ICE server turn:137.220.233.101:3479 successfully resolved to 137.220.233.101:3479.
  (2147):[0:] [19:19:30 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2148):[0:] [19:19:30 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2149):[0:] [19:19:30 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2154):[0:] [19:19:30 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2155):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2156):[0:] [19:19:30 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2157):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2161):[0:] [19:19:30 DBG] Sending TURN allocate request to ICE server turn:137.220.233.101:3479.
  (2162):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2163):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2169):[0:] [19:19:30 WRN] Connection attempt to ICE server turn:137.220.233.101:3479 timed out after 6 requests.
  (2179):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2182):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2186):[0:] [19:19:30 DBG] Attempting to resolve STUN server URI stun:137.220.233.101:3479.
  (2187):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2188):[0:] [19:19:30 DBG] ICE server stun:137.220.233.101:3479 successfully resolved to 137.220.233.101:3479.
  (2189):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2195):[0:] [19:19:30 DBG] Sending STUN binding request to ICE server stun:137.220.233.101:3479.
  (2201):[0:] [19:19:30 DBG] Sending STUN binding request to ICE server stun:137.220.233.101:3479.
  (2202):[0:] [19:19:30 DBG] Sending STUN binding request to ICE server stun:137.220.233.101:3479.
  (2203):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2204):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2208):[0:] [19:19:30 DBG] Sending STUN binding request to ICE server stun:137.220.233.101:3479.
  (2209):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2210):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2214):[0:] [19:19:30 DBG] Sending STUN binding request to ICE server stun:137.220.233.101:3479.
  (2215):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2216):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2220):[0:] [19:19:30 DBG] Sending STUN binding request to ICE server stun:137.220.233.101:3479.
  (2221):[0:] [19:19:30 DBG] [ccmeta] start find _iceServerConnections 
  (2222):[0:] [19:19:30 DBG] [ccmeta] end find _iceServerConnections System.InvalidOperationException: Sequence contains more than one element
  (2226):[0:] [19:19:30 WRN] Connection attempt to ICE server stun:137.220.233.101:3479 timed out after 6 requests.
  (2227):[0:] [19:19:30 DBG] RTP ICE Channel all ICE server connection checks failed, stopping ICE servers timer.
  (2228):[0:] [19:19:30 WRN] Connection attempt to ICE server stun:137.220.233.101:3479 timed out after 6 requests.
```

**Comment by sipsorcery** [comment]
You are correct, it was a silly bug on my behalf. Thx for persevering with your explanations.

It's fixed on `master` now.

**Comment by CCMeta** [comment]
Looks that just happened when stun address same as turn. 
My language skills is poor.
So I am super worried about my English skills to communicate normally now.
😱 
I'm working on codec for iOS and android. When it works will let you know directly.

**Comment by sipsorcery** [comment]
> I'm working on codec for iOS and android. When it works will let you know directly.

Awesome!

If you're going the `PInvoke` route I've been doing work with `libvpx`, ffmpeg` etc. If you are take a look at the new repo's below, they might help:

 - [SIPSorceryMedia.Windows](https://github.com/sipsorcery/SIPSorceryMedia.Windows)
 - [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery/SIPSorceryMedia.FFmpeg)
 - [SIPSorceryMedia.Abstractions](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions).

* All the above are subject to rapid and major changes.

**Comment by hossam14102010** [comment]
@CCMeta could you make the codec?
