### ISSUE TITLE
Softphone external incoming calls not working

### ISSUE THREAD

**Issue by thornzz** [sipsorcery/sipsorcery#286]
Hi,

Im using latest version sipsorcery and latest version softphone example. I can call another extension or another extension can call me but when i call our sip server from outside (from my mobile phone) ;
At this row ;
  SDP offerSDP = SDP.ParseSDPDescription(sipRequest.Body);

im getting 'System.NullReferenceException: 'Object reference not set to an instance of an object.'  because of sipRequest.Body is null.  

### By the way there is no problem with if i make and outbound call to same mobile phone number.

Is there any idea?

**Comment by sipsorcery** [comment]
The `SIPUserAgent` should deal with an empty body on the INVITE request.

Are you able to run the softphone in the Visual Studio debugger? The Debug messages in the `Output` window would be helpful.

**Comment by thornzz** [comment]
Hi,

Thank you for your answer. I have fixed it by this rows; Im checking if Body is null or not.

            bool hasAudio = false;
            bool hasVideo = false;
        if (sipRequest.Body!=null)
                {
                    SDP offerSDP = SDP.ParseSDPDescription(sipRequest.Body);
                     hasAudio = offerSDP.Media.Any(x => x.Media == SDPMediaTypesEnum.audio && x.MediaStreamStatus != MediaStreamStatusEnum.Inactive);
                    hasVideo = offerSDP.Media.Any(x => x.Media == SDPMediaTypesEnum.video && x.MediaStreamStatus != MediaStreamStatusEnum.Inactive);
                }
                else
                {

                    hasAudio = true;
                    hasVideo = false;
                }
