### ISSUE TITLE
Is there any way to modify or hide incoming call from section?

### ISSUE THREAD

**Issue by thornzz** [sipsorcery/sipsorcery#287]
Hi,

I want to hide who is calling section or want to modify it at Softphone example project. Is there any way to do it?

Screenshot : https://prnt.sc/tz6xcl

**Comment by sipsorcery** [comment]
Comment or modify this [line](https://github.com/sipsorcery/sipsorcery/blob/1aa8efbd028947f76a13d3faf870666ae55088d9/examples/Softphone/Softphone.xaml.cs#L207).

**Comment by thornzz** [comment]
Thanks. Thats what i want. 👍
