### ISSUE TITLE
use of other codecs

### ISSUE THREAD

**Issue by dxmann** [sipsorcery/sipsorcery#294]
Hello!
I tested sipsorcery client some months ago for a project and I would ask if it is possible to:
- have a media interface in order to implement it in xam. android or iOS
- design that interface in order to allow the usage of other codecs (for example H263, etc); I had problems to compose or extract rtp video packets with H263P without modifications of the library's source code by my self.

Thank you for your work. Regards!

**Comment by sipsorcery** [comment]
Yes as it happens I'm in the middle of working on a first cut of an approach to more easily allow other media layers to be plugged in. The broad overview (subject to rapid and frequent change):

 - A separate library and nuget package will hold an interface for audio/video devices/encoding features. Currently called [IPlatformMediaSession](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions/blob/master/src/V1/IPlatformMediaSession.cs).

 - The main sipsorcery library will accept `IPlatformMediaSession` implementations and wire them up to the `RTPSession` and `RTCPeerConnection` for, hopefully, simple integration between the audio/video transport and generation/consumption. Currently called [PlatformMediaSession](https://github.com/sipsorcery/sipsorcery/blob/imedia/src/app/Media/PlatformMediaSession.cs).

 - Separate libraries will then be able to implement [IPlatformMediaSession] and pull in OS specific device calls and/or native libraries for additional codecs. I plan on doing bare bones implementations for:
   - [Windows](https://github.com/sipsorcery/SIPSorceryMedia.Windows),
   - [FFmpeg](https://github.com/sipsorcery/SIPSorceryMedia.FFmpeg) which should work on any platform that can install the FFmpeg libraries,
   - `Unix` which I haven't started which is envisioned to allow audio capture and playback on `Linux` and `Macos`, probably via `PortAudio`.
   - Xamarin on Android and iOS. I don't have plans to implement but it should be possible for anyone motivated to build a custom library based off one of the above examples.

It's a lot of work to do cross platform audio/video and I only intend to do basic audio/video features and core codecs. And that's only if I don't run out of steam in the process.

Life would be a lot easier if Microsoft would add basic audio/video support to .NET Core SDK, even Windows only, but unfortunately there's not a lot of [interest](https://github.com/dotnet/runtime/issues/38886).

**Comment by dxmann** [comment]
I'm in the last group: "xamarin developers" :)
I can try to implement something behind `IPlatformMediaSession`

**Comment by sipsorcery** [comment]
@CCMeta may be of interest for your iOS/Android codec efforts.

**Comment by sipsorcery** [comment]
The interfaces needed to implement media end points have now stabilised to the point where I only expect incremental changes. If anyone is still looking at integrating audio/video devices on top of Xamarin and to work with this library then take a look at [SIPSorceryMedia.Abstractions](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions/blob/master/src/V1/MediaEndPoints.cs).

There's no documentation as yet, that should be too far away. The [Windows implementation](https://github.com/sipsorcery/SIPSorceryMedia.Windows) can server as an example.
