### ISSUE TITLE
Support for other schemes in SIPURI

### ISSUE THREAD

**Issue by RoryRoberts** [sipsorcery/sipsorcery#295]
Would you be open to supporting more schemes in SIP URIs in sip sorcery? From my understanding it's not against the sip spec to use schemes other than `sip` and `sips`, but I appreciate you might not want it as a part of sip sorcery.

I'm prototyping specifically for a `tel` scheme but appreciate there could be others, I also note you specifically validate against unknown schemes (`tel` in particular) in a unit test: `SIPURIUnitTest.UnknownSchemeUnitTest`. I've resolved this by changing the schemes enum to a string and defining `sip` and `sips` as constants which works for me and doesn't alter any of the current important logic (e.g. "Sips" still branches things appropriately, like for tls) but I don't know if I'm missing anything important here, especially around providing validations for "Supported schemes" if you explicitly don't want to support some things.

I would be happy to share a pull request if you're open to it though.

**Comment by sipsorcery** [comment]
Can't see a problem with supporting other SIP URI schemes. Please do submit a PR.
