### ISSUE TITLE
Authorization fails on first REGISTER

### ISSUE THREAD

**Issue by FrankPfattheicher** [sipsorcery/sipsorcery#299]
sipgate

1	0.000000	192.168.2.147	217.10.79.9	SIP	524	Request: REGISTER sip:sipgate.de  (1 binding) | 
2	0.025478	217.10.79.9	192.168.2.147	SIP	482	Status: 401 Unauthorized | 
4	0.135449	192.168.2.147	217.10.79.9	SIP	707	Request: REGISTER sip:sipgate.de  (1 binding) | 
5	0.159324	217.10.79.9	192.168.2.147	SIP	466	Status: 200 OK  (1 binding) | 

Unify OpenScape Voice
[REGISTER.zip](https://github.com/sipsorcery/sipsorcery/files/5129712/REGISTER.zip)

653	8.009290	10.124.19.10	10.100.1.10	SIP	531	Request: REGISTER sip:10.100.1.10  (1 binding) | 
654	8.011049	10.100.1.10	10.124.19.10	SIP	568	Status: 401 Unauthorized | 
675	8.064591	10.124.19.10	10.100.1.10	SIP	766	Request: REGISTER sip:10.100.1.10  (1 binding) | 
676	8.065615	10.100.1.10	10.124.19.10	SIP	504	Status: 423 Interval Too Brief | 
715	8.115709	10.124.19.10	10.100.1.10	SIP	531	Request: REGISTER sip:10.100.1.10  (1 binding) | 
716	8.116661	10.100.1.10	10.124.19.10	SIP	556	Status: 401 Unauthorized | 

Registration fails entirely here....

**Comment by sipsorcery** [comment]
You need to change the `Expires`  value you are requesting.

`: 423 Interval Too Brief |`

**Comment by FrankPfattheicher** [comment]
@sipsorcery setting expires to 500 for Unify OpenScape it works, thank you.
What about the idea to have something like server profiles with known good values for compatibility issues?
