### ISSUE TITLE
NullReferenceException in SIPUDPTransport

### ISSUE THREAD

**Issue by achikhv** [sipsorcery/sipsorcery#30]
This simple program causes NullReferenceException.
```
static void Main(string[] args)
{
     var channel = new SIPSorcery.SIP.SIPUDPChannel(new System.Net.IPEndPoint(System.Net.IPAddress.Any, 0));
}
```

Stack trace:
  at SIPSorcery.SIP.SIPUDPChannel.Initialise()
  at SIPSorcery.SIP.SIPUDPChannel..ctor(IPEndPoint endPoint)

**Comment by sipsorcery** [comment]
Fixed.
