### ISSUE TITLE
Wrong media format name

### ISSUE THREAD

**Issue by dxmann** [sipsorcery/sipsorcery#300]
I'm working with H263-1998.
When I receive the sdp inside OK packet of an INVITE request I have that:
my SDPMediaFormat has name "H263-1998"
the remote SDPMediaFormat has name "1998"

Inside wiresharks I can't see errors.

Is this a bug or I'm doing an error?

**Comment by sipsorcery** [comment]
Can you paste the SDP here? Also there is no way to decode H263 samples with this library so you'll need to use your own implementation before and after you send and receive RTP packets.

**Comment by dxmann** [comment]
sent sdp:
```
v=0
o=- 1970544282 0 IN IP4 127.0.0.1
s=-
c=IN IP4 10.10.1.8
t=0 0
m=audio 57982 RTP/AVP 0 8
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=sendrecv
m=video 57984 RTP/AVP 96
a=rtpmap:96 H263-1998/90000
a=fmtp:96 QCIF=3
a=sendrecv
```

received sdp:
```
v=0
o=UAUCloud 172 396 IN IP4 95.110.164.29
s=sipcall
c=IN IP4 95.110.164.29
t=0 0
m=audio 31568 RTP/AVP 0 101
c=IN IP4 95.110.164.29
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
m=video 24188 RTP/AVP 96
c=IN IP4 95.110.164.29
a=rtpmap:96 H263-1998/90000
a=fmtp:96 CIF=2
```

**Comment by sipsorcery** [comment]
Thx, I understand the issue and will take a look.

**Comment by sipsorcery** [comment]
Fixed on `master` now. Thanks for the bug report.

**Comment by dxmann** [comment]
This morning I've tested the library in my project: no errors 👍 
Thanks!!
