### ISSUE TITLE
Proxy Server

### ISSUE THREAD

**Issue by dokaniamukesh** [sipsorcery/sipsorcery#305]
Dear Sir,

I want to implement a proxy server,  where all user register and incoming call can be routed to different user and record the call.
Is this possible ? if so how ?

Can you provide an example ?

**Comment by sipsorcery** [comment]
There is a [SIPProxy](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/SIPProxy) example which should be able to get you started.

**Comment by dokaniamukesh** [comment]
Yes, i have looked that example, but there is reference for call manager, call recording and routing the call. Is there any reference for that ?

**Comment by sipsorcery** [comment]
Typically a SIP Proxy server wouldn't touch the media so functions like call recording would not be handled by it.

The other server type example is [SIPCallServer](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/SIPCallServer) which acts as a SIP Server.

Sounds like you may need a combination of these two and more. I'd suggest choosing one of the two server applications mentioned as a starting point and then add the features you need.

**Comment by dokaniamukesh** [comment]
but it is doing call transfer and not the routing.do you have example of routing in proxy ?
i

**Comment by dokaniamukesh** [comment]
also blindTransfer not working

**Comment by sipsorcery** [comment]
No there are no more examples other than the ones mentioned. If you've found a bug please open a new issue and provide a brief description and ideally log messages.
