### ISSUE TITLE
i am using UsingAgentServer example..i need to change audio file of RtpAVSession runtime. basically  i want to send audio file as a response to the client who is calling.

### ISSUE THREAD

**Issue by jitendragupta2** [sipsorcery/sipsorcery#306]

**Comment by sipsorcery** [comment]
See the [PlaySounds](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/PlaySounds) example.

**Comment by jitendragupta2** [comment]
i am trying to make an IVR system. so i want UserAgentServer to send response a audio file. but in sounds the SIPUserAgent(client) is sending audio. can you help on this

**Comment by sipsorcery** [comment]
In the UserAgentServer example you can [change the initial audio source](https://github.com/sipsorcery/sipsorcery/blob/66cf88d6842a19bda3c849b121bf778f336e66da/examples/SIPExamples/UserAgentServer/Program.cs#L154) to `Silence`. Then after the call is answered and `rtpSession.Start` is called you can call `extrasSource.SendAudioFromStream` to play your sound file.

**Comment by jitendragupta2** [comment]
Thanks ..let me try... will keep you posted.. just to tell you.. i receive dtmf tone from client and accordingly i want to send audio response from server i am using RTPAVSession for that.. below is the snippet... do you have better suggestion? pls help
private static void OnRtpEvent(RTPEvent rtpevent, RTPHeader rtpheader)
        {
            if(rtpheader.MarkerBit == 1)
            {
                Console.WriteLine(rtpevent.EventID);
                if (rtpevent.EventID == 5)

**Comment by sipsorcery** [comment]
If you don't have a specific reason for using the `SIPServerUserAgent` class you would be better off using `SIPUserAgent`. It operates as a higher level that's more suitable for applications and has things like `OnDtmfETone`[https://github.com/sipsorcery/sipsorcery/blob/66cf88d6842a19bda3c849b121bf778f336e66da/src/app/SIPUserAgents/SIPUserAgent.cs#L324].

I'd also recommend switching from `RtpAVSession` to [VoIPMediaSession](https://github.com/sipsorcery/sipsorcery/blob/master/src/app/Media/VoIPMediaSession.cs). It's the new version and the one that will be maintained. All the examples have been updated to use the new class and it's a minor change to update your application.

**Comment by sipsorcery** [comment]
Feel free to re-open if there are any further questions.
