### ISSUE TITLE
Connecting to server

### ISSUE THREAD

**Issue by SenolBalaban** [sipsorcery/sipsorcery#31]
Hello 
First Very nice piece of software you have built.

I am trying to connect to swisscom.ch with the sample softphone
I received following settings from my provider

> Username (landline number): =>+415XXXXXXXX
> Authentication name:  XXXXXXXXXXX@swisscom.ch
> Password:  passsword
> Domain:  swisscom.ch
> Outbound Proxy:  fs1.ims.swisscom.ch

App.config looks like this
 ```xml
<appSettings>
    <add key="STUNServerHostname" value="stun.ekiga.net"/>  
    <add key="SIPUsername" value="XXXXXXXX"/>
    <add key="SIPPassword" value="XXXXXX"/>
    <add key="SIPServer" value="swisscom.ch"/>
    <add key="SIPFromName" value="+415XXXXXXXX"/>
  </appSettings>
```

I tried to connect like that with minimal modification because of proxy

```c#
 var proxy = new SIPEndPoint(new IPEndPoint(Dns.GetHostAddresses("fs1.ims.swisscom.ch")[0],5061));
            _sipRegistrationClient = new SIPRegistrationUserAgent(
                _sipClient.SIPClientTransport,
                proxy, 
                null,
                new SIPURI(m_sipUsername, m_sipServer, null, SIPSchemesEnum.sip, SIPProtocolsEnum.udp),
                m_sipUsername,
                m_sipPassword,
                null,
                m_sipServer,
                new SIPURI(m_sipUsername, _sipClient.SIPClientTransport.GetDefaultSIPEndPoint().GetIPEndPoint().ToString(), null),
                180,
                null,
                null,
                (message) => { logger.Debug(message); });
            _sipRegistrationClient.Start();

```

but getting som error like 

> Die Sequenz enthält keine Elemente. => The sequence does not contain any Elements

I think it is important to mention that I have a normal DSL Modem(Router)  with an attached additional Router for internal Network.

What am I doing wrong?

Sincerely 
Senol Balaban

**Comment by SenolBalaban** [comment]
ok I fixed the Error like here mentioned #20 with a configured flag.
Stunclient is also working.

but the Register fails:


> Request Sent: udp:192.168.188.48:5061->udp:195.186.128.164:5061
> REGISTER sip:swisscom.ch SIP/2.0
> Via: SIP/2.0/UDP 192.168.188.48:5061;branch=z9hG4bK755bef427dad4b82b84e62ec6a5d97ed;rport
> To: <sip:NC964619121811@swisscom.ch>
> From: <sip:NC964619121811@swisscom.ch>;tag=HGEBTPFXJP
> Call-ID: 27be14ba-bcfe-4e2c-a06d-b956f349724d
> CSeq: 1 REGISTER
> Contact: <XXXXXXXX@192.168.188.48:5061> <<HERE
> Max-Forwards: 70
> User-Agent: www.sipsorcery.com
> Expires: 1000
> Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, REFER, REGISTER, SUBSCRIBE
> Content-Length: 0
> 
> 
> SIPRegistrationUserAgent temporarily failed, scheduling next registration to sip:XXXXXXXX@swisscom.ch in 300s.
> 
but the Contact URI is my internal IP adress should that not be my public IP address ?

**Comment by sipsorcery** [comment]
> The program is always showing my internal IP adress should that not be my public IP address ?

The public IP address doesn't get substituted into the Contact header automatically you'll have to do it yourself if it needs to be done. Take a look at SIPSorcery.Net.StunClient.GetPublicIPAddress,

Before you go too far down that path be aware most SIP registrars will substitute in the public IP address on behalf of the client. That is if the registrar receives a REGISTER request with a private IP address in the contact the registrar will assume the client didn't know its public IP address and swap in the IP address the request was received from. In other words don't worry about it and it will most likely just work.

**Comment by SenolBalaban** [comment]
Hi thanks for the Answer

I captured the network packages of a working client and it looks different from the program generates.

> REGISTER sip:swisscom.ch SIP/2.0
> Via: SIP/2.0/UDP 1
> 88.62.169.238:49154;rport;branch=z9hG4bK2C193AC138BCF931 <<PUBLIC IPADRESS
> Route: <sip:fs1.ims.swisscom.ch;lr>			<<ROUTE PROXY
> From: <sip:+41XXXXXXXXXXX@swisscom.ch>;tag=713584095
> To: <sip:+41XXXXXXXXXXX@swisscom.ch>
> Call-ID: F4221E6C0292B22A@188.62.169.238
> CSeq: 3964 REGISTER
> Authorization: Digest username="NCXXXXXXXXXX@swisscom.ch", realm="swisscom.ch", nonce="9BF6717A5B51285900000000FFFFFFFF", uri="sip:swisscom.ch", response="1bdca850b94705dd1f164fcfffffffff", algorithm=MD5, cnonce="38A51037Dfffffff", qop=auth, nc=00000003
> Max-Forwards: 70
> User-Agent: AVM FRITZ!Box 7490 113.06.83 (Mar 21 2017)
> Supported: 100rel,replaces
> Allow-Events: telephone-event,refer,reg
> Allow:  INVITE,ACK,OPTIONS,CANCEL,BYE,UPDATE,PRACK,INFO,SUBSCRIBE,NOTIFY,REFER,MESSAGE,PUBLISH
> Accept: application/sdp, multipart/mixed
> Accept-Encoding: identity
> Content-Length: 0

for comparison the networkpackage capture of the softphone


> REGISTER sip:swisscom.ch SIP/2.0
> Via: SIP/2.0/UDP 192.168.188.48:5061;branch=z9hG4bK9df69497a65542788bf8a3bbcc9f057f;rport
> To: <sip:+41XXXXXXXXX@swisscom.ch>
> From: <sip:+41XXXXXXXXX@swisscom.ch>;tag=PPBKHTMVTC
> Call-ID: 034f750e-715e-423d-a285-7cab50b4e063
> CSeq: 1 REGISTER
> Contact: <sip:+41XXXXXXXXX@192.168.188.48:5061>
> Max-Forwards: 70
> User-Agent: www.sipsorcery.com
> Expires: 180
> Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, REFER, REGISTER, SUBSCRIBE
> Content-Length: 0
> 

for me the most the most significant parts are that it has ant "Authorization" header and that the proxy is a domain name and not an ip adress. 



How its possible to generate such a request?
Sincerely
Senol Balaban

**Comment by sipsorcery** [comment]
SIP uses a challenge response mechanism for authentication. The initial request should be sent without the authentication header. The server will respond with a an authentication header that contains the random nonce and domain which the client then needs to use to construct the authentication header in the second SIP response.

You can use the SIPSorcery.SIP.App.SIPRegistrationUserAgent class to take care of authentication for you or you can use it as an example for your own logic.

**Comment by SenolBalaban** [comment]
Yep, finally worked how I wanted thanks. 👍

**Comment by SenolBalaban** [comment]
thx again

**Comment by MassoudEbrahimi** [comment]
Hi , How to Add Authenticate to request in need it  , when send request has 403 forbidden error , can you help me ?

**Comment by evrenmarin** [comment]
I had the same problem but I can't solve the problem. Where is the problem here? Please can you help?

int expiry = 20;
string username = "+41xxx";
string password = "x";
string domain = "swisscom.ch";
string sipServerHostname = "fs1.ims.swisscom.ch";

var sipTransport = new SIPTransport();
sipTransport.EnableTraceLogs();

var regUserAgent = new SIPRegistrationUserAgent(sipTransport, username, password, domain, expiry);

IPAddress[] serverIPAddresses = Dns.GetHostAddresses(sipServerHostname);
if (serverIPAddresses.Length > 0)
{
    var outboundProxy = new SIPEndPoint(SIPProtocolsEnum.udp, serverIPAddresses[0], 5060);
    regUserAgent.OutboundProxy = outboundProxy;

}

sipTransport.SIPRequestInTraceEvent += (localSIPEndPoint, remoteEndPoint, sipRequest) =>
{
    Console.WriteLine($"Incoming Request: {sipRequest.ToString()}");
};

sipTransport.SIPRequestOutTraceEvent += (localSIPEndPoint, remoteEndPoint, sipRequest) =>
{
    Console.WriteLine($"Outgoing Request: {sipRequest.ToString()}");
};

sipTransport.SIPResponseInTraceEvent += (localSIPEndPoint, remoteEndPoint, sipResponse) =>
{
    Console.WriteLine($"Incoming Response: {sipResponse.ToString()}");
};

sipTransport.SIPResponseOutTraceEvent += (localSIPEndPoint, remoteEndPoint, sipResponse) =>
{
    Console.WriteLine($"Outgoing Response: {sipResponse.ToString()}");
};


// Geri kalan kısım aynı...
regUserAgent.RegistrationFailed += RegUserAgent_RegistrationFailed;
regUserAgent.RegistrationTemporaryFailure += RegistrationTemporaryFailure;
regUserAgent.RegistrationRemoved += RegistrationRemoved;
regUserAgent.RegistrationSuccessful += RegistrationSuccessful;

regUserAgent.Start();
