### ISSUE TITLE
Server | welcome music file want to change |  .ulaw file

### ISSUE THREAD

**Issue by jitendragupta2** [sipsorcery/sipsorcery#311]
i have created two application - one client and one server. server acts as a IVR. when i call from client i hear audio file music, i want to change the audio file . please help, below is the code which is responsible for music. i want some welcome music to be played for client. Also there are some .ulaw files which are used - don't know about them

````csharp
extrasSource = new AudioExtrasSource(new AudioEncoder(), new AudioSourceOptions { AudioSource = AudioSourcesEnum.Music});
rtpSession = new VoIPMediaSession(new MediaEndPoints { AudioSource = extrasSource });
````

**Comment by sipsorcery** [comment]
All music files now need to be in a PCM 8Khz 16 bit little endian format (previously multiple copies of each file for each different codec but it's easier just to supply them in a PCM format and encode as needed).

To set a custom music file you need to set the `MusicFile` option.

````csharp
var ua = new SIPSorcery.SIP.App.SIPUserAgent();
var audioSource = new AudioExtrasSource(new AudioEncoder(), new AudioSourceOptions { AudioSource = AudioSourcesEnum.Music, MusicFile = "whitelight.raw" });
var ms = new VoIPMediaSession(new SIPSorceryMedia.Abstractions.V1.MediaEndPoints { AudioSource = audioSource });
var res = await ua.Call("aaron@192.168.0.50:6060", null, null, ms);

Console.WriteLine($"Call result {res}.");
Console.WriteLine("Press any key to exit...");
Console.ReadLine();
````

You can use [ffmpeg](https://www.ffmpeg.org/) to convert your music files into the required format.
`ffmpeg -i whitelight.mp3 -ar 8k -f s16le -ac 1 whitelight.raw`
`

**Comment by jitendragupta2** [comment]
It is not working.. i get the default tone

                            Log.LogDebug($"Client offer contained PCMU audio codec.");
                            extrasSource = new AudioExtrasSource(new AudioEncoder(), new AudioSourceOptions { AudioSource = AudioSourcesEnum.Music, MusicFile = "welcome.mp3" });
                            rtpSession = new VoIPMediaSession(new MediaEndPoints { AudioSource = extrasSource });
                            rtpSession.AcceptRtpFromAny = true;

**Comment by sipsorcery** [comment]
That most likely means the file could not be found. Check the log messages.

Also see my note about converting your file to the correct format. You can't play `mp3` files directly, they need to be converted using `ffmpeg` or equivalent.

**Comment by jitendragupta2** [comment]
i converted to .wav but in log message i get message
 [17:49:37 WRN] Music file not set or not found, using default music resource.

**Comment by sipsorcery** [comment]
That means the file still can't be found. Make sure it's in the same directory as the executable.

`i converted to .wav`

You need to read what I've written above. `.wav` files won't work.

**Comment by jitendragupta2** [comment]
sorry i converted to .raw and placed in the executable folder but still getting the same error

**Comment by sipsorcery** [comment]
How are you executing your app? If you're using `dotnet run` then the location the app looks for files changes.

I'd recommend changing the path you're using to a fully qualified one, e.g. `c:/temp/welcome.raw`, and once you have that working track down why your relative file path can't be found.

**Comment by jitendragupta2** [comment]
Thanks for your help. it worked
