### ISSUE TITLE
Issue with peers connecting from outside my network

### ISSUE THREAD

**Issue by Tides** [sipsorcery/sipsorcery#314]
I've followed the https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/FfmpegToWebRTC example and now I'm trying to get people from outside to connect to see and the connection state changes to disconnected then failed. I'm wondering if there's anything in particular that I'm missing. 

The code is the same from the example the only thing I'm using is asp net core ^ ^
Another question is should I manage it how you managed it in the asp net example?

**Comment by sipsorcery** [comment]
The instructions for that example use the loopback address `127.0.0.1` which means the `FFmpeg` executable and the .NET Core console application have to be on the same machine.

It can be adjusted to listen on a different address but if you are hoping to get external connections to your machine you are still going to have NAT and firewall hurdles to overcome. Do you know how to deal with them?

**Comment by Tides** [comment]
Yeah, the ffmpeg script is running locally as the .net core app so I assumed I would have no problems when it came for people connecting to the app externally since its running on the web the ports I have open is the one the site uses which is :5000 and the websocket :8081 I thought all they need is the connection to the server and all the server needs is the connection the the ffmpeg output

**Comment by sipsorcery** [comment]
Sorry I'm not sure what's being asked here. Can you narrow down the problem to a code snippet or more detailed description?

**Comment by Tides** [comment]
Okay so the problem I'm having currently pertains to an outside connection getting a live feed from the server. I've made sure I did the proper firewall stuff which includes ports being opened etc.. FFMPEG is doing its thing locally on the same machine so there's no problem there. I tried to see if I can find a specific area where it happens but I've had no luck so far ~ Here are some logs maybe this will give you more insight. It sends/connects then it disconnects and fails here's a gist of the class its the same as the example. 

https://gist.github.com/Tides/7924c36ea9ba13f6a8b478f20dbe616e
```
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Web socket client connection from USERIP:63560, sending offer.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Sending SDP offer to client USERIP:63560.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Answer SDP: v=0
      o=- 5750405465037392158 2 IN IP4 127.0.0.1
      s=-
      t=0 0
      a=group:BUNDLE 0
      a=msid-semantic: WMS
      m=video 9 UDP/TLS/RTP/SAVP 96
      c=IN IP4 0.0.0.0
      a=rtcp:9 IN IP4 0.0.0.0
      a=ice-ufrag:DknG
      a=ice-pwd:3ghnaQvawz76i9TH2zaTrejC
      a=ice-options:trickle
      a=fingerprint:sha-256 16:25:69:76:83:97:72:7F:32:3E:E6:62:1E:FC:E6:BE:F7:04:D4:FC:A3:D1:B5:C5:E1:5D:CB:C3:5A:34:37:C0
      a=setup:active
      a=mid:0
      a=recvonly
      a=rtcp-mux
      a=rtpmap:96 H264/90000
      a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

dbug: PacketTalk.Server.Services.OtherServicer[0]
      ICE connection state change to checking.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Peer connection state changed to connecting.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      ICE Candidate: {"candidate":"candidate:111704799 1 udp 2113937151 99d9d49c-d69a-4b45-80b9-d09690e4d510.local 53833 typ host generation 0 ufrag DknG network-cost 999","sdpMid":"0","sdpMLineIndex":0}
warn: PacketTalk.Server.Services.OtherServicer[0]
      Error adding remote ICE candidate. Remote ICE candidate has an unsupported MDNS hostname 99d9d49c-d69a-4b45-80b9-d09690e4d510.local. 111704799 1 udp 2113937151 99d9d49c-d69a-4b45-80b9-d09690e4d510.local 53833 typ host generation 0
dbug: PacketTalk.Server.Services.OtherServicer[0]
      ICE Candidate: {"candidate":"candidate:842163049 1 udp 1677729535 USERIP 53833 typ srflx raddr 0.0.0.0 rport 0 generation 0 ufrag DknG network-cost 999","sdpMid":"0","sdpMLineIndex":0}
dbug: PacketTalk.Server.Services.OtherServicer[0]
      ICE connection state change to connected.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Peer connection state changed to connected.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Creating RTP session to receive ffmpeg stream.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      ICE connection state change to disconnected.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Peer connection state changed to disconnected.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      ICE connection state change to failed.
dbug: PacketTalk.Server.Services.OtherServicer[0]
      Peer connection state changed to failed.```

**Comment by Tides** [comment]
Okay so after an hour of debugging I figured out the problem... Thank you for responding ~

**Comment by Jvs34** [comment]
Please do explain what you were doing wrong and how you fixed the issue [in case someone else runs into the issue](https://i.redd.it/7khgt29lp1121.jpg) in the future.

**Comment by Tides** [comment]
Haha, sorry about that the problem was with not being able to connect to the stun server I had running ^ ^ I'm not sure why it doesn't get binded when I run it but that's a separate issue ~ @Jvs34
