### ISSUE TITLE
Capture pressed Keyboard Buttons by callee while call is established

### ISSUE THREAD

**Issue by alinoob** [sipsorcery/sipsorcery#315]
Is there a handy possibility to capture the keyboard buttons pressed by a callee while call? I figured out that the logger outputs Signal=2 when 2 is pressed by the callee.

**Comment by sipsorcery** [comment]
Sorry I don't understand this question? Is this in relation to the softphone or one of the example apps or something else?

**Comment by alinoob** [comment]
This is in relation of the behaviour of SIPSorcery when a call is established. So far, I only tested it out on the examples, e.g. GetStartedFramework.

For example, I call someone and the call is established. Now, when the callee presses the "2" button on the keyboard of his phone, those are displayed in the ConsoleLogger in such a way: Signal=2. I am only asking, whether there is an easy way to capture the buttons pressed by the callee so that I could use those information sent by the callee.

Another example: You might heard of people pressing codes while calling a specific number to load their prepaid-cards via mobile. The system then asks for a code number which then the caller types in the keyboard of his mobile phone.

**Comment by sipsorcery** [comment]
Have you seen the [SIPUserAgent.OnDtmfTone](https://github.com/sipsorcery/sipsorcery/blob/2fec2a0c5ed052c418712e57a115f258b6a0a2cb/src/app/SIPUserAgents/SIPUserAgent.cs#L324) event? It will notify your app of any DTMF tone events received.

**Comment by sipsorcery** [comment]
Feel free to re-open if any further queries.

**Comment by alinoob** [comment]
So my idea is to confirm an established call after the callee pressed some numbers on his phone keypad. The callee will hear some text to speech and has to confirm the call by pressing a code on his keypad.
Is there any documentation or example how to use it? I'm not even sure what those two parameters stand for.

**Comment by sipsorcery** [comment]
I'm still not sure what you're asking? Is your problem sending DTMF, receiving DTMF, working out how to interact with an active call or something else? There are already examples doing all of those things:

 - [Send DTMF](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/SendDtmf).
 - Receive DTMF is used in various spots. Search the examples for `userAgent.OnDtmfTone`.
- [Active call interaction](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/SIPCallServer/Program.cs).

**Comment by alinoob** [comment]
I call Person A. Person A picks up and presses buttons on his keypad. I want to know which buttons Person A has pressed. Thats all.

**Comment by sipsorcery** [comment]
> I call Person A. Person A picks up and presses buttons on his keypad. I want to know which buttons Person A has pressed. Thats all. But the sources you send should help, thanks.

`userAgent.OnDtmfTone`
