### ISSUE TITLE
how to stop initial music file of Userserveragent answer call

### ISSUE THREAD

**Issue by jitendragupta2** [sipsorcery/sipsorcery#316]
how can we end the music file ? as i receive dtmf code and send different audio response. but between the gap of dtmf code coming and previous respond completing the initial music goes on playing which is wrong

**Comment by jitendragupta2** [comment]
initial music file should play once. as i am creating IVR the welcome music should be played once

**Comment by sipsorcery** [comment]
Feel free to submit PR's for anything you'd like to see improved!!

`AudioExtrasSource.SetSource(AudioSourceOptions.None)`

**Comment by jitendragupta2** [comment]
also, is there any way we can use .wav file for initial music? actually i am using text to speech and dynamically using the audio file. can we use AudioExtrasSource.sendaudiostream for initial music?

**Comment by sipsorcery** [comment]
> also, is there any way we can use .wav file for initial music?

Not directly. As mentioned previously you need to convert any sound files you want to play to PCM. Take a look at NAudio, should be straight forward for you to either read PCM samples from the `.wav` file or strip out the header and save the raw samples to file.

There is an example of using the Azure Text-to-Speech service to get PCM samples [TextToPcm](https://github.com/sipsorcery/sipsorcery/tree/master/examples/AzureExamples/TextToPcm) maybe that will help you.

**Comment by jitendragupta2** [comment]
Thanks !!  will implement and let you know.

**Comment by jitendragupta2** [comment]
Thanks ! i need one last help... it is regarding sending dtmf tone. i used your softphone example from where i am sending # but i am getting 11 as event id. if i use sipuseragnet i send 0x0023 then i get "#". how should i hand from sending from softphone. it receives as 11 in event id
