### ISSUE TITLE
ScreenShare with WebRTC

### ISSUE THREAD

**Issue by jsantos98** [sipsorcery/sipsorcery#320]
Hello,

Any example about how to share the screen?
Capturing the screen image is not the problem in either windows or linux, but I'm not understanding how to send the frames using this lib.

I was able to have a working example using https://github.com/jatecl/WebrtcSharp, but that lib is not native (depends on a c++ dll) and I'm looking for something cross platform (.net core).

Any pointers?

Thanks

**Comment by sipsorcery** [comment]
There is no screen capture capability in this library. I'm still working on audio and video capture devices.

If you are able to capture the screen frames with a different library then using this one to transport them should be feasible. The closest example would be the [WebRTCTestPatternServer](https://github.com/sipsorcery/sipsorcery/blob/master/examples/WebRTCExamples/WebRTCTestPatternServer/Program.cs). You would replace the `tesPatternSource` with the source used to generate the screen capture samples.

The key line is:

` testPatternSource.OnVideoSourceRawSample += videoEndPoint.ExternalVideoSourceRawSample;`

It wires up the raw samples from the `testPatternSource` to the input of a video encoding source.

**Comment by jsantos98** [comment]
Thanks! 
I'll try it later!

**Comment by jsantos98** [comment]
Hello sipsorcery,

It worked, however the quality is really bad :)
![image](https://user-images.githubusercontent.com/4644017/95392577-e3aef780-08f0-11eb-941c-26db75846f42.png)

I think the frames are being converted to mjpeg...
Is there any configuration/setting to improve this?

Regards
Joao

**Comment by sipsorcery** [comment]
It's impressive that it worked at all! I'd love to add an example if you're able to share your code.

As far as the image quality goes there is no mjpeg conversion on the webrtc side of things. The only codec options ar VP8/9 and H264/5 and of those the only one I've had time to wire up is VP8. 

Two things I'd suggest:

 - Make sure you've set your frame width and height to match your screen capture resolution (I'm pretty sure you must have already done this or you'd have even worse image problems),

 - Switch from the `SIPSorceryMedia.Windows` nuget package and use the [source](https://github.com/sipsorcery/SIPSorceryMedia.Windows) directly. You can then tweak the frame rate and [VP8 codec parameters](https://github.com/sipsorcery/SIPSorceryMedia.Windows/blob/master/src/codecs/Vp8Codec.cs) to improve the quality. To date I have spent next to no time fine tuning codec parameters.

**Comment by jsantos98** [comment]
I'm still trying to find out what may be compressing the frames...

And yes, I can share what I'm doing...
I have changed VideoTestPatternSource with:
`[DllImport("user32.dll")]
        private static extern IntPtr GetDC(IntPtr ptr);
        [DllImport("gdi32.dll")]
        private static extern int GetDeviceCaps(IntPtr hdc, int nIndex);
        [DllImport("user32.dll")]
        private static extern IntPtr ReleaseDC(IntPtr hWnd, IntPtr hDc);

        const int HORZRES = 118;
        const int VERTRES = 117;`

and changed the GenerateTestPattern method to:
`        private void GenerateTestPattern(object state)
        {
            lock (_sendTestPatternTimer)
            {
                if (!_isClosed && OnVideoSourceRawSample != null)
                {

                    IntPtr hdc = GetDC(IntPtr.Zero);
                    Size size = new Size();
                    size.Width = GetDeviceCaps(hdc, HORZRES);
                    size.Height = GetDeviceCaps(hdc, VERTRES);
                    ReleaseDC(IntPtr.Zero, hdc);

                    using (Bitmap stampedTestPattern = new Bitmap(size.Width, size.Height, PixelFormat.Format24bppRgb))
                    {
                        using (Graphics graphics = Graphics.FromImage(stampedTestPattern))
                        {
                            graphics.CopyFromScreen(0, 0, 0, 0, size);
                        }

                         // stampedTestPattern.Save(@"O:\Prototypes\WebRTC\sipsorcery-master\examples\WebRTCExamples\WebRTCTestPatternServer\temp.bmp");

                        // AddTimeStampAndLocation(stampedTestPattern, DateTime.UtcNow.ToString("dd MMM yyyy HH:mm:ss:fff"), "Test Pattern 2.0");

                        // This event handler could get removed while the timestamp text is being added.
                        OnVideoSourceRawSample?.Invoke(
                            (uint)_frameSpacing,
                            size.Width,
                            size.Height,
                            BitmapToBGR24(stampedTestPattern as Bitmap),
                            VideoPixelFormatsEnum.Bgr);
                    }
                }
            }
        }
`

Of course this is still very rough and restricted to windows, but it is still a work in progress!

Regards

**Comment by jsantos98** [comment]
The quality problem is without doubt in the Vp8Codec encode method...
It is compressing my original image from 6912KB into just 40KB...

I'm messing around with the settings and managed to get an increase of quality (around 75KB per frame, setting every frame as key), but still, very far from acceptable quality...

Running the other tests, I'm also getting overall bad quality/low bitrate.

Am I the only one having this issues?

**Comment by sipsorcery** [comment]
You're the first person I've ever heard of using this library to attempt screen sharing.

For screensharing the requirements are a bit different to a "talking head" stream. For the "talking head" low latency is critical. For screen sharing I guess the frame rate can be reduced and the image quality is more important than low latency.

A good place to start to identify appropriate parameters is the Chromium source. I haven't looked for the codec parameters that get set for screensharing but this is the link I used for standard streams https://chromium.googlesource.com/external/webrtc/stable/src/+/refs/heads/master/modules/video_coding/codecs/vp8/vp8_impl.cc.

**Comment by jsantos98** [comment]
Thanks for the pointers!

I'll try to make it work...

**Comment by sipsorcery** [comment]
Yet another option is you could try an H264 codec by switching [SIPSorceryMedia.Encoders](https://github.com/sipsorcery/SIPSorceryMedia.Encoders) to [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery/SIPSorceryMedia.FFmpeg).

In your app all you should need to do is switch from [VideoEncoderEndPoint](https://github.com/sipsorcery/SIPSorceryMedia.Encoders/blob/master/src/VideoEncoderEndPoint.cs) to [FFmpegVideoEndPoint](https://github.com/sipsorcery/SIPSorceryMedia.FFmpeg/blob/master/src/FFmpegVideoEndPoint.cs). It will give you both VP8 and H264 codec options. `FFmpeg` does abstract away some details and it might be trickier to fine tune more specific codec parameters.

**Comment by jsantos98** [comment]
Hello sipsorcery,

Your hint worked, but I had to remove the vp8 from the capability list!
Now the image is quite clear, although a bit laggy...

![image](https://user-images.githubusercontent.com/4644017/95518553-394fd680-09bb-11eb-8d89-d8e0636cb776.png)

Thanks for the help!

Regarding my code (ScreenShareSource), the changes were basically the ones I mentioned some posts ago. 
Fell free to create an example with it!

**Comment by sipsorcery** [comment]
Great, glad it worked.

Note you can do the codec restriction with `RestrictCodecs`.

`videoEndPoint.RestrictCodecs(new List<VideoCodecsEnum> { VideoCodecsEnum.H264 });`

**Comment by peteryang023** [comment]
@sipsorcery I have the same requirement that to share screen, has it already implemented the functionality natively?

**Comment by sipsorcery** [comment]
@peteryang023 no, no new functionality has been added for screen sharing since this issue was created. The recommended approach is the same one suggested above: use another library or API to do the screen capturing and then feed the raw images into the sipsorcery library for transmission.

**Comment by peteryang023** [comment]
@sipsorcery thanks for the reply. I implemented it with the way above, but I met some issues that hope you can help me out of it. 
1. The color of the image encoded by H264 changed as the image shows below:
![image](https://user-images.githubusercontent.com/16588029/130350351-58c30240-0939-4754-b736-402ebc0fa27f.png)
2. About 10s latency when displaying the screenshot by the page, attached [webrtc.zip](https://github.com/sipsorcery-org/sipsorcery/files/7027011/webrtc.zip) is the HTML page from the sample and attached [WpfApp6.zip](https://github.com/sipsorcery-org/sipsorcery/files/7027023/WpfApp6.zip) is .NET application.

Looking forward to your reply.

**Comment by sipsorcery** [comment]
> The color of the image encoded by H264 changed as the image shows below:

When you're converting your bitmap to a byte array switch the red and blue array elements. Some of the Windows API's return RGB when they are in fact BGR.

> About 10s latency when displaying the screenshot by the page, attached webrtc.zip is the HTML page from the sample and attached WpfApp6.zip is .NET application.

It's tricky to get good performance with large byte arrays moving across managed and unmanaged boundaries, i.e C# to/from C/Win32/C++. I've mentioned a similar constraint in #384. What I'd recommend is reducing the frame rate and/or the frame size and then gradually increasing them until the performance is too poor. Note that getting the data across the network is normally not a problem. It's the video encoding pipeline that is typically the bottleneck.

You could go further and write a C++ library that does the screen capture and encoding. That would perform a lot better. That's a lot more work and the code would be different for each OS.

**Comment by peteryang023** [comment]
@sipsorcery thanks for the reply. I'll try that later.

**Comment by peteryang023** [comment]
@sipsorcery An update of today:
I tested with the Encoder, through absolutely it has the worse performance than the C++ native invoking, but I think it is not the case for the latency I met, I debugged with the source code and found it sends the packet, but the HTML doesn't render the until after about 10s, any ideas?

**Comment by peteryang023** [comment]
@sipsorcery , just an update: I fixed the latency issue by adding tune -> "zerolatency". The code like below shows:
`ffmpeg.av_opt_set(_encoderContext->priv_data, "tune", "zerolatency", 0).ThrowExceptionIfError();`
or pass the options from constructor.

**Comment by sipsorcery** [comment]
Thanks, I've added that line into the `FFmpegVideoEncoder` initialisation.

**Comment by forlayo** [comment]
I am needing to do exactly this ( screenshare with sipsorcery through webrtc ). Is the result of this conversation added to any sample of code I could check.

Thanks in advance! :)
