### ISSUE TITLE
Can I use sipsorcery as Turn/Stun server

### ISSUE THREAD

**Issue by Varooneh** [sipsorcery/sipsorcery#322]
Hi,

Can I use this library as turn stun server?

Thank you/

**Comment by sipsorcery** [comment]
In theory you can use it as a very basic STUN server, see this [example](https://github.com/sipsorcery/sipsorcery/blob/master/examples/StunServer/Program.cs). There are no TURN server features in the library.

TBH though I don't know why you would want to write a TURN server from scratch. There are already lots of good ones available, such as [coturn](https://github.com/coturn/coturn), and unlike other parts of the VoIP/WebRTC stack there aren't many application functions/features that can be added to TURN.

**Comment by Varooneh** [comment]
Thank you, I don't want write turn or stun server, now, I used coturn and it's worked, I searched for other turn stun server and compare with coturn features.
