### ISSUE TITLE
call a Microsoft Teams User?

### ISSUE THREAD

**Issue by chenxing105** [sipsorcery/sipsorcery#323]
Hello, Is that possible to use libraries to make a videocall to MS Teams user who will pick up a call on Teams desktop client?
Thanks!

**Comment by sipsorcery** [comment]
The short answer is no, you will not be able to use this library to call a Teams user. Teams does not support any well known signalling protocol such as SIP or XMPP.

The longer answer is that it is possible to wrangle a call to a Team's user using a Calling Bot and [Microsoft's Graph API](https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=http). Whether you should attempt to do so depends on your pain threshold and how badly you need to do it.

**Comment by sipsorcery** [comment]
See also https://github.com/Azure/Communication/issues/37.

**Comment by chenxing105** [comment]
I see just now on Azure communication service roadmap, 

> "Soon, integrate into existing on-premises equipment and carrier networks with SIP."

seem like we have to wait for this one.

**Comment by sipsorcery** [comment]
I wouldn't get your hopes up. Teams can already integrate with a list of approved SIP PBX's and you can purchase DIDs and place calls from Microsoft at 10x the normal cost. I wouldn't count on them jumping off that gravy train until forced to by the competition.

**Comment by chenxing105** [comment]
You are right.  😀 and Graph API solution is also difficult way for me to go but gotta try again this time.
