### ISSUE TITLE
Enhance audio pipeline for L8 and L16 16KHz pass thru

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/sipsorcery#326]
Originally from #324.

> I am not using 722.
> I am using L16 to communicate with Asterisk
> https://www.ietf.org/rfc/rfc3551.html#section-4.5.11
> Because bandwith is not an issue in my case, and I would like to avoid additional re-encoding from whatever codec is used to communicate with cellphone.
> 
> ` var audio_session = new NoDeviceAudioEndpoint( new L16Encoder( ) ); //No audio devices, custom encoder
> var rtp_session = new VoIPMediaSession( audio_session.ToMediaEndPoints( ) );
> 
> var offer_sdp = rtp_session.CreateOffer( null );
> 
> offer_sdp.Media.First( ).MediaFormats.Clear( );
> offer_sdp.Media.First( ).MediaFormats.Add( new SDPMediaFormat( 118, "L16", 16000 ) ); //Setting media format to L16 16 kHz
> 
> [skip]
> 
> rtp_session.AudioExtrasSource.SendAudioFromStream( new FileStream( @"g:\hellowelcome16k.raw", FileMode.Open ),
> AudioSamplingRatesEnum.Rate16KHz );
> `
> 
> Here's the link to the capture file made without the fix.
> 
> Packets from 13.2 (Asterisk) have timestamp increment of 320, captured audio is ok.
> Packets from 1.146 (SIP Client) have timestamp increment of 640, audio is distorted.

This enhancement is to enhance the audio pipeline to deal with L8 and L16 raw audio sample pass thru.

**Comment by Al-Dyachkov** [comment]
I can contribute to this issue, since I am already working with L16.

**Comment by sipsorcery** [comment]
I've been working on adding `L8` and `L16` support to the audio extras source. It's still a work in progress and I'm doing something wrong with the encoding. I'll work on it again tomorrow.

If you want to take a look it's on the `l16` branch and you'll also need the same named branch from [SIPSorceryMedia.Abstractions](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions).

I've testing with the SIPExamples/PlaySounds` example and it's wired up to use the new `L16` codec on that `l16` branch.

**Comment by sipsorcery** [comment]
The L16 audio stream was working for me. It seems it's my Asterisk server that isn't set up correctly.

I've also taken out L8 as an option. Nowhere else in the library uses 8 bit samples.

I've got a bit more tidying up to do and then this feature should be good to go for L16 @ 8 and 16KHz.

**Comment by Al-Dyachkov** [comment]
It has same issue I've adressed in #324 -- when playing 16 bir audio audio using SendAudioFromStream timestamp is incremented in twice actual sample count, by 640. No matter what codec class is used, built-in or custom, timestamp should reflect sample count, not byte count.

**Comment by sipsorcery** [comment]
Yep, note the `work in progress` mention.

If you got any kind of sound output that's all I was checking for. I'm sorting out the sampling rates at the moment.

**Comment by Al-Dyachkov** [comment]
Encoding and decoding works.
Cell phone->Asterisk->Sip Client Recording works fine, recorded audio is OK.

**Comment by sipsorcery** [comment]
`l16` branch is ready for testing now. Audio resampling is all wired up. Should work fine for both 8k and 16k.

**Comment by Al-Dyachkov** [comment]
I've tested `sdprefactor` branch, both sending media and receiving&recording are working.

**Comment by sipsorcery** [comment]
The L16 format is now supported in the latest nuget packages. It's available directly in the `AudioExtraSource` class and you can force it's use on any AudioEndPoint that uses the AudioEncoder using:

````csharp
var voipMediaSession = new VoIPMediaSession(windowsAudio.ToMediaEndPoints());
voipMediaSession.AudioLocalTrack.Capabilities.Clear();
voipMediaSession.AudioLocalTrack.Capabilities.Add(
    new SDPAudioVideoMediaFormat(new AudioFormat(AudioCodecsEnum.L16, 118, 8000)));
````

See it [here](https://github.com/sipsorcery/sipsorcery/blob/e047464c85cf6c9acc1f8336664355b6b7f90f93/examples/SIPExamples/PlaySounds/Program.cs#L70).

I ended up doing a fairly substantial refactor around the audio/video formats and SDP mappings that was related to this. I've tested L16 @ 8KHz and 16KHz and they are working correctly.

**Comment by sipsorcery** [comment]
Feel free to re-open if there are any problems.
