### ISSUE TITLE
Any way of detecting silence?

### ISSUE THREAD

**Issue by cristianmad** [sipsorcery/sipsorcery#327]
Hi, 

Let me start by saying that this is a very powerful library that I have been using in a number of small projects in the past. Thank you for all the work you put into it!

I'm currently looking at a solution involving an IVR (Interactive Voice Response) system. Basically I'm trying to implement a basic conversation between a person and the IVR.
I'm using the RTPSession class directly (Not the Voip/SIP or WebRTC implementations).
From a communication point of view, everything is working as expected. 

The problem I'm trying to solve is this: I need to know when to send what the person said to the IVR. Basically I want to acumulate the RTP package's payload while the person is talking and then, once they stop, send everything to the IVR.
I do not know what would be the recommended way of detecting when the person stopped talking.

One (very basic) way I was thinking of doing it was to inspect the RTP package's payload and see when identical packages are being received for a certain amount of time (ex. 3 sec). I know this is far from ideal and it would not account for background noise, however, is there a better way of achieving this?

Btw, I'm using G.711 mu-law if it makes any difference.

Thank you!

**Comment by sipsorcery** [comment]
Take my advice with a grain of salt as I've never looked at silence detection. 

Your idea of checking for identical RTP payloads would work if the remote party was explicitly sending silence payloads. For `PCMU` that's defined as `0x7F 0xFF` so would be easy to do. But if it's a person speaking you're not likely to ever get nice clean silence from a microphone.

A better approach would be to convert the `PCMU` to `PCM`, which is a very [simple decode step](https://github.com/sipsorcery/sipsorcery/blob/e8b6fd9bbba363d6089edb16c9cfca34bae9498f/src/app/Media/Codecs/G711Codecs.cs#L247), and get your signals in the range -32768 to 32767 (`short.MinValue` to `short.MaxValue`). The value of a PCM sample represents audio amplitude so values close to 0 represent silence. You could set some minimum threshold and then if it doesn't get exceeded for a second or so interpret it as a the person stopping talking.

**Comment by cristianmad** [comment]
Hi Aaron, 

That it perfect! I just did quick test and it seems to work very well for my use case!

Thank you very much,
Cristian
