### ISSUE TITLE
WebRTC to SIP audio/video communication

### ISSUE THREAD

**Issue by jafarulla15** [sipsorcery/sipsorcery#328]
I found SIP to WebRTC but not WebRTC to SIP. Is there any way to develop that

**Comment by sipsorcery** [comment]
The [SIPToWebRtcBridge](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/SIPToWebRtcBridge) example acts as a two way bridge in that the session can be initiated from either SIP or WebRTC. Note I've just simplified that example so it should be a lot clearer now.

The audio flow is only one way from SIP to the WebRTC peer. Is that what you mean? You're looking for two way audio?

**Comment by jafarulla15** [comment]
Sorry for late response. Yes, you are right.  I am concern of getting audio from WebRTC and send to SIP. I didn't find any code for sending to SIP. Your project is great, working fine. Feeling missing of it.

**Comment by gastu1** [comment]
I'm interested in that too

**Comment by sipsorcery** [comment]
I added the extra event handler and browser microphone capture. The example does two way audio now.

**Comment by jafarulla15** [comment]
It's working fine. Thanks a lot. You save me. Great work.
