### ISSUE TITLE
DtlsHandshake not working

### ISSUE THREAD

**Issue by gastu1** [sipsorcery/sipsorcery#330]
when is use this constructor 
`new RTCCertificate {
         X_CertificatePath = DTLS_CERTIFICATE_PATH,
         X_KeyPath = DTLS_KEY_PATH,
         X_Fingerprint = DTLS_CERTIFICATE_FINGERPRINT
}`
in 4.0.55-pre version dtls working, but in version 4.0.67-pre with constructor
` var crt = new RTCCertificate() {
       Certificate = ...
};`

**Comment by sipsorcery** [comment]
OS? Error message? You'll need to be on the latest nuget package for any fixes.

**Comment by gastu1** [comment]
OS: Woindows 10, b 1703. No errors, but DoHandshakeAsServer return -1 and IsHandshakeComplete return false.

**Comment by sipsorcery** [comment]
OK I'll take a look. I would recommend trying with the latest nuget package `v4.0.85-pre` to make sure you get some [recent work](https://github.com/sipsorcery/sipsorcery/commit/e180a1205ab922066372fd3c5986ae0a082dc8c6) that was done on improving the `pfx` loading in the [DtlsUtils class](https://github.com/sipsorcery/sipsorcery/blob/master/src/net/DtlsSrtp/DtlsUtils.cs).

Loading `pfx` files with .NET/Core turns out to be a real pain due to different support on different OS (even though it's just reading from a file) and a recent change made on .NET Core. Here are some of the notes I made while working on the above commit.

````csharp
// Summary:
// .NET Framework (including Mono on Linux, macOS and WSL)
//  - Set x509.PrivateKey works.
// .NET Standard:
//  - Set x509.PrivateKey for a .NET Framework application.
//  - Set x509.PrivateKey for a .NET Core application FAILS.
// .NET Core:
//  - Set x509.PrivateKey for a .NET Core application FAILS.
//  - PFX serialisation works on Windows.
//  - PFX serialisation works on WSL and Linux.
//  - PFX serialisation FAILS on macOS.
//
// For same issue see https://github.com/dotnet/runtime/issues/23635.
// For fix in net5 see https://github.com/dotnet/corefx/pull/42226.
````

**Comment by sipsorcery** [comment]
Does it work if you load your certificate like this?

````csharp
X509Certificate2 cert = new X509Certificate2("localhost.pfx", "", X509KeyStorageFlags.Exportable);
````

**Comment by gastu1** [comment]
I try it tomorrow with new version, I use this flag at last time, with 85 pre

**Comment by gastu1** [comment]
![image](https://user-images.githubusercontent.com/71744944/97260149-91555c80-1846-11eb-96b0-892412db4bbc.png)
![image](https://user-images.githubusercontent.com/71744944/97260173-9c0ff180-1846-11eb-9e8c-8b3d251ddb2b.png)
![image](https://user-images.githubusercontent.com/71744944/97260198-a8944a00-1846-11eb-8fea-b39102f2005f.png)
![image](https://user-images.githubusercontent.com/71744944/97260222-b4800c00-1846-11eb-89ca-2b4b8e90d8cc.png)

`//-----------------------------------------------------------------------------
// Filename: Program.cs
//
// Description: A sample program to interop with the sip.js
// javascript SIP library, see https://sipjs.com/.
//
//
// Author(s):
// Aaron Clauson (aaron@sipsorcery.com)
//
// History:
// 13 Jun 2020	Aaron Clauson	Created, Dublin, Ireland.
//
// License: 
// BSD 3-Clause "New" or "Revised" License, see included LICENSE.md file.
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Serilog;
using Serilog.Sinks.SystemConsole.Themes;
using SIPSorcery.Net;
using SIPSorcery.SIP;
using SIPSorcery.SIP.App;
using SIPSorceryMedia;
using SIPSorceryMedia.Abstractions.V1;

namespace demo {
    class Program {
        private const string DTLS_CERTIFICATE_PATH = "certs/localhost_key.pem";
        private const string DTLS_KEY_PATH = "certs/localhost.pem";
        private const string DTLS_CERTIFICATE_FINGERPRINT = "sha-256 24:89:24:71:E2:65:17:2A:6C:EC:F8:21:0B:6D:7B:BC:78:FD:72:1A:76:78:D3:D8:31:9A:F9:88:CF:87:B4:E2";

        private static SIPEndPoint OUTBOUND_PROXY = SIPEndPoint.ParseSIPEndPoint("udp:10.10.21.137:5060");
        private static Microsoft.Extensions.Logging.ILogger Log = SIPSorcery.LogFactory.CreateLogger<Program>();

        static async Task Main() {
            Console.WriteLine("SIPSorcery sip.js Demo");

            AddConsoleLogger();

            var sipTransport = new SIPTransport();
            EnableTraceLogs(sipTransport);

            var sipChannel = new SIPWebSocketChannel(IPAddress.Loopback, 80);

            var wssCertificate = new System.Security.Cryptography.X509Certificates.X509Certificate2("certs/localhost.pfx");
            var rtcCertificate = new System.Security.Cryptography.X509Certificates.X509Certificate2("certs/localhost.pfx", string.Empty, X509KeyStorageFlags.Exportable);
            var sipChannelSecure = new SIPWebSocketChannel(IPAddress.Loopback, 443, wssCertificate);

            sipTransport.AddSIPChannel(sipChannel);
            sipTransport.AddSIPChannel(sipChannelSecure);

            var userAgent = new SIPUserAgent(sipTransport, OUTBOUND_PROXY, true);
            userAgent.OnIncomingCall += async (ua, req) => {
                Log.LogDebug($"Auto-answering incoming call from {req.Header.From}.");
                var uas = userAgent.AcceptCall(req);

                RTCConfiguration pcConfiguration = new RTCConfiguration {
                    certificates = new List<RTCCertificate>
                {
                    new RTCCertificate {
                        Certificate = rtcCertificate
                    }
                },
                    //X_RemoteSignallingAddress = context.UserEndPoint.Address,
                    //iceServers = new List<RTCIceServer> { new RTCIceServer { urls = SIPSORCERY_STUN_SERVER } }
                };

                var peerConnection = new RTCPeerConnection(pcConfiguration);
                var dtls = new DtlsHandshake(DTLS_CERTIFICATE_PATH, DTLS_KEY_PATH);

                peerConnection.OnTimeout += (mediaType) => {
                    peerConnection.Close("remote timeout");
                };

                peerConnection.oniceconnectionstatechange += async (state) => {
                    Log.LogDebug($"ICE connection state change to {state}.");

                    if (state == RTCIceConnectionState.connected) {
                        var remoteEndPoint = peerConnection.AudioDestinationEndPoint;
                        Log.LogInformation($"ICE connected to remote end point {remoteEndPoint}.");

                        await Task.Run(() => DoDtlsHandshake(peerConnection, dtls))
                        .ContinueWith((dtlsResult) => {
                            Log.LogDebug($"dtls handshake result {dtlsResult.Result}.");

                            if (dtlsResult.Result) {
                                var remoteEP = peerConnection.AudioDestinationEndPoint;
                                peerConnection.SetDestination(SDPMediaTypesEnum.audio, remoteEP, remoteEP);
                            } else {
                                dtls.Shutdown();
                                peerConnection.Close("dtls handshake failed.");
                            }
                        });
                    }
                };

                peerConnection.onconnectionstatechange += (state) => {
                    if (state == RTCPeerConnectionState.connected) {
                        var remoteEP = peerConnection.AudioDestinationEndPoint;

                        Log.LogDebug($"DTLS connected on {remoteEP}.");

                        peerConnection.SetDestination(SDPMediaTypesEnum.audio, remoteEP, remoteEP);
                        peerConnection.SetDestination(SDPMediaTypesEnum.video, remoteEP, remoteEP);

                        peerConnection.OnReceiveReport += RtpSession_OnReceiveReport;
                        peerConnection.OnSendReport += RtpSession_OnSendReport;
                        // peerConnection.OnRtpPacketReceived += OnRtpPacketReceived;
                    }
                };

                MediaStreamTrack audioTrack = new MediaStreamTrack(SDPMediaTypesEnum.audio, false, new List<SDPAudioVideoMediaFormat> { new SDPAudioVideoMediaFormat(new AudioFormat(SDPWellKnownMediaFormatsEnum.PCMU)) }, MediaStreamStatusEnum.SendRecv);
                peerConnection.addTrack(audioTrack);
                //MediaStreamTrack videoTrack = new MediaStreamTrack("1", SDPMediaTypesEnum.video, false, new List<SDPMediaFormat> { new SDPMediaFormat(SDPMediaFormatsEnum.VP8) }, MediaStreamStatusEnum.Inactive);
                //peerConnection.addTrack(videoTrack);

                var answerResult = await userAgent.Answer(uas, peerConnection);
            };

            Console.Write("press any key to exit...");
            Console.Read();

            sipTransport.Shutdown();
        }

        private static void OnRtpPacketReceived(SDPMediaTypesEnum media, RTPPacket pkt) {
            Log.LogDebug($"RTP {media} packet received, ssrc {pkt.Header.SyncSource}, seqnum {pkt.Header.SequenceNumber}, timestamp {pkt.Header.Timestamp}.");
        }

        /// <summary>
        /// Hands the socket handle to the DTLS context and waits for the handshake to complete.
        /// </summary>
        /// <param name="webRtcSession">The WebRTC session to perform the DTLS handshake on.</param>
        private static bool DoDtlsHandshake(RTCPeerConnection peerConnection, DtlsHandshake dtls) {
            Log.LogDebug("DoDtlsHandshake started.");

            if (!File.Exists(DTLS_CERTIFICATE_PATH)) {
                throw new ApplicationException($"The DTLS certificate file could not be found at {DTLS_CERTIFICATE_PATH}.");
            } else if (!File.Exists(DTLS_KEY_PATH)) {
                throw new ApplicationException($"The DTLS key file could not be found at {DTLS_KEY_PATH}.");
            }

            byte[] clientFingerprint = null;
            var dtlsResult = dtls.DoHandshakeAsServer((ulong)peerConnection.GetRtpChannel(SDPMediaTypesEnum.audio).RtpSocket.Handle, ref clientFingerprint);

            Log.LogDebug($"DtlsContext initialisation result {dtlsResult}.");

            if (dtls.IsHandshakeComplete()) {
                Log.LogDebug("DTLS negotiation complete.");

                var srtpSendContext = new Srtp(dtls, false);
                var srtpReceiveContext = new Srtp(dtls, true);

                peerConnection.SetSecurityContext(
                    srtpSendContext.ProtectRTP,
                    srtpReceiveContext.UnprotectRTP,
                    srtpSendContext.ProtectRTCP,
                    srtpReceiveContext.UnprotectRTCP);

                return true;
            } else {
                Log.LogWarning("DTLS handshake failed.");

                dtls.Shutdown();
                return false;
            }
        }

        /// <summary>
        /// Diagnostic handler to print out our RTCP sender/receiver reports.
        /// </summary>
        private static void RtpSession_OnSendReport(SDPMediaTypesEnum mediaType, RTCPCompoundPacket sentRtcpReport) {
            if (sentRtcpReport.Bye != null) {
                Log.LogDebug($"RTCP sent BYE {mediaType}.");
            } else if (sentRtcpReport.SenderReport != null) {
                var sr = sentRtcpReport.SenderReport;
                Log.LogDebug($"RTCP sent SR {mediaType}, ssrc {sr.SSRC}, pkts {sr.PacketCount}, bytes {sr.OctetCount}.");
            } else {
                if (sentRtcpReport.ReceiverReport.ReceptionReports?.Count > 0) {
                    var rrSample = sentRtcpReport.ReceiverReport.ReceptionReports.First();
                    Log.LogDebug($"RTCP sent RR {mediaType}, ssrc {rrSample.SSRC}, seqnum {rrSample.ExtendedHighestSequenceNumber}.");
                } else {
                    Log.LogDebug($"RTCP sent RR {mediaType}, no packets sent or received.");
                }
            }
        }

        /// <summary>
        /// Diagnostic handler to print out our RTCP reports from the remote WebRTC peer.
        /// </summary>
        private static void RtpSession_OnReceiveReport(IPEndPoint ep, SDPMediaTypesEnum mediaType, RTCPCompoundPacket recvRtcpReport) {
            if (recvRtcpReport.Bye != null) {
                Log.LogDebug($"RTCP recv BYE {mediaType}.");
            } else {
                var rr = recvRtcpReport.ReceiverReport?.ReceptionReports?.FirstOrDefault();
                if (rr != null) {
                    Log.LogDebug($"RTCP {mediaType} Receiver Report: SSRC {rr.SSRC}, pkts lost {rr.PacketsLost}, delay since SR {rr.DelaySinceLastSenderReport}.");
                } else {
                    Log.LogDebug($"RTCP {mediaType} Receiver Report: empty.");
                }
            }
        }

        /// <summary>
        /// Enable detailed SIP log messages.
        /// </summary>
        private static void EnableTraceLogs(SIPTransport sipTransport) {
            // Logging configuration. Can be omitted if internal SIPSorcery debug and warning messages are not required.
            var loggerFactory = new Microsoft.Extensions.Logging.LoggerFactory();
            var loggerConfig = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Is(Serilog.Events.LogEventLevel.Debug)
                .WriteTo.Console()
                .CreateLogger();
            loggerFactory.AddSerilog(loggerConfig);
            SIPSorcery.LogFactory.Set(loggerFactory);

            sipTransport.SIPRequestInTraceEvent += (localEP, remoteEP, req) => {
                Log.LogDebug($"Request received: {localEP}<-{remoteEP}");
                Log.LogDebug(req.ToString());
            };

            sipTransport.SIPRequestOutTraceEvent += (localEP, remoteEP, req) => {
                Log.LogDebug($"Request sent: {localEP}->{remoteEP}");
                Log.LogDebug(req.ToString());
            };

            sipTransport.SIPResponseInTraceEvent += (localEP, remoteEP, resp) => {
                Log.LogDebug($"Response received: {localEP}<-{remoteEP}");
                Log.LogDebug(resp.ToString());
            };

            sipTransport.SIPResponseOutTraceEvent += (localEP, remoteEP, resp) => {
                Log.LogDebug($"Response sent: {localEP}->{remoteEP}");
                Log.LogDebug(resp.ToString());
            };

            sipTransport.SIPRequestRetransmitTraceEvent += (tx, req, count) => {
                Log.LogDebug($"Request retransmit {count} for request {req.StatusLine}, initial transmit {DateTime.Now.Subtract(tx.InitialTransmit).TotalSeconds.ToString("0.###")}s ago.");
            };

            sipTransport.SIPResponseRetransmitTraceEvent += (tx, resp, count) => {
                Log.LogDebug($"Response retransmit {count} for response {resp.ShortDescription}, initial transmit {DateTime.Now.Subtract(tx.InitialTransmit).TotalSeconds.ToString("0.###")}s ago.");
            };
        }

        /// <summary>
        ///  Adds a console logger. Can be omitted if internal SIPSorcery debug and warning messages are not required.
        /// </summary>
        private static void AddConsoleLogger() {
            var loggerFactory = new Microsoft.Extensions.Logging.LoggerFactory();
            var loggerConfig = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Is(Serilog.Events.LogEventLevel.Debug)
                .WriteTo.Console(theme: AnsiConsoleTheme.Code)
                .CreateLogger();
            loggerFactory.AddSerilog(loggerConfig);
            SIPSorcery.LogFactory.Set(loggerFactory);
        }
    }
}`

**Comment by sipsorcery** [comment]
The DTLS code has changed substantially since the version of the example you are running. Please checkout the latest [sipjs example code](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/sipjs) (updated 4 days ago) and try with that.

**Comment by gastu1** [comment]
Yes, without tls its work. Thanks

**Comment by rafcsoares** [comment]
Just to complement this issue.

the DtlsStrpTransport contains some bugs related to chrome.

To fix it just replace Receive method to function below.

1) The hardcoded WaitMillis of bouncy castle is setted to initial time begin with 1000ms, this time is too long when trying to connect with chrome in local network, so we must correct this value.
2) Some cases of Receive was not sending -1. The function below correct this behaviour to fix retransmition logic of Handshake in BouncyCastle

```
private static readonly Random random = new Random();
public int Receive(byte[] buf, int off, int len, int waitMillis)
        {
            if (!handshakeComplete)
            {
                // The timeout for the handshake applies from when it started rather than
                // for each individual receive..
                int millisecondsRemaining = GetMillisecondsRemaining();

                //Handshake reliable contains too long default backoff times
                waitMillis = System.Math.Max(100, waitMillis / (random.Next(100, 1000)));

                if (millisecondsRemaining <= 0)
                {
                    logger.LogWarning($"DTLS transport timed out after {TimeoutMilliseconds}ms waiting for handshake from remote {(connection.IsClient() ? "server" : "client")}.");
                    throw new TimeoutException();
                }
                else if (!_isClosed)
                {
                    waitMillis = (int)System.Math.Min(waitMillis, millisecondsRemaining);
                    return Read(buf, off, len, waitMillis);
                }
                else
                {
                    return DTLS_RECEIVE_ERROR_CODE;
                }
            }
            else if (!_isClosed)
            {
                return Read(buf, off, len, waitMillis);
            }
            else
            {
                return DTLS_RECEIVE_ERROR_CODE;
            }
        }
```

Best Regards
Rafael

**Comment by sipsorcery** [comment]
@rafcsoares thanks for the fix. I've added it to [master](https://github.com/sipsorcery/sipsorcery/pull/335).
