### ISSUE TITLE
Print content of ConsoleLogger into an UI element such as TextBox?

### ISSUE THREAD

**Issue by dibstah** [sipsorcery/sipsorcery#331]
Is it possible to print the content of the ConsoleLogger to a TextBox or something similar?

Thanks in advance!

**Comment by sipsorcery** [comment]
Yes it's possible. This library is using the [Microsoft Logging interface](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1). Unfortunately Microsoft's documentation in this case is very poor and assumes the only use case is ASP.NET. As an alternative you could try search for relevant entries against one of the logging providers, e.g. [Serilog](https://stackoverflow.com/questions/35567814/is-it-possible-to-display-serilog-log-in-the-programs-gui).

The closest case in the examples is for one of the mobile demos, see [here](https://github.com/sipsorcery/sipsorcery/blob/cb12149ab4d5516656b88c381308a7fb2e681222/examples/SIPExamples/AndroidSIPGetStarted/MainActivity.cs#L70).
