### ISSUE TITLE
How can i do webrtc to sip server (asterisk, freeswitch) proxy?

### ISSUE THREAD

**Issue by gastu1** [sipsorcery/sipsorcery#332]
I wanna create html client for sip server (asterisk, freeswitch) with sip.js or other. I saw example with sip.js, but it working as self sip server. Can i do proxy for sip.js?

**Comment by sipsorcery** [comment]
Unless I've misunderstood you don't need a library like sipsorcery for this. `sip.js` can work with Asterisk/FreeSWITCH directly, e.g. [Asterisk Installation and Configuration](https://sipjs.com/guides/server-configuration/asterisk/).

**Comment by gastu1** [comment]
Yes, i know it, thanks. But i use other product, wich not supported webrtc from cisco

**Comment by sipsorcery** [comment]
So what you want is?

WebRTC Browser <-> custom app <-> SIP Server (no WebRTC support)

If so that's exactly what the [SIPtoWebRtcBridge example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/SIPToWebRtcBridge) does.

If you want to enhance it further to:

WebRTC Browser with `sip.js` <-> custom app <-> SIP Server (no WebRTC support)

Then you need to combine the [SIPtoWebRtcBridge example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/SIPToWebRtcBridge) with the [sipjs example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/sipjs) (note I just fixed the `sipjs` example so it works with the latest sipsorcery nuget packages).

**Comment by gastu1** [comment]
Yes, thank you. Will try use bridge

**Comment by gastu1** [comment]
I have create application, like bridge. Audio works good, i can recieve and send from webrtc. But cant config video, it not work.

`
using SIPSorcery.Media;
    using SIPSorcery.Net;
    using SIPSorcery.SIP;
    using SIPSorcery.SIP.App;
    using SIPSorceryMedia.Abstractions.V1;
    using SIPSorceryMedia.Encoders;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using WebSocketSharp;
    using WebSocketSharp.Net.WebSockets;
    using WebSocketSharp.Server;

    namespace ConsoleApp1 {
        class Program {
            static SIPTransport sipTransport;

            static void Main(string[] args) {
                var _webSocketServer = new WebSocketServer(IPAddress.Any, 8080, false);
                //_webSocketServer.SslConfiguration.ServerCertificate = new X509Certificate2(WEBSOCKET_CERTIFICATE_PATH);
                //_webSocketServer.SslConfiguration.CheckCertificateRevocation = false;
                //_webSocketServer.Log.Level = WebSocketSharp.LogLevel.Debug;

                sipTransport = new SIPTransport();

                _webSocketServer.AddWebSocketService<SDPExchange>("/", (sdpExchanger) => {
                    sdpExchanger.SetSIPTransport(sipTransport);
                });
                _webSocketServer.Start();

                Console.ReadLine();
            }
        }


        public class SDPExchange : WebSocketBehavior {
            private SIPTransport _sipTransport;
            private SIPUserAgent _userAgent;
            RTCPeerConnection _peerConnection;

            public SDPExchange() { }

            protected override void OnMessage(MessageEventArgs e) {
                try {
                    _peerConnection
                        .setRemoteDescription(new RTCSessionDescriptionInit { type = RTCSdpType.answer, sdp = e.Data });
                } catch (Exception excp) {
                }
            }

            protected override void OnClose(CloseEventArgs e) {
                if (_userAgent != null && _userAgent.IsCallActive) {
                    _userAgent.Hangup();
                }
                base.OnClose(e);
            }

            protected override async void OnOpen() {
                base.OnOpen();

                _peerConnection = new RTCPeerConnection(null);

                var rtpSession = new RTPSession(false, false, false);
                rtpSession.AcceptRtpFromAny = true;

                Action<SDPMediaTypesEnum, RTPPacket, RTPSession> forwardMedia = (SDPMediaTypesEnum mediaType, RTPPacket rtpPacket, RTPSession dest) => {
                    if (mediaType == SDPMediaTypesEnum.audio) {
                        dest.SendAudio((uint)rtpPacket.Payload.Length, rtpPacket.Payload);
                    }
                    if (mediaType == SDPMediaTypesEnum.video) {
                        dest.SendVideo((uint)rtpPacket.Payload.Length, rtpPacket.Payload);
                    }
                };


                var videoEncoderEndPoint = new VideoEncoderEndPoint();
                videoEncoderEndPoint.GetVideoSourceFormats();

                _peerConnection.OnRtpPacketReceived +=
                    (IPEndPoint ep, SDPMediaTypesEnum mediaType, RTPPacket rtpPacket) => forwardMedia(mediaType, rtpPacket, rtpSession);

                rtpSession.OnRtpPacketReceived +=
                    (IPEndPoint ep, SDPMediaTypesEnum mediaType, RTPPacket rtpPacket) => forwardMedia(mediaType, rtpPacket, _peerConnection);

                _peerConnection.addTrack(peerAudioTrack);
                _peerConnection.addTrack(peerVideoTrack);

                rtpSession.addTrack(sipAaudioTrack);
                rtpSession.addTrack(sipVideoTrack);

                await _userAgent.Call("room1@192.168.0.100", "User", null, rtpSession);

                var offerInit = _peerConnection.createOffer(null);
                await _peerConnection.setLocalDescription(offerInit);
                Send(offerInit.sdp);
            }

            public void SetSIPTransport(SIPTransport sipTransport) {
                _sipTransport = sipTransport;
                _userAgent = new SIPUserAgent(sipTransport, null);
            }

            MediaStreamTrack peerAudioTrack = new MediaStreamTrack(SDPMediaTypesEnum.audio, false, new List<SDPAudioVideoMediaFormat>() {
                    new SDPAudioVideoMediaFormat(new AudioFormat(AudioCodecsEnum.OPUS, 96)),
                    new SDPAudioVideoMediaFormat(new AudioFormat(AudioCodecsEnum.G722, 97)),
                    new SDPAudioVideoMediaFormat(new AudioFormat(AudioCodecsEnum.PCMU, 98))
                }, MediaStreamStatusEnum.SendRecv);

            MediaStreamTrack sipAaudioTrack = new MediaStreamTrack(SDPMediaTypesEnum.audio, false, new List<SDPAudioVideoMediaFormat>() {
                    new SDPAudioVideoMediaFormat(new AudioFormat(AudioCodecsEnum.OPUS, 96)),
                    new SDPAudioVideoMediaFormat(new AudioFormat(AudioCodecsEnum.G722, 97)),
                    new SDPAudioVideoMediaFormat(new AudioFormat(AudioCodecsEnum.PCMU, 98))
                }, MediaStreamStatusEnum.SendRecv);

            MediaStreamTrack sipVideoTrack = new MediaStreamTrack(
                SDPMediaTypesEnum.video,
                false, new List<SDPAudioVideoMediaFormat>((new VideoEncoderEndPoint()).GetVideoSourceFormats().Select(x => new SDPAudioVideoMediaFormat(x))),
                MediaStreamStatusEnum.SendRecv);

            MediaStreamTrack peerVideoTrack = new MediaStreamTrack(
                SDPMediaTypesEnum.video,
                false, new List<SDPAudioVideoMediaFormat>((new VideoEncoderEndPoint()).GetVideoSourceFormats().Select(x => new SDPAudioVideoMediaFormat(x))),
                MediaStreamStatusEnum.SendRecv);
        }
    }`

**Comment by sipsorcery** [comment]
I've added a [new SIP-to-WebRTC example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/SIPToWebRtcBridgeVideo} that includes video. 

Note that I had some problems with getting the video streams to start between my browser and SIP softphone. The problem is related to key frames. Because the two end points cannot talk directly they cannot exchange RTCP feedback packets to request a key frame. The hack I put in to work around this is if you press the `k` key both ends are sent an RTCP feedback message requesting they generate a key frame. That fixed the problem in my case,

**Comment by gastu1** [comment]
I do like in example, but in my case it not working. I use cisco meeting sip server

**Comment by sipsorcery** [comment]
> I do like in example, but in my case it not working. I use cisco meeting sip server. some frames received but all dropped

I can't troubleshoot that set up for you. You'll need to narrow it down further. I'd suggest doing some Wireshark captures and checking the formats are correct etc.
