### ISSUE TITLE
Association closing connection after receive -1 from DtlsSrtpTransport

### ISSUE THREAD

**Issue by rafcsoares** [sipsorcery/sipsorcery#338]
Hello @sipsorcery ,

After investigate why my connection was so unstable when trying to communicate with peers on another network, and i figured out the problem.

In class **Association.cs** inside method **startRcv()** the DtlsSrtpTransport.DTLS_RECEIVE_ERROR_CODE breaks the loop and killed entire connection

```
else if (length == DtlsSrtpTransport.DTLS_RECEIVE_ERROR_CODE)
{
     // The DTLS transport has been closed or i no longer available.
     break;
 }
.
.
.
_transp.Close();
```
But the value of DtlsSrtpTransport.DTLS_RECEIVE_ERROR_CODE is -1 and in BouncyCastle TlsTransport, -1 means retransmission and not Error.

DtlsSrtpTransport.DTLS_RECEIVE_ERROR_CODE was sended by two methods inside DtlsSrtpTransport

* **public int Read(byte[] buffer, int offset, int count, int timeout)** when timeout was not enough to read a package (udp package lost)
* **public int Receive(byte[] buf, int off, int len, int waitMillis)** when _IsClosed == true.

I changed the value of DtlsSrtpTransport.DTLS_RECEIVE_ERROR_CODE to -2 and changed the "Read" to return -1 (DTLS_RETRANSMISSION_CODE)

This way the problem was solved and connection was stable again.

Above i attached the fix for the problem to apply in DtlsSrtpTransport.cs

```
//Changed from -1
public const int DTLS_RECEIVE_ERROR_CODE = -2;
//New const
public const int DTLS_RETRANSMISSION_CODE = -1;

public int Read(byte[] buffer, int offset, int count, int timeout)
        {
            try
            {
                if (_chunks.TryTake(out var item, timeout))
                {
                    Buffer.BlockCopy(item, 0, buffer, 0, item.Length);
                    return item.Length;
                }
            }
            catch (ObjectDisposedException) { }
            catch (ArgumentNullException) { }
            return DTLS_RETRANSMISSION_CODE;
        }
```

Best Regards
Rafael

**Comment by sipsorcery** [comment]
Thanks for the fix Rafael. I'll add it to `master`. 

Sorry about the bug it's not ideal that a problem with the SCTP association can close the whole connection. The SCTP logic does need to be tidied up a bit. It was originally ported from a Java library and didn't come across hat cleanly. It's on the list.
