### ISSUE TITLE
The lastest version is work without voice

### ISSUE THREAD

**Issue by Teastears** [sipsorcery/sipsorcery#341]
`
            var sipTransport = new SIPTransport();
            var userAgent = new SIPUserAgent(sipTransport, null);
            BindEvent(userAgent);
            var windowsAudioEndPoint = new WindowsAudioEndPoint(new AudioEncoder()); 

            MediaEndPoints mediaEndPoints = new MediaEndPoints
            {
                AudioSink = windowsAudioEndPoint,
                AudioSource = windowsAudioEndPoint,
            };

            var voipMediaSession = new VoIPMediaSession(mediaEndPoints);
            voipMediaSession.AcceptRtpFromAny = true;

            userAgent.Call("XXXX@XXXXX", "Port1", "", voipMediaSession);

            Console.ReadKey();
`

This is my code . It is on .net core 3.1
I use it to make a call from PC to a SIP Gateway. The SIP Gateway has some SIM ,
It can work  on SIPSorcery 4.0.67-pre and SIPSorceryMedia.Windows 0.0.15-pre
But I update SIPSorcery to 4.0.85 -pre  and SIPSorceryMedia.Windows to 0.0.24 -pre  today .Then it is breakdown.
The phone can be connected but no voice

**Comment by sipsorcery** [comment]
Can you use the [Get Started demo](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/GetStarted), change the destination and then post the console output to this issue.

**Comment by Teastears** [comment]
I has used the Get Started demo yesteday，It is same result. The phone can be connected but no voice.
But I don`t save the output.
I can retry it two days later.
Then I'll come here and reply to this issue.

**Comment by Teastears** [comment]
This is the console output while I use the Get Started demo with 4.0.86 -pre.
It is same result. The phone can be connected but no voice.

[ConsoleOutput.txt](https://github.com/sipsorcery/sipsorcery/files/5472306/ConsoleOutput.txt)

For privacy,I have replace my phone number ,PC IP and SIP Gateway IP to [MyPhoneNumber],[MyPCIP],[MySipGatewayIP]

**Comment by Teastears** [comment]
This is the console output while I use the Get Started demo with 4.0.86 -pre.

It is work good with this version

[ConsoleOutput_4.0.67_pre.txt](https://github.com/sipsorcery/sipsorcery/files/5472327/ConsoleOutput_4.0.67_pre.txt)

For privacy,I have replace my phone number ,PC IP and SIP Gateway IP to [MyPhoneNumber],[MyPCIP],[MySipGatewayIP]

**Comment by sipsorcery** [comment]
Thanks for the traces.

Another user has reported the same problem so something appears to have been broken somewhere.

The console outputs/SIP traces from your call attempts with `v4.0.67-pre` and `v4.0.86-pre` and  are almost identical and don't provide an obvious cause.

The next step is to take a look at the RTP traffic. Are you able to do a WireShark capture on your PC for a call attempt with  `v4.0.86-pre`? You can email it to me directly at aaron@sipsorcery.com if you don't want to reveal your IP addresses.

**Comment by sipsorcery** [comment]
Cancel that WireShark trace.

I think the issue has been found. It seems I have introduced a bug during some recent work on processing the remote SDP that sets a stream as inactive if there is no `a=sendrecv` attribute set. That's wrong, the default should be `sendrecv`.

**Comment by Teastears** [comment]
The result of WireShark capture has already send to your email.
