### ISSUE TITLE
How to use the SIP encryption

### ISSUE THREAD

**Issue by Teastears** [sipsorcery/sipsorcery#342]
My Sip gateway support encryption with VOS1.1
How to use it?

**Comment by sipsorcery** [comment]
There are some [SRTP](https://en.wikipedia.org/wiki/Secure_Real-time_Transport_Protocol) primitives in this library but to date they've only be hooked up for WebRTC and not SIP. That means you won't be able to use this library for SIP + SRTP without additional development.

What's VOS1.1? Is it related to [this product](http://www.vos3000.com/)?

**Comment by Teastears** [comment]
I am not sure what is VOS1.1,it looks like a protocol not a product
I think it is an encryption for SIP Message similar to RSA or Base64
Maybe we can ignore "VOS1.1",only discuss how to encrypt the SIP Message.
I hope to send an encrypted message, not send plaintext over the network like now

**Comment by sipsorcery** [comment]
If you want to confidentiality of SIP packets the only common option is to use a TLS transport couple with the `sips` scheme. The sipsorcery library supports TLS channels and `sips`.

You need to be aware that TLS is ONLY for the SIP messages. The RTP packets carrying the media will still be sent unencrypted and the audio/video can be easily extracted by anyone with access to the packets.

**Comment by Teastears** [comment]
Yes,I want to confidentiality of SIP packets，Only SIP messages.
But ,not TLS .


I think I figured out what is VOS1.1. 
It is a protocol. It use RC4 as encryption .
So how can I encrypt SIP message packets by RC4 before send it

**Comment by sipsorcery** [comment]
TLS is the only official option for SIP confidentiality (RC4 is a stream cipher that can be used by TLS, although it's not recommended due to known vulnerabilities according to [wikipedia](https://en.wikipedia.org/wiki/RC4)).

If you don't want to use TLS your only option is to use something like a VPN or IPSec. That will be feasible for point-to-point SIP where you control both end points but it's unlikely you'll be able to connect to any SIP Providers or public services.

**Comment by Teastears** [comment]
Is there any example for TLS?

**Comment by sipsorcery** [comment]
The [SIPCallServer demo](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/SIPCallServer) attempts to create and listen on a TLS channel.

````csharp
var localhostCertificate = new X509Certificate2(SIPS_CERTIFICATE_PATH);
_sipTransport.AddSIPChannel(new SIPTLSChannel(localhostCertificate, new IPEndPoint(IPAddress.Any, SIPS_LISTEN_PORT)));
````

**Comment by Teastears** [comment]
I can`t understand 
The class SIPTLSChannel looks like use Certificate by X509Certificate2 only.
How Can I let SIPTLSChannel use RC4
Or 
Is there any SIPTCPChannel

**Comment by Teastears** [comment]
I can`t understand 
The class SIPTLSChannel looks like use Certificate by X509Certificate2 only.
How Can I let SIPTLSChannel use RC4?
Or 
Is there any SIPTCPChannel other which use RC4?

Because my SIP Gateway is only support RC4.

**Comment by bormm** [comment]
What @sipsorcery was trying to explain was, that there is no option to use some obscure plain RC4 in the library. RC4 is a encryption algorithm. To get a working solution you need some key generation/exchange and more. You need a protocol, not a algorithm. You can't have a gateway that speaks just "RC4", it will speak some ???+RC4.

And what @sipsorcery also was telling you: TLS can use RC4, and TLS can be used for SIP. If TLS+RC4 is not what you are searching for, than you have to find out what protocol your gateway is speaking and implement it yourself.

**Comment by Teastears** [comment]
@bormm Thank you for the explanation ，I think  I'd better get in touch with the manufacturer of the Gateway and have a chat.
Thanks also to @sipsorcery
