### ISSUE TITLE
PCM voice to SIP

### ISSUE THREAD

**Issue by jafarulla15** [sipsorcery/sipsorcery#345]
I have done some work using your library and it's a great project you have done. Thanks a lot for your work. I am trying to send PCM voice to SIP server, using your Sipsorcery client. Actually I want to make bridge between mumble server and SIP using your Sipsorcery sip client. One way from SIP client to mumble is working fine. But when try to do reverse one, mean mumble to sip, not working.  Actually I am trying to create RTP packet from the PCM voice getting from mumble server. Actually I want to get some help to create RTP packet from PCM voice, so that I can send that to sip server. Thanks for your time.

**Comment by sipsorcery** [comment]
> But when try to do reverse one, mean mumble to sip, not working.

What's not working?

**Comment by jafarulla15** [comment]
Another one is, I can send voice form Sip client to webRTC, it's working fine. But can't send voice from webRTC to Sip - using your example. I am using cisco call manager as SIP server. Is there need any extra configuration. Thank you for your time.

**Comment by sipsorcery** [comment]
Actually there was a bug where the outgoing stream could be set inactive if an attribute was missing from the `SDP`. It was fixed in nuget version >= `v4.0.86-pre`.

**Comment by jafarulla15** [comment]
Sorry for late response. Yes, It's working perfectly with latest one. You are doing a great job. Really appreciable. Thanks for you valuable time.
