### ISSUE TITLE
WebRTC received video quality is low

### ISSUE THREAD

**Issue by adrientoub** [sipsorcery/sipsorcery#346]
I am trying to use this project to stream my iOS device camera to my computer using local network in real time. I used "examples/WebRTCExamples/WebRTCReceiver/" as a base for what I am trying to do and after setting up a SSL certificate it works correctly. My issue is that the video quality is quite bad compared to what I am expecting, and I can see that the bandwidth used is ~300kbps which seems very low.
I tried to increase the quality by editing the SDP to add a higher bandwidth limit but it did not have any effect.

Do you know if the current quality issue is a fundamental flaw of the technology used or if there is a way to increase it?

**Comment by sipsorcery** [comment]
> I am trying to use this project to stream my iOS device camera to my computer using local network in real time. 

Which browser are you using on your iOS device? Safari?

> Do you know if the current quality issue is a fundamental flaw of the technology used or if there is a way to increase it?

It won't be a fundamental flaw. It's most likely the video encoder properties being tuned for the most common use case and thus limiting the bandwidth consumption. 300Kbps is still likely to be a challenge in most parts of the World.

With Chrome there do seem to be some SDP attributes that can be set to adjust the encoder parameters see [here](https://stackoverflow.com/questions/57653899/how-to-increase-the-bitrate-of-webrtc#:~:text=Is%20there%20a%20way%20to,google%2Dmax%2Dbitrate%20works.) and [here](http://www.rtcbits.com/2016/11/controlling-bandwidth-usage-in-webrtc.html). I haven't played around with these options yet. 

With a quick poke around the libwebrtc source I also found this [javascript example](https://webrtc.googlesource.com/src/+/refs/heads/master/rtc_tools/loopback_test/loopback_test.js#80) which is using an SDP bandwidth attribute on the video announcement `b=AS:' + maxVideoBitrateKbps + '\r\n'`.

**Comment by adrientoub** [comment]
Thanks for your help.

Yes I am using Safari, but all browser on iOS must use Safari's engine behind the scenes so changing browser would not do anything in this case.

I tried to edit the SDP in the C# code to add the bandwidth to all media announcements but it did not have any effect, do you think that changing it from the JS side would have an effect? By the way, it feels weird that this parameter is not easily editable from the "MediaStreamTrack".

Agreed that 300 Kpbs might already be a lot for some people, but for the local network case it's really limiting.

**Comment by sipsorcery** [comment]
> Yes I am using Safari, but all browser on iOS must use Safari's engine behind the scenes so changing browser would not do anything in this case.

I would doubt that. Google's `libwebrtc` builds on iOS so I don't see why they wouldn't use it in Chrome. If you want to test out anything to do with WebRTC you're always better off using Chrome where possible since Google is the main driving force behind WebRTC.
 
> I tried to edit the SDP in the C# code to add the bandwidth to all media announcements but it did not have any effect, do you think that changing it from the JS side would have an effect? By the way, it feels weird that this parameter is not easily editable from the "MediaStreamTrack".

Maybe. There's lots of chatter about mangling this or that SDP setting to adjust encoding parameters but it's highly likely such settings would be browser specific. If you're going to try this approach then again Chrome will be the best option and checking the [libwebrtc source](https://webrtc.googlesource.com/src/) code to double check the latest options (as mentioned in my previous comment) is recommended.

> Agreed that 300 Kpbs might already be a lot for some people, but for the local network case it's really limiting.

I've done a bit of messing around with different video resolutions and it does indeed look like Chrome enforces a 300Kbps bandwidth limit.

If I use:

````javascript
var captureStm = await navigator.mediaDevices.getUserMedia({
	video: {
		width: 1920,
		height: 1080,
		frameRate: 30
	},
	audio: true
});
````
And then view the video stream stats on `chrome://webrtc-internals/` I get this:

![chrome_quality_limitation](https://user-images.githubusercontent.com/197660/98546537-c32ae200-228e-11eb-974d-f0ec080dc97d.png)

If I do the reverse and send a stream from a Windows Console application to Chrome the bandwidth consumed exceeds 300Kbps.

````csharp
WindowsVideoEndPoint winVideoEP = new WindowsVideoEndPoint(WEBCAM_NAME, 1920, 1080, 30);
````

![chrome_rtpin_bw](https://user-images.githubusercontent.com/197660/98546851-3a607600-228f-11eb-8b76-76158139274d.png)

**Comment by sipsorcery** [comment]
As a further note I did mess around with adding the SDP attributes mentioned above to an SDP offer generated by the sipsorcery library. Chrome did not seem to do anything differently based on those attributes.

It could be that what's necessary is to apply the attributes to Chrome's local SDP before setting it. For example in a demo like [this](https://github.com/sipsorcery/sipsorcery/blob/master/examples/WebRTCExamples/WebRTCReceiver/capture.html) the change could be:

````javascript
await pc.setRemoteDescription(new RTCSessionDescription(JSON.parse(evt.data)));
pc.createAnswer()
.then((answer) => {
  // ADD SDP ATTRIBUTES
  pc.setLocalDescription(answer);
})
.then(() => ws.send(JSON.stringify(pc.localDescription)));
````

> By the way, it feels weird that this parameter is not easily editable from the "MediaStreamTrack".

I agree. Mangling SDP is a precarious business. There is actually a [maxBitrate](https://www.w3.org/TR/webrtc/#dom-rtcrtpencodingparameters-maxbitrate) property specified but, at least in my version of Chrome, it's not supported.

````javascript
pc.onconnectionstatechange = () => {
	console.log("onconnectionstatechange: " + pc.connectionState);
	if(pc.connectionState === "connected") {
		pc.getSenders().forEach(sender => {
			if(sender.track.kind === "video") {
				console.log(sender);
				console.log(sender.getParameters());
				const params = sender.getParameters();
				console.log(`is active: ${params.encodings[0].active}.`);
				console.log(`maxBitrate: ${params.encodings[0].maxBitrate}.`);
			}
		});
	}
}
```` 

Output:

````
is active: true.
maxBitrate: undefined.
````

Which leaves SDP mangling in the browser as the most likely approach.

**Comment by adrientoub** [comment]
Thanks for your help. I tried using Chrome on iOS and it doesn't seem to have any WebRTC capability (which seems to be yet another Apple limitation).
I also tried to change the SDP locally by doing:
```js
pc.createAnswer()
    .then((answer) => {
        answer.sdp = answer.sdp.replace(
            /a=mid:1\r\n/g,
            'a=mid:1\r\nb=AS:8000\r\n');
        pc.setLocalDescription(answer);
    })
    .then(() => ws.send(JSON.stringify(pc.localDescription)));
```
and while the SDP does look to have changed it doesn't change the bandwidth used (and the quality).

This might be an iOS limitation and a solution would be to create an app to send high quality video, but using WebRTC would be so much simpler.
Looks like there is no way to make my scenario work until Apple decides to make some changes to Safari.

**Comment by sipsorcery** [comment]
I spent some more time messing around with this out of my own interest. Eventually I stumbled across this [example](https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/). I tested it on my iPad and, at least according to the bandwidth graph the page displays, it is possible to adjust the sending bit rate. It's doing so by adding the SDP bandwidth attribute.

**Comment by adrientoub** [comment]
Thanks for continuing to look at it, and indeed it seems to work when I launch this website on my phone.
However I cannot make it work for something that is not local.

I tried both changes made in the example; adding "sdp.replace(/c=IN (.*)\r\n/g, 'c=IN $1\r\nb=' + modifier + ':' + bandwidth + '\r\n');" instead of doing it after the "a=mid" part and changing directly the encoding parameter to update the maxBitrate (which in Safari is set to 0 before I changed it). All of this still results in a ~300 kbps bitrate.
I might be missing something I will try to have a more in depth look this weekend.

**Comment by sipsorcery** [comment]
A note for future reference, a semi-authoritative way of determining the current approaches to setting `maxBitrate` can be found in the [Web Platform Tests (WPT)](https://github.com/web-platform-tests/wpt/search?q=maxbitrate).

**Comment by leo0104** [comment]
I had a similar issue when streaming video from browser to server (sipsorcery). The bitrate stays at ~300kbps. Under chrome://webrtc-internals in the chrome browser the targetBitrate is 300000 for outbound-rtp.
![image](https://user-images.githubusercontent.com/88649311/212268758-511dfbac-9ce4-487e-af75-a8908bf20127.png)
As a solution to this, I modified the sdp created by the server to increase the targetBitrate to 2500000.
I create the video track on the server side for receiving the video like this:
```cs
void AddVideoToPeer(RTCPeerConnection pc)
{
   const int formatId = 108;
   var videoFormat = new VideoFormat(VideoCodecsEnum.H264, formatId);
   var h264CustomFormat = new SDPAudioVideoMediaFormat(
      SDPMediaTypesEnum.video,
      id: formatId,
      rtpmap: "H264/90000",
      fmtp: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f;x-google-max-bitrate=5000;x-google-min-bitrate=0;x-google-start-bitrate=2500");

   var localVideoTrack = new MediaStreamTrack(videoFormat, MediaStreamStatusEnum.RecvOnly);
   localVideoTrack.RestrictCapabilities(h264CustomFormat);

   pc.addTrack(localVideoTrack);
}
```
That results in this sdp:
```
a=mid:1
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f;x-google-max-bitrate=5000;x-google-min-bitrate=0;x-google-start-bitrate=2500
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=recvonly
```

After that change the targetBitrate in the chrome webrtc-internals is 2500000 and the video quality is much better.
