### ISSUE TITLE
How to renegotiate WebRTC media streams

### ISSUE THREAD

**Issue by moorecj** [sipsorcery/sipsorcery#348]
I have a project where I am trying to use Signaling to make changes to a media stream on the fly. I have the browser able to send the signal to my sipsorcery app and triggers a new offer/answer sequence.  However after the exchange the I seem to get stuck here:

[22:26:06 DBG] ICE connection state change to checking.

I was assuming I wouldn't have to do anything with ice candidates for this connection. As  they were already exchanged earlier. 

Is this currently possible using sipsorcery?

Thank you in advance for your help.

**Comment by sipsorcery** [comment]
How are you triggering the new offer from the browser? Can you provide a javascript snippet so I can attempt to replicate it?

> Is this currently possible using sipsorcery?

It's likely to be something missing in the sipsorcery library. ICE restarts and media re-negotiation have not been extensively tested yet.

**Comment by moorecj** [comment]
The code to trigger offer is nothing special at all just a simple websocket message.  I am using this message to reload the media at a new timestamp. 


`function sendSec(){		
	var temp = document.querySelector('#jumptosec').value;
	ws.send('jumpto:'+temp);
};
`

On the sipsorcery app side I have my own WebRtcWebSocketPeer to handle this message and trigger something like:
`
	var offerSdp = peerConnections[id].createOffer(null);
	await peerConnections[id].setLocalDescription(offerSdp);

	wsPeers[id].Context.WebSocket.Send(offerSdp.toJSON());
`

Which seems to exchange correctly but then gets hung up.

**Comment by sipsorcery** [comment]
I've had a closer look at the current support for SDP re-negotiation and the answer is this library doesn't currently support it in any meaningful way. It may partially cope with a new remote offer but even then probably not very well.

What's required is proper support for the WebRTC [Session Negotiation Model](https://w3c.github.io/webrtc-pc/#session-negotiation-model) and I've added #352 to capture that.

**Comment by sipsorcery** [comment]
Enhancement required for this issue is in #352. Closing.
