### ISSUE TITLE
I need to get the handheld radio with sip,H264

### ISSUE THREAD

**Issue by hulusimizrak** [sipsorcery/sipsorcery#349]
Hi,
I have to give the hand-held radio talk to the web screen
Is possible this software ?

Thank you

**Comment by sipsorcery** [comment]
I'm guessing you mean some kind of push-to-talk application for iOS or Android?

If so this library will only be able to provide you part of the solution. It can get your packets from one peer to the other and handle the connection set up, media negotiation etc. The bit missing is the hooks for the audio and video devices and video codecs.

If you are targeting a mobile platform and don't care about the programming language then you may be better off looking at something like the [Flutter WebRTC](https://github.com/flutter-webrtc/flutter-webrtc) plugin.

**Comment by hulusimizrak** [comment]
No, I need to show the wireless (walkie talkie) conversation on the web

**Comment by sipsorcery** [comment]
If it's a web only application then this library can't help you.

Try the official [WebRTC samples](https://webrtc.github.io/samples/).

**Comment by hulusimizrak** [comment]
I understand :(
https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples
what does this project do,won't it help me ?

**Comment by sipsorcery** [comment]
This project is a library to build client or server VoIP/WebRTC applications with .NET. Typically the application would one of:
 
  - Windows/macOS/Linux Console
  - Windows Desktop
  - Xamarin iOS/Android
  - Unity plugin.

If you are building an application that only involves browser based web clients communicating with each other then it's unlikely this library is what you're looking for.

**Comment by hulusimizrak** [comment]
How can I get spoken voices over the radio (walkie talkie) 
Do you have ready made code to recommend

**Comment by sipsorcery** [comment]
> How can I get spoken voices over the radio (walkie talkie)

I don't know.

> Do you have ready made code to recommend.

No.

**Comment by hulusimizrak** [comment]
Thank you
