### ISSUE TITLE
STUN Message Issue

### ISSUE THREAD

**Issue by alextatham** [sipsorcery/sipsorcery#350]
Hello,

I think I've stumbled across an issue with STUN while testing the WebRTC implementation with Kamailio using RTPEngine.

The RTPEngine server is logging that it is unable to process the STUN request due to failing to validate the attributes.  I captured the packets and could not see any issue so I took a trace using the native WebRTC stack on Android.  After looking at the RTPengine source code I think I've found it.

The RTP Engine code checks that the priority attribute is length = 4.  On the request generated by the SIPSourcery code the data transmitted is length 4 but the attribute says its length is 8.  Example of the first four bytes is: 00 24 00 08 and I guess this should be 00 24 00 04.

I think I'm close to locating the code lines where this may be.  I'm in RtpIceChannel.cs at around line 1256 of the current master branch.

I'll try and see if I can locate the exact line in the AM.  Any help would be appreciated.

Full copy of the packet in hex as below:

0000   00 1d aa ae 8c f0 c8 21 58 cf 48 5b 08 00 45 00
0010   00 70 26 86 00 00 80 11 0a 8d c0 a8 64 12 6d 49
0020   77 66 dd 46 e7 a6 00 5c f8 7d 00 01 00 40 21 12
0030   a4 42 55 58 55 48 48 4d 59 49 4b 53 45 4e 00 06
0040   00 0d 41 39 4f 6b 70 44 43 6d 3a 42 44 5a 43 00
0050   00 00 00 24 00 08 7e 1d 14 fe 00 00 00 00 00 08
0060   00 14 b9 68 59 4d 5f 90 14 1d b0 99 08 25 b5 dc
0070   0e 46 4a d6 d0 5a 80 28 00 04 3f 48 1e 9d

Thank you and goodnight!

**Comment by sipsorcery** [comment]
I was using a ulong (8 bytes) for the ICE candidate priority field in accordance with the WebRTC [specification](https://www.w3.org/TR/webrtc/#dom-rtcicecandidate-priority). Double checking the ICE RFC it does state the [STUN PRIORITY](https://tools.ietf.org/html/rfc8445#section-7.1.1) attribute should be between [1 and 2^31-1](https://tools.ietf.org/html/rfc8445#section-5.1.2), which is a 4 byte unsigned integer.

So as always when there's ambiguity I checked what `libwebrtc` (via Chrome) is doing and it's using a STUN PRIORITY attribute of 4 bytes. Hence I'll make the change so this library does the same.

**Comment by alextatham** [comment]
Hello,

I've tested this and it appears to be generating corrupt requests.  I think I know where it is.

It is line 146 of StunAttributes.  Change the type to uint.  I have submitted a pull request for this change.

I've compiled that and it works ok.

Thanks, Alex
