### ISSUE TITLE
ICE Candidates

### ISSUE THREAD

**Issue by alextatham** [sipsorcery/sipsorcery#354]
Hi, me again!

I've got calls working after implementing the change to the priority.  Thanks for that.

I've hit another snag, I'm having issues when trying to initiate both audio and video.  From what I can see ICE completes and stops but only provides candidates for the first media stream in the bundle.  Its not something specific to the type of media, it just only does the first one.

From what I can see RTPEngine then bulks at this.  I'm using RTPEngine as a proxy in front of a SIP server so trickle ICE doesn't really work.  Elsewhere I'm waiting for ice complete before sending SDP.  I've done the same here but it doesn't work.  I just added a loop in my code to see if complete is perhaps fired twice, thinking once for each stream, but no.

Is there anything I'm missing?  I'll start digging into the code in a bit.

Thank you.

Cheers, Alex

**Comment by sipsorcery** [comment]
Do you know if `RTPEngine` supports multiplexing audio and video?

The sipsorcery `RTCPeerConnection` ONLY supports multiplexed media hence it only negotiates a single ICE connection.

The underlying `RTPSession` class, which is designed for VoIP scenarios, does support separate RTP channels for audio and video but it does not currently have any ICE functionality.

**Comment by alextatham** [comment]
I see.  Well there's a bit more to it in my case, I'm actaully manipulating the SDP in transit and I'm passing the audio through to RTPEngine and I'm allowing the video to travel direct between the endpoints.  I don't think a multiplexed scenerio sounds like that would work.  Things like DTLS are going to fail in that scenerio I think.

Just looking at other options, does the RTC bridge examples provide the basis for code that might demultiplex the two streams?

**Comment by sipsorcery** [comment]
> Just looking at other options, does the RTC bridge examples provide the basis for code that might demultiplex the two streams?

If you can put a WebRTC Peer in front of `RTPEngine` then de-multiplexing the audio and video is straightforward. The [SIPToWebRtcBridgeVideo](https://github.com/sipsorcery/sipsorcery/blob/bedb5087eb35e5838328d46f7f5a06feff59fc9f/examples/WebRTCExamples/SIPToWebRtcBridgeVideo/Program.cs#L193) demo is an example of doing that.

**Comment by alextatham** [comment]
Hi,

I have made a solution to this by using an RTPSession and a PeerConnection on the client and then manipulating the SDP in transit to prove that it can be done.

Thanks, Alex

**Comment by konnextv** [comment]
Hi @alextatham ,

do you mind sharing your process to use a separate RTPSession? I guess you copy values from the RTCPeerConnection to the RTPSession and send only one media type to each?
I made it work with two separate RTCPeerConnections that receive manipulated SDP messages (one audio, one video) and merge the answers, but that does not seem like an elegant solution as all the ICE Operations are happening twice.
