### ISSUE TITLE
İp Phone Call/incoming

### ISSUE THREAD

**Issue by hulusimizrak** [sipsorcery/sipsorcery#356]
Hi Aaron,
can i make a call to ip phone ? 
or incoming call

**Comment by sipsorcery** [comment]
Yes.

**Comment by hulusimizrak** [comment]
wonderful :)
what project? 
(SıpExamples/CallHoldAndTransfer) ?

**Comment by hulusimizrak** [comment]
Thank you for reply,
which one incoming call project ?

**Comment by hulusimizrak** [comment]
RecordIncomingCall project is not work,
I can make a call but I cannot listen :( 
I am using windows, is it possible?
