### ISSUE TITLE
Sip Server

### ISSUE THREAD

**Issue by hulusimizrak** [sipsorcery/sipsorcery#357]
Hi again 
How ı can find sip server and account. (hostname)

**Comment by sipsorcery** [comment]
You need to find a SIP Provider or set up your own SIP server.

To save you some wasted effort be aware that to use a library like the one in this project you need a good understanding of how SIP/VoIP work. It will be very frustrating to try and learn a new API and the core concepts at the same time.

**Comment by hulusimizrak** [comment]
I understand,thank you
