### ISSUE TITLE
SRTP support

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#36]
Hi Aaron.

I've been working on a project for this, and the client has just switched me to a trunk setup that requires TLS and SRTP.

I looked at the source, and it seemed TLS was supported for SIPChannel, but although there were references to things like STRP_SIGNATURE_LENGTH, it also looked like all the related code was commented out.

I'm using 1.5.5.
Could you let me know if SRTP is supported in 1.5.5 or later?
Thanks

Roger

**Comment by sipsorcery** [comment]
Hi Roger,

SRTP has never been included in the main sipsorcery nuget package. The work I did with SRTP is in https://github.com/sipsorcery/sipsorcery/tree/master/sipsorcery-media and was for a WebRTC project rather than a SIP one.

Are you parsing and extracting RTP/SRTP packets yourself? Or do you want to support SRTP negotiation with SIP? 

If it's the latter there's nothing to do. The sipsorcery SIP stack will happily pass through arbitrary SDP packets including those ones that reference SRTP parameters. If it's the former you could use the porject mentioned above to get started but it's a big big job.

Regards,
Aaron

**Comment by rwil02** [comment]
Huh.  I had replied to this via the email function.

That was an amazingly fast  response :)
I was just after an idea of what was already available so I could discuss with the client.

I did a quick code search and I can see what look like SRTP client/server/session/etc classes inside SIPSorcery.Net

Particularly, RTSPSession has this:
// Hooks for DTLS and SRTP.
        public Action<byte[], int, Action<byte[]>> OnDtlsReceive;   // [buffer, length, Raw send callback method] Handler for any DTLS packets received.                
        public Func<byte[], byte[]> RtpProtect;                     // [out encrypted buffer, in buffer] Set this for SRTP protection of RTP packets.

**Comment by sipsorcery** [comment]
Yes the hooks are there and there is a managed C++ wrapper for the [Cisco libsrtp](https://github.com/cisco/libsrtp) library  in the sipsorcery-media project. There's not a lot to SRTP, the RTP packets are encrypted with AES and that's pretty much it (there are more options of course).

**Comment by rwil02** [comment]
That's good to know.
Apparently they should be able to configure a "Direct IP" alternative that means I won't have to use SRTP.
I was looking at the spec and going "hmm,3 of those and 2 of those, and 'some' of those, that's a lot of options"

**Comment by sipsorcery** [comment]
@kkdinesh if you're referring to the main [SIPSorcery nuget package](https://www.nuget.org/packages/SIPSorcery/) then there is only an incomplete RTP implementation available and no SRTP option.

The [SIPSorceryMedia nuget package](https://www.nuget.org/packages/SIPSorceryMedia/) was an experiment to wrap the Cisco libsrtp library. The experiment worked but I didn't get around to doing any SIP/VoIP testing with the wrapper. The project I was working on at the time was WebRTC.

**Comment by sipsorcery** [comment]
For anyone else interested in srtp it's now possible to install the Cisco library using Microsoft's vcpkg manager:

`vcpkg install libsrtp:x64-windows`

To use with C# is still a bit tricky as you need PInvoke or Managed C++. For an example of the latter see my [WebRtc demo](https://github.com/sipsorcery/sipsorcery-media/tree/master/examples/WebRtcDaemon) in the sipsorcery-media repo.

**Comment by palakkapoor** [comment]
Hi Aaron, we've been working on a project to emulate SIP Devices using SIP Sorcery.  Our project supports only SRTP and not RTP.  We tried to add media in our project using VoIPMediaSession class.

 var voipSession = new VoIPMediaSession(winAudio.ToMediaEndPoints());
                    voipSession.AcceptRtpFromAny = true;
                    
We could see the following sdp being sent over the wire and the call attempt was unsuccessful.

v=0
o=- 1431785656 0 IN IP4 127.0.0.1
s=sipsorcery
c=IN IP4 10.156.160.85
t=0 0
m=audio 59480 RTP/AVP 0 9 18 101
a=rtpmap:0 PCMU/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=ssrc:117641121 cname:0b814744-d699-48f0-b022-70d9f34b2d33

However, when we hardcoded the SDP as follows, the call attempt was successful but the call did not have any sound.

v=0
o=- 2000 2000 IN IP4 192.168.1.151
s=session
c=IN IP4 192.168.1.151
t=0 0
m=audio 6524 RTP/SAVP 9 104 103 111 18 0 8 97 118 101 13
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=mid:1
a=rtpmap:0 PCMU/8000
a=sendrecv
a=rtpmap:18 G729/8000
a=fmtp:111 bitrate=16000
a=rtpmap:8 PCMA/8000
a=rtpmap:97 RED/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtpmap:13 CN/8000
a=rtpmap:118 CN/16000
a=ptime:20
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:ifCF7SQo9DOjP7rcsI1Tsqyw2S0M4MwYczcRtqMM|2^31
a=crypto:2 AES_CM_128_HMAC_SHA1_32 inline:h1yAgAkEWuQqo1eGXtinqcQcAEVS5AQBQjtSwp6A|2^31
a=crypto:3 AES_256_CM_HMAC_SHA1_80 inline:HLsQ1mltT/h+hiuvpoPJD0K36pCrzlp7N5kYIoG6jztMmO7oaonR2Osc454sYQ==|2^31
a=sendrecv


Could you please guide us on how we can encrypt the RTP to support only SRTP and enable media in our calls? Your response would be highly appreciated.

**Comment by sipsorcery** [comment]
Hi,

Unfortunately, I can't give you a great answer. I only worked on the SRTP
for use with WebRTC and not with SIP.

At the SRTP level it should be identical for a SIP or WebRTC session. The
differences will be in the SDP. Another contributor added the SDP
processing for SIP and SRTP.

Sorry I couldn't be more help.

Regards,
Aaron

**Comment by palakkapoor** [comment]
Hi Aaron, could you point us to the respository link where SDP processing for SIP and SRTP is added? We would take a look at the implementation.

**Comment by sipsorcery** [comment]
[Here](https://github.com/sipsorcery-org/sipsorcery/blob/master/src/net/SDP/SDPSecurityDescription.cs) maybe?

**Comment by palakkapoor** [comment]
Thanks.  Is there an example code that can help us understand how to use this class?
