### ISSUE TITLE
SDP From Firefox creates an error

### ISSUE THREAD

**Issue by moorecj** [sipsorcery/sipsorcery#361]
Hello,

I was tried testing some WebRtc code against Firefox and setting the remote description fails where it works in Chrome.

This is the error in the log:
[10:12:43 ERR] Exception ParseSDPDescription. The rtpmap parameter cannot be empty for a dynamic SDPMediaFormat. (Parameter 'rtpmap')

This was happening in the provided examples as well, I tried, WebRTCWebcamServer and WebRTCReceiver and they both had the same error.

My Firefox version is 83.0 (64-bit)

Thank you

**Comment by sipsorcery** [comment]
Thanks for the bug report. I've found the bug in the sipsorcery code and will fix today.

**Comment by moorecj** [comment]
No problem, thank you for the quick response.
