### ISSUE TITLE
SipSorcery Media sound cuts out during playback

### ISSUE THREAD

**Issue by Shadoweh** [sipsorcery/sipsorcery#362]
Hello
I've met the issue with SipSorcery Media package.
The sound cuts out for some seconds, when I'm trying to play audio from file.
```
await _mediaSession.SendAudioFromStream(
    new FileStream(fileName, FileMode.Open),
    AudioSamplingRatesEnum.SampleRate8KHz);
```
So the audio playing as expected, than there is a gap about 2-3 seconds and audio continues from the place where it would be in 2-3 seconds. There was an assumption, that it's related to the internet connection, but I've checked and everything should be fine.
As I can see there two possible options:
1) Somebody will be able to suggest, how the issue can be fixed.
2) I'll stop using SipSorcery Media and start using the latest version of the SipSorcery, but I haven't found a way how the audio file can be played using it :(

I'm using
SIPSorcery Version="4.0.51-pre"
SIPSorceryMedia Version="4.0.50-pre"

Thank you in advance.

**Comment by sipsorcery** [comment]
I don't have an answer for option 1.

For option 2, playing audio files is largely the same as it always was:

`voipMediaSession.AudioExtrasSource.SendAudioFromStream(new FileStream(WELCOME_8K, FileMode.Open), AudioSamplingRatesEnum.Rate8KHz);`

The [PlaySounds](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/PlaySounds/Program.cs) demo has a full example.

**Comment by Shadoweh** [comment]
Thank you for the example
I'll try to use it.
Have a good day.

**Comment by Shadoweh** [comment]
Unfortunately, nothing has changed with the library update.
I'll add comment If I find any solution.

**Comment by sipsorcery** [comment]
Just to make sure you're aware the `SIPSorceryMedia` package was [deprecated](https://github.com/sipsorcery/sipsorcery-media) a while ago. If you tried out the demo linked to above you should have ended up using the `SIPSorceryMedia.Windows` package. There's not a lot of difference between the two as far as Windows Audio goes, both use `NAudio`.

Also if you're using the .NET Framework you'll find the generated audio sources and signals are very choppy. Using .NET Core improves things a lot for the reliability of timer callbacks and can produce reasonable audio streams. If the input is a microphone this doesn't apply as the hardware device is the timing source and should work equivalently in the Framework or Core.

**Comment by Shadoweh** [comment]
Thanks for the concern
I'm using core 3.1. Also, I've removed  `SIPSorceryMedia` package.
But instead of `SIPSorceryMedia.Windows` package, I'm using such construction
```
var audioExtrasSource = new AudioExtrasSource(
    new AudioEncoder(), new AudioSourceOptions { AudioSource = AudioSourcesEnum.None });

 _mediaSession = new VoIPMediaSession(new MediaEndPoints { AudioSource = audioExtrasSource });
```
Because, when I've tried to use `SIPSorceryMedia.Windows` there was sound interference

**Comment by sipsorcery** [comment]
In that case might be also worth checking the points mentioned on #273.

**Comment by Shadoweh** [comment]
Thank you, I'll check if our systems have something similar.
