### ISSUE TITLE
Registration stops working.

### ISSUE THREAD

**Issue by mattiaspihl** [sipsorcery/sipsorcery#363]
On some occations the registration stops working. A restart of the program is needed for it to work. 

I am using SIPRegistrationUserAgent for registration and I have version 4.0.90-pre of SipSorcery.

I have not been able to regreate the problem myself and unfortunately the logs I have have swedish exception message.

The exception bubbles up to the "top" of the program. And after it is thrown registration no longer works even though it looks like it is still trying. 

The exception (sorry for the swedish)
20201123 09:29:38.2291	Excep	App.xaml.TaskScheduler_UnobservedTaskException() | TaskScheduler Unhandled Exception System.AggregateException: Undantag för en uppgift upptäcktes inte vilket antingen berodde på väntande på uppgift eller vid åtkomst till dess undantagsegenskap. Av det skälet kastade slutförartråden det oupptäckta undantaget igen. ---> System.TimeoutException: Åtgärdens tidsgräns har överskridits.
   vid DnsClient.DnsUdpMessageHandler.<QueryAsync>d__9.MoveNext()
   --- Slut på stackspårning för interna undantag ---
---> (Internt undantag #0) System.TimeoutException: Åtgärdens tidsgräns har överskridits.
   vid DnsClient.DnsUdpMessageHandler.<QueryAsync>d__9.MoveNext()<---

SipSorcery log at that time.
20201123 09:29:36.5092	Debug	DoRegistration for sip:3.somename@ipagent.xxxx.se:5070.
20201123 09:29:38.5392	Warn	SIPDNS exception on A lookup. Query 52229 => ipagent.xxxx.se IN A on 10.99.1.1:53 timed out or is a transient error..
20201123 09:29:38.5452	Debug	Initiating registration to ipagent.xxxxx.se:5070 at udp:empty for sip:3.somename@ipagent.xxxx.se:5070.

Most dns lookups works just fine, and I have not been able to recreate this problem myself. But on occations it fails and after that a restart is needed.

Any idea what I can do to fix or prevent this?

**Comment by sipsorcery** [comment]
There was a bug where an empty DNS result was not being handled correctly in the `SIPRegistrationUserAgent`. It's fixed on `master` now.

**Comment by mattiaspihl** [comment]
Wow, that was quick! Thanks a lot!
