### ISSUE TITLE
RTP to VLC

### ISSUE THREAD

**Issue by mksbamford** [sipsorcery/sipsorcery#364]
I'm trying to setup an RTP video stream and send it to VLC (although the end goal is actually to send it to AWS)
I setup a simple program sending through green frames, but VLC isn't picking it up.
This should work right? Am I doing something wrong?

Here's the code:

    using System;
    using System.Linq;
    using System.Net;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.Logging;
    using Serilog;
    using Serilog.Extensions.Logging;
    using SIPSorcery.Media;
    using SIPSorcery.Net;
    using SIPSorceryMedia.Windows;
    using SIPSorceryMedia.Abstractions.V1;
    using Amazon;
    using Amazon.KinesisVideo;
    using SIPSorceryMedia.Encoders;
    using System.Collections.Generic;

    namespace AWS_WebRTC
    {
        class Program2
        {
            private static Microsoft.Extensions.Logging.ILogger logger = null;

            static RTPSession rtp;

            static async Task Main(string[] args)
            {
                Console.WriteLine("WebRTC Client Test Console");

                logger = AddConsoleLogger();

                var iPAddress = IPAddress.Parse("127.0.0.1");
                var endpoint = new IPEndPoint(iPAddress, 5004);

                rtp = new RTPSession(true, false, false);
                rtp.SetDestination(SDPMediaTypesEnum.video, endpoint, endpoint);
                rtp.SetDestination(SDPMediaTypesEnum.audio, endpoint, endpoint);

                SetupAVForSession(rtp, MediaStreamStatusEnum.SendOnly, out IAudioSource audioSource, out IVideoSource videoSource);

                const int Width = 256;
                const int Height = 256;
                const int DataSize = Width * Height * 4;
                var data = new byte[DataSize];
                for (int i = 0; i < DataSize; i += 4)
                {
                    data[i + 0] = 0;
                    data[i + 1] = 0xFF;
                    data[i + 2] = 0;
                    data[i + 3] = 0xFF;
                }

                while (true)
                {
                    videoSource.ExternalVideoSourceRawSample(1,
                        Width,
                        Height,
                        data,
                        VideoPixelFormatsEnum.Bgra);
                    await Task.Delay(1000);
                }
            }

            static void SetupAVForSession(RTPSession session, MediaStreamStatusEnum mediaStreamStatus, out IAudioSource audioSource, out IVideoSource videoSource)
            {
                audioSource = null;
                videoSource = null;

                session.OnTimeout += (mediaType) => logger.LogDebug($"Timeout on media {mediaType}.");

                IEnumerable<AudioFormat> audioSourceFormats = null;
                IEnumerable<VideoFormat> videoSourceFormats = null;

                if (mediaStreamStatus == MediaStreamStatusEnum.SendOnly || mediaStreamStatus == MediaStreamStatusEnum.SendRecv)
                {
                    audioSource = new AudioExtrasSource(new AudioEncoder(), new AudioSourceOptions { AudioSource = AudioSourcesEnum.None });
                    audioSource.OnAudioSourceEncodedSample += session.SendAudio;

                    videoSource = new SIPSorceryMedia.Encoders.VideoEncoderEndPoint();
                    videoSource.OnVideoSourceEncodedSample += session.SendVideo;

                    audioSourceFormats = audioSource.GetAudioSourceFormats();
                    videoSourceFormats = videoSource.GetVideoSourceFormats();

                    SetupAVSenderForSession(session, videoSource, audioSource);
                }

                session.addTrack(new MediaStreamTrack(audioSource.GetAudioSourceFormats(), mediaStreamStatus));
                session.addTrack(new MediaStreamTrack(videoSource.GetVideoSourceFormats(), mediaStreamStatus));
            }

            static void SetupAVSenderForSession(RTPSession session, IVideoSource videoSource, IAudioSource audioSource)
            {
                session.OnVideoFormatsNegotiated += (formats) => videoSource.SetVideoSourceFormat(formats.First());
                session.OnAudioFormatsNegotiated += (formats) => audioSource.SetAudioSourceFormat(formats.First());

                session.OnTimeout += (mediaType) => logger.LogDebug($"Timeout on media {mediaType}.");
            }

            /// <summary>
            ///  Adds a console logger. Can be omitted if internal SIPSorcery debug and warning messages are not required.
            /// </summary>
            private static Microsoft.Extensions.Logging.ILogger AddConsoleLogger()
            {
                var seriLogger = new LoggerConfiguration()
                    .Enrich.FromLogContext()
                    .MinimumLevel.Is(Serilog.Events.LogEventLevel.Debug)
                    .WriteTo.Console()
                    .CreateLogger();
                var factory = new SerilogLoggerFactory(seriLogger);
                SIPSorcery.LogFactory.Set(factory);
                return factory.CreateLogger<Program>();
            }
        }
    }

**Comment by sipsorcery** [comment]
What VLC command are you using to play the RTP stream? I'm pretty sure you need to add a command line parameter to map the RTP payload ID to a video type or use an SDP file.

Here is a similar [demo program](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/WebRTCtoFfplay) that plays a sipsorcery derived stream with FFPlay.

**Comment by mksbamford** [comment]
I'm not sure on the exact VLC command, but I know it supports rtp protocols. I just opened a network stream with url rtp://@127.0.0.1:5004 (I tested this using a 2nd VLC streaming a video using rtp, and that worked fine)

**Comment by mksbamford** [comment]
As I mentioned my end goal is AWS (Media Live), which doesn't support SDP just raw RTP. sipsourcery seems to assume the need for an SDP, do you know if it would be easy to change this?

**Comment by sipsorcery** [comment]
RTP is a transport protocol it doesn't dictate how the payloads it carries should be interpreted. The RTP `Payload ID` header field is used to allow both ends of the connection to agree on how a particular payload should be interpreted. The typical way to reach agreement is by exchanging a Session Description Protocol (SDP) message.

But there are certain`Payload IDs` that are "[well known](https://github.com/sipsorcery/SIPSorceryMedia.Abstractions/blob/ac6e1364dd21ef7ee2ac77d819d1c0df18133f84/src/V1/MediaEndPoints.cs#L35)" which means the payloads are "likely" to be of a specific format. The well known formats are predominantly for audio though and there are no well known formats for the main video codecs such as VP8, VP9, H264 or H265.

For an arbitrary RTP video packet, that's not a well known type, VLC player will have to make an educated guess as to the format. When it's VLC sending to VLC it can probably guess right. When the RTP source is not another VLC player such a guess is less likely to work. Attempting to handle RTP video streams without somehow negotiating the format, whether using SDP or some other mechanism, will be fragile at best. That's not a limitation of the sipsorcery library, AWS or VLC it's simply the state of the specifications.

All that aside, most software I've come across uses a `Payload ID` of 96 or 100 for the primary video format supported. If you're able to build the `SIPSorceryMedia.Encoders` assembly from source you could try changing the [default ID](https://github.com/sipsorcery/SIPSorceryMedia.Encoders/blob/b91fa707fc26bb19e0fb95daed7aeaefcf461d3e/src/VideoEncoderEndPoint.cs#L33) from 96 to 100 and maybe it will just work. Alternatively I'm pretty sure VLC player, and I'm guessing the AWS service, have a way to map `Payload IDs` to video formats. In VLC's case there are parameters you can add to the `rtp://@127.0.0.1:5004` URL to set different things.

**Comment by mksbamford** [comment]
So I stripped out all the RTCP/SDP stuff from the RTPSession class and now AWS is acknowledging the packets (although it is complaining that it doesn't support VP8, but that's a separate issue)
You might want to consider separating these concerns. i.e. if you know the endpoint and expected format, there is no need for RTCP/SDP, and in fact it turns out AWS doesn't support RTCP/SDP.

**Comment by sipsorcery** [comment]
> You might want to consider separating these concerns. i.e. if you know the endpoint and expected format, there is no need for RTCP/SDP, and in fact it turns out AWS doesn't support RTCP/SDP.

You're missing the point here. The "concerns" are separated in this library. You can send whatever RTP packets with whatever payloads you want. IF you want the other end to understand the RTP packets you're sending you need a way to inform it what those packets are.

**Comment by mksbamford** [comment]
The endpoint knows what is in the packet because it has a payload id.

**Comment by sipsorcery** [comment]
Nope.

Try and find VP8, VP9, H264 or H265 in the list of [known payload IDs](https://tools.ietf.org/html/rfc3551#section-6).

**Comment by mksbamford** [comment]
Well it doesn't matter if you are using a known ID, however this is an interesting point since AWS claims to support H264 over RTP, but it doesn't support RTCP/SDP or anything else.

**Comment by sipsorcery** [comment]
I don't mean to be offhand, I am well aware the acronym soup in real-time comms is ridiculous. If you want to work with a library like this it will save you a lot of pain if you understand, at a high level, how SDP and RTP are related. Here's a very brief, and very incomplete, synopsis:

 - RTP: Is a dumb protool that simply transports payloads from one end to the other. It provides a small number of headers to describe properties of the payload,

 - RTCP: Provides mainly statistical information about the RTP packets sent and received. Also used for other purposes such as feedback and limited control. For simple audio/video transmission you can often get by without needing RTCP.

 - SDP: Complicated protocol that is used to describe media sessions. At the simplest level it is used to map RTP payload IDs to specific audio and video formats. At more complicated levels it is used for anything and everything.

So you can do often do without RTCP. You can also often do with SDP if there is some pre-agreement or alternative mechanism to determine what RTP payloads contain.

A quick look at the AWS Media Live documentation reveal that it supports a [limited number of video codecs](https://docs.aws.amazon.com/medialive/latest/ug/inputs-supported-containers-and-codecs.html) for RTP. That "could" mean it determines the video codec by inspecting the RTP payloads and ignores the payload ID. VLC supports a much larger number of video codecs and thus is unlikely to use that approach. You could always use the [SIPSorceryMedia.FFmpeg](https://github.com/sipsorcery/SIPSorceryMedia.FFmpeg) package to send a H264 stream to the AWS service and see if it gets recognised.

**Comment by mksbamford** [comment]
Thanks for the summary, I am fairly new to this. However, everything I have read suggests that RTP should work on its own without knowledge of RTCP and SDP, whereas your RTPSession class relies on them, hence my suggestion they be separated.

**Comment by sipsorcery** [comment]
The `RTPSession` class **supports** SDP and RTCP it doesn't need them BUT as you'll find it you keep reading they are all inter-related. After all RTCP is part of the RTP specification.

I won't beat a dead horse. I don't see any bugs or improvements here but as always am interested in any progress you make.

**Comment by mksbamford** [comment]
I can't confirm this, as I don't have it working yet, but it looks like AWS treats the payload id as a program id. Allowing multiple programs to be sent over the same channel.
The expected encoding is defined in the Media Live settings. (where H264 is referred to as AVC)

**Identifying content in an RTP source:** https://docs.aws.amazon.com/medialive/latest/ug/extract-contents-rtp.html
"The content in an RTP input is always a transport stream (TS). The TS is made up of one program (SPTS) or multiple programs (MPTS). Each program contains a combination of video and audio."

**Input settings—Video selector:** https://docs.aws.amazon.com/medialive/latest/ug/input-video-selector.html
"If the input contains an MPTS, choose Selector settings and enter the program or PID to extract. If you don't specify the program or PID, MediaLive extracts the first video it finds.
If the input contains an SPTS, MediaLive extracts that video. There is no need to complete Selector settings. "

**Comment by sipsorcery** [comment]
There's no support in this library for the [MPEG Stream Encapsulation over RTP](https://tools.ietf.org/html/rfc2250). It looks like that's what the Amazon service requires.

This library supports the RTP packetisation for H264 as defined in [RFC6184](https://tools.ietf.org/html/rfc6184). That's the packetisation format supported for WebRTC and VoIP.

**Comment by sipsorcery** [comment]
No issue with the sipsorcery library was identified here.
