### ISSUE TITLE
Can I call gsm or pstn numbers with sipsorcery?

### ISSUE THREAD

**Issue by HarunDurmus** [sipsorcery/sipsorcery#365]
Can I use sipsorcery with sip trunk service like a pbx? For example, I have a paid sip trunk connection, is it possible to call gsm numbers with sipsorcery using this sip trunk connection?

**Comment by sipsorcery** [comment]
Yes. Calling the PSTN via a SIP Provider is the same as any other SIP call.

Something along the lines of the [GetStarted demo](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/GetStarted/Program.cs) should be all you need.

**Comment by HarunDurmus** [comment]
How to configure VoIP Providers / SIP Trunks for sipsorcery?

**Comment by HarunDurmus** [comment]
> Yes. Calling the PSTN via a SIP Provider is the same as any other SIP call.
> 
> Something along the lines of the [GetStarted demo](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/GetStarted/Program.cs) should be all you need.

**Comment by HarunDurmus** [comment]
> Yes. Calling the PSTN via a SIP Provider is the same as any other SIP call.
> 
> Something along the lines of the [GetStarted demo](https://github.com/sipsorcery/sipsorcery/blob/master/examples/SIPExamples/GetStarted/Program.cs) should be all you need.

How to configure VoIP Providers / SIP Trunks for sipsorcery?

**Comment by sipsorcery** [comment]
> How to configure VoIP Providers / SIP Trunks for sipsorcery?

Nothing special. Standard settings will generally work. If you're using a commercial provider then follow the instructions for a popular softphone such as CounterPath's Bria, Zoiper, MicroSIP etc.

**Comment by HarunDurmus** [comment]
> > How to configure VoIP Providers / SIP Trunks for sipsorcery?
> 
> Nothing special. Standard settings will generally work. If you're using a commercial provider then follow the instructions for a popular softphone such as CounterPath's Bria, Zoiper, MicroSIP etc.

Thanks a lot
