### ISSUE TITLE
Binary data in body gets corrupt.

### ISSUE THREAD

**Issue by henrik73** [sipsorcery/sipsorcery#372]
I have found an issue when requests contains binary data in the body. The raw bytes gets converted to a UTF-8 string. The conversion between binary raw data and UTF-8 encoded string and back again, as done by the library, is lossy.

I've solved this for incoming requests by adding a reference to the rawbuffer in SipRequest (patch attached below will give you an idea what I've did). The body containing binarydata is then read from the rawbuffer bypassing the body utf8-string normally used. I would like your opinion on this and how to solve it for outgoing requests as well. 

/Henrik

diff --git a/src/core/SIP/SIPMessageBase.cs b/src/core/SIP/SIPMessageBase.cs
index 9afc8df5..e0403209 100644
--- a/src/core/SIP/SIPMessageBase.cs
+++ b/src/core/SIP/SIPMessageBase.cs
@@ -37,8 +37,8 @@ namespace SIPSorcery.SIP
         /// <summary>
         /// The optional body or payload for the SIP request/response.
         /// </summary>
-        public string Body;
-
+        public string Body;
+
         /// <summary>
         /// Timestamp for the SIP request/response's creation.
         /// </summary>
@@ -65,5 +65,10 @@ namespace SIPSorcery.SIP
         /// when sending this request/response.
         /// </summary>
         public string SendFromHintConnectionID;
+
+        /// <summary>
+        /// Used for binary data payloads.
+        /// </summary>
+        public byte[] RawBuffer;
     }
-}
+}
diff --git a/src/core/SIP/SIPRequest.cs b/src/core/SIP/SIPRequest.cs
index df7b2489..9895b391 100644
--- a/src/core/SIP/SIPRequest.cs
+++ b/src/core/SIP/SIPRequest.cs
@@ -97,6 +97,7 @@ namespace SIPSorcery.SIP
                     sipRequest.SIPVersion = statusLine.Substring(secondSpacePosn, statusLine.Length - secondSpacePosn).Trim();
                     sipRequest.Header = SIPHeader.ParseSIPHeaders(sipMessage.SIPHeaders);
                     sipRequest.Body = sipMessage.Body;
+                    sipRequest.RawBuffer = sipMessage.RawBuffer;
 
                     return sipRequest;
                 }
diff --git a/src/core/SIP/SIPResponse.cs b/src/core/SIP/SIPResponse.cs
index 1254e1bb..9ccb90a7 100644
--- a/src/core/SIP/SIPResponse.cs
+++ b/src/core/SIP/SIPResponse.cs
@@ -7,7 +7,7 @@
 // Aaron Clauson (aaron@sipsorcery.com)
 // 
 // History:
-// 17 Sep 2005	Aaron Clauson	Created, Dublin, Ireland.
+// 17 Sep 2005	Aaron Clauson	Created, Dublin, Ireland.
 // 26 Nov 2019  Aaron Clauson   Added SIPMessageBase inheritance.
 //
 // License: 
@@ -101,7 +101,8 @@ namespace SIPSorcery.SIP
                 sipResponse.ReasonPhrase = statusLine.Substring(3).Trim();
 
                 sipResponse.Header = SIPHeader.ParseSIPHeaders(sipMessageBuffer.SIPHeaders);
-                sipResponse.Body = sipMessageBuffer.Body;
+                sipResponse.Body = sipMessageBuffer.Body;
+                sipResponse.RawBuffer = sipMessageBuffer.RawBuffer;
 
                 return sipResponse;
             }
@@ -197,95 +198,95 @@ namespace SIPSorcery.SIP
         {
             SendFromHintChannelID = localEndPoint?.ChannelID;
             SendFromHintConnectionID = localEndPoint?.ConnectionID;
-        }
-
-        /// <summary>
-        /// Helper method to create a SIP response for a SIP request. This method can be thought of as creating a 
-        /// vanilla (or no frills) response for a request. It's suitable for generating error responses. For requests that
-        /// require an action such as creating a call or registering a contact the response will require additional 
-        /// information and this method will not be suitable.
-        /// </summary>
-        /// <param name="sipRequest">The SIP request to create the response for.</param>
-        /// <param name="responseCode">The response code.</param>
-        /// <param name="reasonPhrase">Optional reason phrase to set on the response (needs to be short).</param>
-        /// <returns>A SIP response object.</returns>
-        public static SIPResponse GetResponse(SIPRequest sipRequest, SIPResponseStatusCodesEnum responseCode, string reasonPhrase)
-        {
-            try
-            {
-                SIPResponse response = new SIPResponse(responseCode, reasonPhrase);
-                response.SetSendFromHints(sipRequest.LocalSIPEndPoint);
-
-                if (reasonPhrase != null)
-                {
-                    response.ReasonPhrase = reasonPhrase;
-                }
-
-                SIPHeader requestHeader = sipRequest.Header;
-                SIPFromHeader from = (requestHeader == null || requestHeader.From != null) ? requestHeader.From : new SIPFromHeader(null, new SIPURI(sipRequest.URI.Scheme, sipRequest.LocalSIPEndPoint), null);
-                SIPToHeader to = (requestHeader == null || requestHeader.To != null) ? requestHeader.To : new SIPToHeader(null, new SIPURI(sipRequest.URI.Scheme, sipRequest.LocalSIPEndPoint), null);
-                int cSeq = (requestHeader == null || requestHeader.CSeq != -1) ? requestHeader.CSeq : 1;
-                string callId = (requestHeader == null || requestHeader.CallId != null) ? requestHeader.CallId : CallProperties.CreateNewCallId();
-
-                response.Header = new SIPHeader(from, to, cSeq, callId);
-                response.Header.CSeqMethod = (requestHeader != null) ? requestHeader.CSeqMethod : SIPMethodsEnum.NONE;
-
-                if (requestHeader == null || requestHeader.Vias == null || requestHeader.Vias.Length == 0)
-                {
-                    response.Header.Vias.PushViaHeader(new SIPViaHeader(sipRequest.RemoteSIPEndPoint, CallProperties.CreateBranchId()));
-                }
-                else
-                {
-                    response.Header.Vias = requestHeader.Vias;
-                }
-
-                response.Header.MaxForwards = Int32.MinValue;
-                response.Header.Allow = m_allowedSIPMethods;
-
-                return response;
-            }
-            catch (Exception excp)
-            {
-                logger.LogError("Exception SIPResponse.GetResponse. " + excp.Message);
-                throw excp;
-            }
-        }
-
-        /// <summary>
-        /// Used to create a SIP response for a request when it was not possible to parse the incoming SIP request. 
-        /// The response generated by this method may or may not make it back to the requester. Because the SIP 
-        /// request could not be parsed there are no Via headers available and without those the return network
-        /// path is missing. Instead a new Via header is generated that may get through if the requester is only
-        /// one SIP hop away.
-        /// </summary>
-        /// <param name="localSIPEndPoint">The local SIP end point the request was received on.</param>
-        /// <param name="remoteSIPEndPoint">The remote SIP end point the request was received on.</param>
-        /// <param name="responseCode">The response code to set on the response.</param>
-        /// <param name="reasonPhrase">Optional reason phrase to set on the response (keep short).</param>
-        public static SIPResponse GetResponse(SIPEndPoint localSIPEndPoint, SIPEndPoint remoteSIPEndPoint, SIPResponseStatusCodesEnum responseCode, string reasonPhrase)
-        {
-            try
-            {
-                SIPResponse response = new SIPResponse(responseCode, reasonPhrase);
-                response.SetSendFromHints(localSIPEndPoint);
-                SIPSchemesEnum sipScheme = (localSIPEndPoint.Protocol == SIPProtocolsEnum.tls) ? SIPSchemesEnum.sips : SIPSchemesEnum.sip;
-                SIPFromHeader from = new SIPFromHeader(null, new SIPURI(sipScheme, localSIPEndPoint), null);
-                SIPToHeader to = new SIPToHeader(null, new SIPURI(sipScheme, localSIPEndPoint), null);
-                int cSeq = 1;
-                string callId = CallProperties.CreateNewCallId();
-                response.Header = new SIPHeader(from, to, cSeq, callId);
-                response.Header.CSeqMethod = SIPMethodsEnum.NONE;
-                response.Header.Vias.PushViaHeader(new SIPViaHeader(new SIPEndPoint(localSIPEndPoint.Protocol, remoteSIPEndPoint.GetIPEndPoint()), CallProperties.CreateBranchId()));
-                response.Header.MaxForwards = Int32.MinValue;
-                response.Header.Allow = m_allowedSIPMethods;
-
-                return response;
-            }
-            catch (Exception excp)
-            {
-                logger.LogError("Exception SIPResponse.GetResponse. " + excp.Message);
-                throw;
-            }
+        }
+
+        /// <summary>
+        /// Helper method to create a SIP response for a SIP request. This method can be thought of as creating a 
+        /// vanilla (or no frills) response for a request. It's suitable for generating error responses. For requests that
+        /// require an action such as creating a call or registering a contact the response will require additional 
+        /// information and this method will not be suitable.
+        /// </summary>
+        /// <param name="sipRequest">The SIP request to create the response for.</param>
+        /// <param name="responseCode">The response code.</param>
+        /// <param name="reasonPhrase">Optional reason phrase to set on the response (needs to be short).</param>
+        /// <returns>A SIP response object.</returns>
+        public static SIPResponse GetResponse(SIPRequest sipRequest, SIPResponseStatusCodesEnum responseCode, string reasonPhrase)
+        {
+            try
+            {
+                SIPResponse response = new SIPResponse(responseCode, reasonPhrase);
+                response.SetSendFromHints(sipRequest.LocalSIPEndPoint);
+
+                if (reasonPhrase != null)
+                {
+                    response.ReasonPhrase = reasonPhrase;
+                }
+
+                SIPHeader requestHeader = sipRequest.Header;
+                SIPFromHeader from = (requestHeader == null || requestHeader.From != null) ? requestHeader.From : new SIPFromHeader(null, new SIPURI(sipRequest.URI.Scheme, sipRequest.LocalSIPEndPoint), null);
+                SIPToHeader to = (requestHeader == null || requestHeader.To != null) ? requestHeader.To : new SIPToHeader(null, new SIPURI(sipRequest.URI.Scheme, sipRequest.LocalSIPEndPoint), null);
+                int cSeq = (requestHeader == null || requestHeader.CSeq != -1) ? requestHeader.CSeq : 1;
+                string callId = (requestHeader == null || requestHeader.CallId != null) ? requestHeader.CallId : CallProperties.CreateNewCallId();
+
+                response.Header = new SIPHeader(from, to, cSeq, callId);
+                response.Header.CSeqMethod = (requestHeader != null) ? requestHeader.CSeqMethod : SIPMethodsEnum.NONE;
+
+                if (requestHeader == null || requestHeader.Vias == null || requestHeader.Vias.Length == 0)
+                {
+                    response.Header.Vias.PushViaHeader(new SIPViaHeader(sipRequest.RemoteSIPEndPoint, CallProperties.CreateBranchId()));
+                }
+                else
+                {
+                    response.Header.Vias = requestHeader.Vias;
+                }
+
+                response.Header.MaxForwards = Int32.MinValue;
+                response.Header.Allow = m_allowedSIPMethods;
+
+                return response;
+            }
+            catch (Exception excp)
+            {
+                logger.LogError("Exception SIPResponse.GetResponse. " + excp.Message);
+                throw excp;
+            }
+        }
+
+        /// <summary>
+        /// Used to create a SIP response for a request when it was not possible to parse the incoming SIP request. 
+        /// The response generated by this method may or may not make it back to the requester. Because the SIP 
+        /// request could not be parsed there are no Via headers available and without those the return network
+        /// path is missing. Instead a new Via header is generated that may get through if the requester is only
+        /// one SIP hop away.
+        /// </summary>
+        /// <param name="localSIPEndPoint">The local SIP end point the request was received on.</param>
+        /// <param name="remoteSIPEndPoint">The remote SIP end point the request was received on.</param>
+        /// <param name="responseCode">The response code to set on the response.</param>
+        /// <param name="reasonPhrase">Optional reason phrase to set on the response (keep short).</param>
+        public static SIPResponse GetResponse(SIPEndPoint localSIPEndPoint, SIPEndPoint remoteSIPEndPoint, SIPResponseStatusCodesEnum responseCode, string reasonPhrase)
+        {
+            try
+            {
+                SIPResponse response = new SIPResponse(responseCode, reasonPhrase);
+                response.SetSendFromHints(localSIPEndPoint);
+                SIPSchemesEnum sipScheme = (localSIPEndPoint.Protocol == SIPProtocolsEnum.tls) ? SIPSchemesEnum.sips : SIPSchemesEnum.sip;
+                SIPFromHeader from = new SIPFromHeader(null, new SIPURI(sipScheme, localSIPEndPoint), null);
+                SIPToHeader to = new SIPToHeader(null, new SIPURI(sipScheme, localSIPEndPoint), null);
+                int cSeq = 1;
+                string callId = CallProperties.CreateNewCallId();
+                response.Header = new SIPHeader(from, to, cSeq, callId);
+                response.Header.CSeqMethod = SIPMethodsEnum.NONE;
+                response.Header.Vias.PushViaHeader(new SIPViaHeader(new SIPEndPoint(localSIPEndPoint.Protocol, remoteSIPEndPoint.GetIPEndPoint()), CallProperties.CreateBranchId()));
+                response.Header.MaxForwards = Int32.MinValue;
+                response.Header.Allow = m_allowedSIPMethods;
+
+                return response;
+            }
+            catch (Exception excp)
+            {
+                logger.LogError("Exception SIPResponse.GetResponse. " + excp.Message);
+                throw;
+            }
         }
     }
 }
diff --git a/src/core/SIP/SIPTransport.cs b/src/core/SIP/SIPTransport.cs
index ad78887a..ddcf9a0d 100644
--- a/src/core/SIP/SIPTransport.cs
+++ b/src/core/SIP/SIPTransport.cs
@@ -832,7 +832,7 @@ namespace SIPSorcery.SIP
                                 return Task.FromResult(SocketError.InvalidArgument);
                             }
 
-                            SIPMessageBuffer sipMessageBuffer = SIPMessageBuffer.ParseSIPMessage(rawSIPMessage, localEndPoint, remoteEndPoint);
+                            SIPMessageBuffer sipMessageBuffer = SIPMessageBuffer.ParseSIPMessage(buffer, localEndPoint, remoteEndPoint);
 
                             if (sipMessageBuffer != null)
                             {
-- 
2.25.0.windows.1

**Comment by sipsorcery** [comment]
Any chance you could open this fix as a PR instead? It will make it a lot easier to compare the changes.

Also just out of interest what situation are you using SIP binary payloads with?

**Comment by henrik73** [comment]
I can see the patch I pasted into my message didn't turn out well. I created a PR: "https://github.com/sipsorcery/sipsorcery/pull/374". This is my first, so I hope I did that right? Please note this PR does not take into account of sending a SipMessageBase with a RawBuffer. This has to be figured out.
