### ISSUE TITLE
Need a conference for C#

### ISSUE THREAD

**Issue by alexRylov** [sipsorcery/sipsorcery#376]
We like SipSorcery, but our work requires a conference.

Is it possible to implement it in this solution? Is it possible to revise? Can development for money be acceptable?

**Comment by sipsorcery** [comment]
> Is it possible to implement it in this solution?

Probably.

There are different ways to implement multi-party conferencing application, see [WebRTC Multiparty Architectures](https://bloggeek.me/webrtc-multiparty-architectures/) and [Which Multi-Party WebRTC Option Should You Go With?](https://webrtc.ventures/2018/07/which-multi-party-webrtc-option-should-you-go-with/) for some further information.

This library does not have any audio or video mixing features so it doesn't support the `MCU` architecture. It should be able to support the other approaches.

As to implementing a conferencing application it's not something currently on my roadmap. There might be other developers around familiar with this library that could help. You could post in the new [Discussions](https://github.com/sipsorcery/sipsorcery/discussions) forum with a bit more info about what you're attempting to build.
