### ISSUE TITLE
Retransmission/NACK

### ISSUE THREAD

**Issue by rafcsoares** [sipsorcery/sipsorcery#377]
Hello again @sipsorcery 

Is there any retransmission protocol inside sip webrtc to handle packets lost in video transmission?

I saw a good information about this in blog below.

http://www.rtcbits.com/2017/03/retransmissions-in-webrtc.html 

This is super useful when handling with mobile platforms that contains unstable internet connections.

Thanks in advance
Rafael

**Comment by sipsorcery** [comment]
The mechanism you're referring to is [RTCP Feedback](https://tools.ietf.org/html/rfc4585).

There was a bit of work done on it see the [RTCPFeedback](https://github.com/sipsorcery/sipsorcery/blob/master/src/net/RTCP/RTCPFeedback.cs) class. An example of how to manually send feedback to request a key frame is [here](https://github.com/sipsorcery/sipsorcery/blob/c502eb894bd26d3245d999e1ad2ead364ce49262/examples/WebRTCExamples/WebRTCtoFfplay/Program.cs#L131).

The missing piece is the automatic sending of the feedback packets when a missing video frame is detected.

**Comment by rafcsoares** [comment]
Thanks @sipsorcery i will take a look on it!
