### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Terricide** [sipsorcery/sipsorcery#380]
I was testing one of my apps using Sipsocery and sometimes I was noticing huge cpu spikes. I created a dump file and noticed a bunch of threads the threadedassociation run method.

After establishing a webrtc connection if I pause execution (pause on the debugger) for 5 seconds of so I can duplicate a ton of threads as well

I was wondering what you though of this fix? Only allowing the timer to run at a time? You could also change new SemaphoreSlim to a higher number if you want more then one thread to run at a time.

static class SimpleSCTPTimer
    {
        private static SemaphoreSlim semaphore = new SemaphoreSlim(1);
        public static void setRunnable(Action r, long at)
        {
            new Timer(async (o) =>
            {
                try
                {
                    await semaphore.WaitAsync().ConfigureAwait(false);
                    r();
                }
                finally
                {
                    semaphore.Release();
                }
            }, null, at, Timeout.Infinite);
        }
    }

    
    I was trying to figure out of the java sctp library had any sort of limits to the number of threads.
    `class SimpleSCTPTimer implements SCTPTimer {
    protected  static Timer _timer = new Timer("SCTPTimer",true); 
    static int tno = 1;
    

    @Override
    public void setRunnable(Runnable r, long at) {
        TimerTask tt = new TimerTask(){
            @Override
            public void run() {
                r.run();
            }
            
        };
        _timer.schedule(tt, at);
    }
    
}`

**Comment by sipsorcery** [comment]
Overall I think the SCTP implementation will eventually need to be re-written. It's the flakiest bit of the library and I've never been that happy with its reliability. But that's a big task for another day.

In this particular case what about the [System.Timers.Timer](https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer?view=net-5.0) class?

**Comment by Terricide** [comment]
I think system.timers.timer would have the same issue? I think the issue this change is trying to solve if there is a slowdown somewhere it is very easy to overwhelm the system with nested calls into the run method and this change slows that down a bit.

here is what the dump looked like
![image](https://user-images.githubusercontent.com/1705108/102649407-570d8a80-4126-11eb-86f3-8b7eafccac06.png)

**Comment by Terricide** [comment]
After the change the webrtc connection seems really stable pushing 10mbps through it.
![image](https://user-images.githubusercontent.com/1705108/102650054-7f49b900-4127-11eb-9a3e-f0290a784a77.png)

**Comment by Terricide** [comment]
I think I spoke too soon.

![image](https://user-images.githubusercontent.com/1705108/102650949-e0be5780-4128-11eb-9246-0bd18af350e8.png)

**Comment by Terricide** [comment]
Sorry for spamming the comments. I wonder if this is a better solution? If another thread attempts to spawn a new timer the previous one is cancelled if it hasn't run?

static class SimpleSCTPTimer
    {
        private static Timer timer = null;
        public static void setRunnable(Action r, long at)
        {
            if (timer != null)
            {
                timer?.Dispose();
            }

            timer = new Timer((o) => { r(); }, null, at, Timeout.Infinite);
        }
    }

**Comment by sipsorcery** [comment]
It seems like such a crazy number of threads or are you actually creating hundreds of SCTP associations?

From a quick look at the `ThreadedAssociation` class it seems like it could create a single `Timer` instance and adjust that depending on the state. That's instead of creating a new `Timer` instance for every state change. Or alternatively use your idea of disposing of any existing `Timer` before creating a new one.

**Comment by Terricide** [comment]
Disposing the timer before creating a new one seems to be working great so far. I'm testing leaving the webrtc connection open for hours.

**Comment by sipsorcery** [comment]
Is this now resolved with #391?

**Comment by Terricide** [comment]
Yes, thanks
