### ISSUE TITLE
WebRTC: Fragmented PCMA/PCMU audio packets play incorrectly in browsers

### ISSUE THREAD

**Issue by techms** [sipsorcery/sipsorcery#394]
Method SIPSorcery.Net.RTPSession.SendAudioFrame() split large audio frames into several smaller frames to fit into MTU size. The method has the following comment:

// RFC3551 specifies that for audio the marker bit should always be 0 except for when returning
// from silence suppression. For video the marker bit DOES get set to 1 for the last packet
// in a frame.

So the method never sets the marker bit to 1 for audio but still uses the same timestamp value for all RTP packets belonging to one audio frame. Hovewer browsers, which receive an audio stream via WebRTC, can't handle such packets correctly. They treat them not as parts of a single frame but as independent packets with the same timestamp. I tested PCMA/PCMU audio codecs with large audio frames in the latest versions of Firefox and Chrome via WebRTC and got distorted sound. Not sure about other WebRTC supported audio codecs, but solution for PCMA/PCMU is the following: just set a different, proportionally calculated timestamp for every RTP packet when splitting a large frame.

I workaround this issue by splitting large frames into smaller frames before calling RTPSession.SendAudioFrame() method. But I think it could be handled inside RTPSession.SendAudioFrame().

**Comment by sipsorcery** [comment]
To be honest I hadn't considered an audio "frame" exceeding the MTU size. Out of interest what sample period are you using? To get a PCMU payload exceeding the MTU you must have sample period over 350ms. It's a lot larger than the typical 20 or 50ms periods and will most likely result in noticeable lag at the receiver.

As far as how best to handle large frame I guess it could be done in `RTPSession`. The payloads could be sliced into MTU sized chunks and the timestamp bumped accordingly.

**Comment by techms** [comment]
I have some old IP cameras which send PCMA/PCMU audio in 2048 byte frames (approx. 4 frames per second). So the duration of each audio frame is 1000 / (8000 / 2048) = 256 ms. I have a server which receives AV streams from such cameras via RTSP and retranslates them to client browsers via WebRTC.

When a camera sends 2048 byte audio frames via RTSP, it splits them into two RTP packets of different size with the same RTP timestamp and sets the marker bit of the second packet to 1. Obviously it violates RFC 3551, but widely used RTSP clients (VLC, ffplay) correcly handle and play such frames. That's where I get large audio frames from.
