### ISSUE TITLE
Sending an 'options' request

### ISSUE THREAD

**Issue by LADSoft** [sipsorcery/sipsorcery#397]
IS there some way to use this library to SEND an options request and monitor the response?     Our use case is we would like to use the library with IP speakers but need to supervise them to make sure they are 'there' at regular intervals.

**Comment by sipsorcery** [comment]
Yep sure, that's one of the simplest SIP scenarios. There's no dedicated example for it but you can take a look at the [SendOptionsTaskAsync](https://github.com/sipsorcery/sipsorcery/blob/5a5b0b4136f25a44dad0b5d2447e30941533ac2f/examples/sipcmdline/Program.cs#L308) in the `sipcmdline` app for one approach.

Note that the `sipcmdline` app can do exactly what you've asked. Send one or more OPTIONS requests and monitor the responses.

`sipcmdline -d sipsorcery.com`

to get all the the options

`sipcmdline --help`

**Comment by LADSoft** [comment]
thank you!
