### ISSUE TITLE
Regex.Match vs. Convert.ToInt

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#40]
Hi Aaron
i ran into an unexpected excpetion while adapting/using code for SIP Notify (SIP Monitor).
There are some occurances in code where strings are checked against regular expressions and Regex.Match returns true and then passed to Convert.ToInt method which fails with "InvalidFormatException".

Solution would be to change either the regular expression pattern to check for whole string is numeric (before: @"\d{1,2}" after: @"^\d{1,2}$") or to use int.TryParse method (preferred, additional check for numeric value necessary if it must be less than 100)

affected file: 
-SIPMonitorFilter.cs: ctor(filter), 3x Regex.Match should return false and "else" processing should execute.

Ralf

**Comment by sipsorcery** [comment]
C#7 can use local variables in TryParse now which means those regex's are no longer needed. I've fixed up the SIPMonitorFilter class.
