### ISSUE TITLE
Null Reference Error in ClientUserAgent

### ISSUE THREAD

**Issue by rwil02** [sipsorcery/sipsorcery#41]
If SIPClient has not completed InitialiseSIP before SIPClientUserAgent is created, you can end up passing in NULL for sipTransport.
Then later when a call starts, you get a Null Reference error elsewhere.
I'd suggest adding a null check into the constructor so you get an informative error back in the right place.

public SIPClientUserAgent(
            SIPTransport sipTransport,
            SIPEndPoint outboundProxy,
            string owner,
            string adminMemberId,
            SIPMonitorLogDelegate logDelegate
            )
        {
            m_sipTransport = sipTransport;

**Comment by sipsorcery** [comment]
I've made a commit that switches the SIPClient to use async initialisation which is the modern way to do it.
