### ISSUE TITLE
Peer to peer SIP communication with multiple Network interfaces

### ISSUE THREAD

**Issue by clem13480** [sipsorcery/sipsorcery#48]
Hi,

I am facing an issue with the sipsorcery library. I use the library only in peer to peer mode : call from 192.168.0.12 to 192.168.0.23 for example.

I cannot make the library work with multiple network interfaces on my computer. I'm working on a laptop, i got internet access with 192.168.0.10 address by wifi and I have a connection to an Axis intercom through ethernet with address : 192.168.2.10.

I made a wpf application that register every network interfaces channel, I want to be able to recieve calls from every network adapters. So my program use the method SIPTransport.AddSipChannel for the 192.168.0.10 AND 192.168.2.10 IP address. But when I try to call the device with the ip address 192.168.2.88, I get an error : cannot reach device on unreachable network. 
Then I notice in the CallFailed callback that the field m_localSIPEndPoint is 192.168.0.10 so it cannot reach the 192.168.2.x.

So I note that m_sipTransport.GetDefaultSIPEndPoint(m_serverEndPoint) method was only checking the protocol of the endpoint and return the first channel that match with UDP protocol. And both of the channels (192.168.0.10 and 192.168.2.10) use udp.

Is there a way in the current version to make this work ? Or do you I have to change the code of the call method inside the SIPClientUserAgent ?

Thank you.

Best regards.

**Comment by sipsorcery** [comment]
The networking logic in the SIPTransport class is not sophisticated enough to work out which interface to use when sending a SIPRequest or SIPResponse. If you don't specify which interface to use it falls back to the default SIP channel which is the first one that was created.

The network smarts is left up to the application and once it determines which interface to use you can set the LocalSIPEndPoint on the SIPRequest or SIPResponse objects BEFORE calling SendRequest or SendResponse. If that property is set then the SIPTransport class will attempt to honour it by sending the message from the interface matching the LocalSIPEndPoint property.

**Comment by clem13480** [comment]
Hello,

Thanks a lot for the answer. I managed to make it work by changing two files : SIPDialogue.cs and SIPTransport.cs. The SIPTransport now resolve the right SIPChannel registered to use according to the remote host. 

If you could just take a look and tell me if you can merge my changes to the master branch ? It would be great.

Thank you.
[sipsorcery-master-fixissue48.zip](https://github.com/sipsorcery/sipsorcery/files/1487020/sipsorcery-master-fixissue48.zip)

**Comment by clem13480** [comment]
I also posted a pull request ;)

**Comment by sipsorcery** [comment]
Closing as fix in PR #49.
