### ISSUE TITLE
ExtensionPayload is not initialized in RTPHeader ctor

### ISSUE THREAD

**Issue by letsRoll** [sipsorcery/sipsorcery#50]
In [RTPHeader](https://github.com/sipsorcery/sipsorcery/blob/master/sipsorcery-core/SIPSorcery.Net/RTP/RTPHeader.cs) class constructor when _HeaderExtensionFlag_ is set and `ExtensionLength > 0` the _ExtensionPayload_ field itself is not being set (not copied over from _packet_ parameter).

**Comment by sipsorcery** [comment]
Fixed.
