### ISSUE TITLE
Example softphonev2 does not work

### ISSUE THREAD

**Issue by njbrown09** [sipsorcery/sipsorcery#53]
I am getting a "Buffer full" error.

**Comment by apdevelop** [comment]
It can happen when `BufferedWaveProvider` receives more samples, than its buffer can contain (`BufferLength` property), and they are not consumed by `WaveOut` fast enough (for example, when excess RTP packets are received).

The simple _workaround_ is setting `DiscardOnBufferOverflow`  property of `BufferedWaveProvider` to `true` here:
https://github.com/sipsorcery/sipsorcery/blob/b971aad9015da5c99ed4fdce047962e13d0e2444/examples/sipsorcery-softphonev2/SIPSorcery.SoftPhone/Media/AudioChannel.cs#L62

**Comment by sipsorcery** [comment]
The softphone example now sets `DiscardOnBufferOverflow` to `true`. Thanks to @apdevelop for the tip.
