### ISSUE TITLE
SIPDialogue.Hangup Authentication ?

### ISSUE THREAD

**Issue by clem13480** [sipsorcery/sipsorcery#58]
Hi,

I am facing a problem with the hangout method. My application use a central SIPServer on which i register. Everything works fine. But when I want to hangup the call, I use the SipDialogue.Hangup method and I receive a 401 message from the SIP Server telling me i am not authorize, which is normal because the request does not contains the auths headers. Is that normal that the hangup method does not include the credentials, digest ... like all the other request ? 

Regards.

**Comment by sipsorcery** [comment]
According to the SIP standard the BYE (and all other in dialog requests) should include the same authentication header that was included in the INVITE request. When I was writing and testing that code I found some SIP Providers that didn't handle authentication headers in the BYE request so I took them out.

To fix the problem the authentication header from the original INVITE request could be copied to the BYE request in the Hangup method. Pull Requests gratefully accepted.

**Comment by clem13480** [comment]
Thank you for the answer. I noticed that the INVITE request is send first without the auth headers, and if a 401 response is receive, the same request is resend with the auth headers.

Do you think that the right way to fix that would be :
- Automaticaly include auth headers in the bye request ?
- Resend the bye request with auth headers if they are required ?

**Comment by clem13480** [comment]
Hi,

I just submit a pull request. I have fix the Hangup issue by creating two new Hangup methods. One inside the SIPUserClientAgent and one inside the SIPUserServerAgent. They first send a normal request, if 401 is received the same request is resent with the auth headers.

I also change the Cancel method inside the SIPUserClientAgent to automaticaly include the Auth headers.

Regards.

**Comment by sipsorcery** [comment]
Closed as fixed in PR #59.
