### ISSUE TITLE
Missing SDP setup attribute when creating answer for video and application data bundle

### ISSUE THREAD

**Issue by SimonAJT** [sipsorcery/sipsorcery#596]
Hello,

When  trying to establish a connection against a peer that is running GStreamer with the WebRTC plugin the answer created by SIPSorcery fails to include the setup attribute for the application data, which causes the peer to throw the following error: "media 1 is missing or contains an empty setup attribute". ([Source](https://github.com/GStreamer/gst-plugins-bad/blob/ca8068c6d793d7aaa6f2e2cc6324fdedfe2f33fa/ext/webrtc/webrtcsdp.c#L202))
I am uncertain whether this is a bug or not, but a workaround that "works" is manually adding the "a=setup:passive" or any other of the valid setup attributes. Like the following:
```cs
var answer = peerConnection.createAnswer(new RTCAnswerOptions {X_ExcludeIceCandidates = true});
answer.sdp += "a=setup:passive"; 
await peerConnection.setLocalDescription(answer);
// Code for sending the answer...
```

The created answer then becomes:
```
v=0
o=- 59500 0 IN IP4 127.0.0.1
s=sipsorcery
t=0 0
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVP 96
c=IN IP4 0.0.0.0
a=ice-ufrag:HPXD
a=ice-pwd:PHVGYKGMRITNOMVKDVRYJVOT
a=fingerprint:sha-256 81:2E:F5:A8:12:CA:11:53:CE:BE:68:23:64:7A:02:CB:0B:23:29:31:0B:07:B1:64:BB:1F:08:54:E9:EA:B4:E7
a=ice-options:ice2,trickle
a=mid:0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=42E01F;sprop-parameter-sets=Z00AKeKQDwBE/LNwEBAaUABt3QAZv8wA8SIq,aO48gA==
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=setup:active
a=sendrecv
a=ssrc:1912187107 cname:d046493e-db2f-40ee-9370-0b05fdf51623
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:HPXD
a=ice-pwd:PHVGYKGMRITNOMVKDVRYJVOT
a=fingerprint:sha-256 81:2E:F5:A8:12:CA:11:53:CE:BE:68:23:64:7A:02:CB:0B:23:29:31:0B:07:B1:64:BB:1F:08:54:E9:EA:B4:E7
a=ice-options:ice2,trickle
a=mid:1
a=sctp-port:5000
a=max-message-size:262144
a=setup:passive
```
Which can be set by GStreamer without issues.

Note that I am running only with a video track added and not a data channel even though the SDP states that we are ready to use both, but after this answer has been sent we can establish a connection without issues.

Thanks for your work, this library has been of great use!

**Comment by sipsorcery** [comment]
Thanks for the info. I've added a [unit test](https://github.com/sipsorcery-org/sipsorcery/blob/e76f974f2fc7e37eb9bd6fe19b7a1d1017d41454/test/integration/net/WebRTC/RTCPeerConnectionUnitTest.cs#L399) for the GStreamer offer and it is setting the ICE setup attribute correctly.

Below is the answer that got generated for that offer by the unit test. Both media announcements have the ICE setup attribute correctly set as `a=setup:active`. I wonder if something else is causing a problem with the ICE setup attribute? Are you able to post the code you are suing to create your `RTCPeerConnection` instance?

````
v=0
o=- 43765 0 IN IP4 127.0.0.1
s=sipsorcery
t=0 0
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVP 96
c=IN IP4 0.0.0.0
a=ice-ufrag:LYHL
a=ice-pwd:PTUYASALJHJCKHRASCSMDWHJ
a=fingerprint:sha-256 05:0F:33:B8:6C:42:03:DE:CE:07:8E:69:16:43:D0:AF:F5:8D:E9:AB:6B:EE:5F:35:B4:19:30:A9:03:0B:27:D0
a=setup:active
a=candidate:2944 1 udp 659136 192.168.11.50 52067 typ host generation 0
a=candidate:2488 1 udp 659136 192.168.0.50 52067 typ host generation 0
a=candidate:2705 1 udp 659136 2a02:8084:6180:500::12b 52067 typ host generation 0
a=mid:0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=42E01F;sprop-parameter-sets=Z00AKeKQDwBE/LNwEBAaUABt3QAZv8wA8SIq,aO48gA==
a=ice-options:ice2,trickle
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=sendrecv
a=ssrc:623516375 cname:2f2b0786-3af6-4542-857b-cddfbb10021b
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:LYHL
a=ice-pwd:PTUYASALJHJCKHRASCSMDWHJ
a=fingerprint:sha-256 05:0F:33:B8:6C:42:03:DE:CE:07:8E:69:16:43:D0:AF:F5:8D:E9:AB:6B:EE:5F:35:B4:19:30:A9:03:0B:27:D0
a=setup:active
a=mid:1
a=ice-options:ice2,trickle
a=sctp-port:5000
a=max-message-size:262144
````

**Comment by SimonAJT** [comment]
Glad I could be of any help! 
The creating the peer connection object is done with the following configuration and tracks:
```cs
RTCConfiguration peerConnectionConfig = new RTCConfiguration
{
	iceServers = iceServers,
	X_ICEIncludeAllInterfaceAddresses = true,
	bundlePolicy = RTCBundlePolicy.max_bundle,
	iceTransportPolicy = RTCIceTransportPolicy.all,
};
var pc = new RTCPeerConnection(peerConnectionConfig);

// Add video track
endpoint = new WindowsVideoEndPoint(new FFmpegVideoEncoder());
endpoint.RestrictFormats(format => format.Codec == VideoCodecsEnum.H264);

var videoTrack = new MediaStreamTrack(endpoint.GetVideoSinkFormats().First(), MediaStreamStatusEnum.RecvOnly);
pc.addTrack(videoTrack);

// Register event handlers ....
```

Again, we are including all interface addresses because of testing purposes, the ICE servers are extracted at an earlier point.

**Comment by SimonAJT** [comment]
Update: The Video track is now added in the following manner: 
```cs
// Add video track
var videoTrack =
	new MediaStreamTrack(new List<VideoFormat>
		{
			new VideoFormat(VideoCodecsEnum.H264, 100)
		},
		MediaStreamStatusEnum.RecvOnly);

pc.addTrack(videoTrack);
```
Since we have changed the project from .NET Core to Framework and we are no longer interested in decoding the frames using the endpoint.
Issue still persists as described above.

I should perhaps mention that we are using the NuGet package version 5.2.3

**Comment by grondinjc** [comment]
If it can help, I fixed a similar issue for which media would not be established. See issue #609.
Your issue looks similar. GStreamer appears to send media-id-tag as `video0 application1` and SipSorcery replies with `0 1`.
