### ISSUE TITLE
WebSocket support?

### ISSUE THREAD

**Issue by cristianmad** [sipsorcery/sipsorcery#61]
Hi,
 I built a basic SIP proxy&registrar using the library in order to test some Windows and mobile SIP UAs. Both the TCP and UDP channels are working fine. (using the SIPTCPChannel and SIPUDPChannel)

I now need to test a SIP UA implemented part of a web application. I was wondering if there is a way for the library to listen to WebSocket connections (wss - secure)? I was not able to see a "SIPWSChannel" implementation (assumed name).

Is there a way of achieving that?

Thanks!

**Comment by sipsorcery** [comment]
A web socket SIP channel is now available.

[Example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/GetStartedWebSocket ) project for creating a server for how to use with the SIPSorcery library.

[Article](https://sipsorcery.github.io/sipsorcery/articles/websocket-sipchannel.html) describing how to do a basic test with the [jssip](https://github.com/versatica/jssip-node-websocket) javascript library.
