### ISSUE TITLE
Support SIPDialogue.Refer

### ISSUE THREAD

**Issue by MarkusElmer** [sipsorcery/sipsorcery#67]
Hi
Would be nice to support the REFER command on SIPDialogue to be able to transfer a ongoing call.

**Comment by byQ96** [comment]
I have similar question but about call redirect with 302 Move temporarily message

**Comment by sipsorcery** [comment]
REFER requests are supported insofar as you can receive and then decide what to do with them. For example the main sipsorcery service allows the use of REFER requests and the logic is in https://github.com/sipsorcery/sipsorcery/blob/master/sipsorcery-core/SIPSorcery.Servers.Cores/SIPApplicationServer/SIPDialogueManager.cs (search for "refer"). Likewise with redirect responses, if you search this repo for "redirect" you'll find examples of where the responses are processed.

**Comment by MarkusElmer** [comment]
Thanks for your reply. I have seen this, but it only allows to react on REFER Requests and not to initiate them. So this issue is more like a feature request. Do you plan to integrate the possibility to initiate REFER Requests?

**Comment by sipsorcery** [comment]
I'm not sure what could be added as far as generating REFER requests go. There's nothing special about them except that they are **in dialogue** requests the same as BYE. If you look at SIPDialogue.GetByeRequest that's the basic method to create an in dialogue request. There are extra headers that need to be set for a REFER but from memory I think it's only `Refer-To` and `Referred-By`. All the complexity with REFER requests is inside the server that has to handle them. The client side is very basic.

**Comment by sipsorcery** [comment]
[Example](https://sipsorcery.github.io/sipsorcery/articles/calltransfer.html) now available.
