### ISSUE TITLE
How to call without Video?

### ISSUE THREAD

**Issue by nikitoSha** [sipsorcery/sipsorcery#68]
Hi.
Very good lib. Can you show, how to use only microphone (default mic) and talk via mic? All my video-devices not supported by this lib (I don't know, why). So, I need to make call only with voice. Sorry for my Russian English. Can you help me?

**Comment by nikitoSha** [comment]
I testing "softphone2". Outgoing calls works good, but I don't hear man from mobile phone and he can't hear me

**Comment by sipsorcery** [comment]
I haven't kept up with the audio/media side of things on Windows. I'd recommend taking a look at the NAudio project.

**Comment by sipsorcery** [comment]
The [UserAgentClient example](https://github.com/sipsorcery/sipsorcery/blob/master/examples/UserAgentClient/Program.cs) now demonstrates how to place a two way audio only call in a console application.

It relies on [NAudio](https://github.com/naudio/NAudio) for microphone input and speaker output.
