### ISSUE TITLE
Exception thrown: 'System.InvalidOperationException' in NAudio.dll

### ISSUE THREAD

**Issue by ingfraga** [sipsorcery/sipsorcery#69]
after de 4 or 5 call i get this error:

SIPSorcery.Softphone V2

Exception thrown: 'System.InvalidOperationException' in NAudio.dll

and the audio start to lag or cutting in pieces

**Comment by sipsorcery** [comment]
If the audio is getting choppy it's likely you've still got media flowing from some of the previous calls. This can happen if they weren't terminated correctly. The easiest way to track it down is to use Wireshark and do a packet capture and analyse the RTP streams.

**Comment by sipsorcery** [comment]
If there is any further information about this issue please feel free to re-open.
