### ISSUE TITLE
Multiple successful registration

### ISSUE THREAD

**Issue by ingfraga** [sipsorcery/sipsorcery#70]
this method

SIPRegistrationUserAgent_RegistrationSuccessful

trigger several times across the calls.

is that normal? expected?

**Comment by sipsorcery** [comment]
Registrations are independent of call activity. A registration interval is typically between 3 and 60 minutes so it would not be unusual for register traffic to occur while you're on a call. A registration is 4 or 5 SIP requests and does not include any media packets so it's not going to affect your call in any way.
