### ISSUE TITLE
add_OnVideoSourceRawSampleFaster' in type 'SIPSorceryMedia.Windows.WindowsVideoEndPoint

### ISSUE THREAD

**Issue by MRedaAmer** [sipsorcery/sipsorcery#776]
Method 'add_OnVideoSourceRawSampleFaster' in type 'SIPSorceryMedia.Windows.WindowsVideoEndPoint' from assembly 'SIPSorceryMedia.Windows, Version=0.0.31.0, Culture=neutral, PublicKeyToken=null' does not have an implementation

**Comment by Yasopp** [comment]
I also encountered this problem. Have you solved it？

**Comment by ChristopheI** [comment]
You use an old version of the package [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows): use at least [v6.0.3-pre](https://www.nuget.org/packages/SIPSorceryMedia.Windows/6.0.3-pre)

**Comment by MRedaAmer** [comment]
Hi , I did not solve it for yet , but author send to me this "You use an old version of the package SIPSorceryMedia.Windows<https://github.com/sipsorcery-org/SIPSorceryMedia.Windows>: use at least v6.0.3-pre<https://www.nuget.org/packages/SIPSorceryMedia.Windows/6.0.3-pre>"
________________________________
