### ISSUE TITLE
Receive SMS 10 Times with SIP server.

### ISSUE THREAD

**Issue by ducdanganhit** [sipsorcery/sipsorcery#85]
Hello, 
I use delegate event to receive SMS from server, but for each message, i get 10 times. 
I use this delegate: SIPTransportRequestReceived.
What was wrong? 
I printed the logs when use SIPTransportRequestReceived, just write logs of result. 

`SIPSorcery client user agent server example.
Press ctrl-c to exit.
[22:33:21 DBG] SIPUDPChannel socket on udp:0.0.0.0:5060 listening started.
[22:33:21 DBG] SIPUDPChannel listener created 0.0.0.0:5060.
[22:33:21 DBG] SIPUDPChannel listener created [::]:5060.
[22:33:21 DBG] SIPUDPChannel socket on udp:[::]:5060 listening started.
[22:33:21 DBG] SIP TCP Channel listener created 0.0.0.0:5060.
[22:33:21 DBG] SIP TCP Channel listener created [::]:5060.
[22:33:21 DBG] SIPTCPChannel socket on tcp:0.0.0.0:5060 accept connections thread started.
[22:33:21 DBG] SIPTCPChannel socket on tcp:[::]:5060 accept connections thread started.
COUNT 1
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:36
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0

COUNT 2
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:36
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0

COUNT 3
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:37
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0

COUNT 4
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:39
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0

COUNT 5
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:43
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0

COUNT 6
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:48
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0

COUNT 7
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:52
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0

COUNT 8
METHOD MESSAGE
Body Sender: 84904988888
Receiver: "1.01"
SMSC: 84900000066
SCTS: 19102922333128

0988765442114567
CreateBranchId z9hG4bKd0e5a7ebb20b9ae88c747546b5f8af2998e9c191
Created 10/29/2019 22:33:56
Header SIPSorcery.SIP.SIPHeader
LocalSIPEndPoint udp:0.0.0.0:5060
ReceivedRoute
RemoteSIPEndPoint udp:192.168.100.110:5060
SIPMajorVersion 2
SIPMinorVersion 0
SIPVersion SIP/2.0
StatusLine MESSAGE sip:192.168.100.7 SIP/2.0
UnknownMethod
URI SIPSorcery.SIP.SIPURI
SIPVersion SIP/2.0`

**Comment by sipsorcery** [comment]
The multiple retransmits are almost certainly because you are not sending a response or the response you are sending is not being recognised. The sender will retransmit the message up to 11 times to try and make sure it was received.

To tell the sender you got the message it's as simple as putting the two lines below in your incoming request handler.

````
SIPResponse okResponse = SIPTransport.GetResponse(sipRequest, SIPResponseStatusCodesEnum.Ok, null);
sipTransport.SendResponse(okResponse);
````

**Comment by ducdanganhit** [comment]
Aha. I got it. Thank you very much. :)
