### ISSUE TITLE
How can I run code TURN Server?

### ISSUE THREAD

**Issue by tvtoanitvn** [sipsorcery/sipsorcery#88]
There is no machine code for TURN Server to run. Please can give me the example code. In the example section there is no running code.

**Comment by sipsorcery** [comment]
Will whip something up, stay tuned.

**Comment by sipsorcery** [comment]
Example [program](https://github.com/sipsorcery/sipsorcery/blob/master/examples/StunServer/Program.cs) and [article](https://sipsorcery.github.io/sipsorcery/articles/stunserver.html) for a basic STUN server.

**Comment by sipsorcery** [comment]
Somehow I managed to read this issue and think you only required a STUN server.

Currently there's no TURN specific logic in this library. But there are some classes in the `net\STUNv2` directory that implement the STUN messages as per [RFC5389](https://tools.ietf.org/html/rfc5389) which are the building blocks for the TURN signalling messages.

What exactly is your use case? Do you only need TURN with UDP? I can't promise anything but maybe a prototype would be feasible or alternatively I'm happy to offer advice as to how you could implement it.

**Comment by tvtoanitvn** [comment]
Thank's @sipsorcery
