### ISSUE TITLE
How to Transfer a Call in Progress?

### ISSUE THREAD

**Issue by rodolphopedra** [sipsorcery/sipsorcery#89]
Hello!

Could you give an example?

"Redirect" works when the call is incoming, but not in progress.

**Comment by sipsorcery** [comment]
What do you mean by "in progress"?

The state of a SIP call prior to getting the final response (which can be an answer or failure condition) can be considered to be "in progress". Prior to getting answered the only way you're likely to be able to redirect a call is with the `3xx response`.

After the call is answered then `REFER` requests as per [RFC3515](https://tools.ietf.org/html/rfc3515) and [RFC5589](https://tools.ietf.org/html/rfc5589) can be used.

This [link](http://www.dialogic.com/webhelp/img1010/10.5.2/webhelp/sip_rfr_calltrans.htm) has some good examples of SIP flow diagrams for transfer operations with REFER requests.

**Comment by rodolphopedra** [comment]
Wich method i use with SipSorcery? Do you have an c# example?

**Comment by sipsorcery** [comment]
There's now an [example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/CallTransfer) along with an explanatory [article](https://sipsorcery.github.io/sipsorcery/articles/calltransfer.html).

The amount of code to set up a call and do the transfer is way too long. I'm more than happy to take suggestions on improvements in new issues if you have any ideas.
