### ISSUE TITLE
SIP-TCP: not really closing the socket on shutdown

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#9]
If there is a SIPTCPChannel which a client connected the socket isn't really freed when calling SIPTransport.Shutdown and exiting program.
It takes some time (around 30 sec) until socket is really freed and other application (actually the same but in another instance) can use it again.

I've found that "everybody" has this issue with System.Net.TcpListener and I tried to apply some suggested  solutions but nothing worked.

My last work around now is, to do a final read on the NetworkStream in SIPTCPChannel.Close() that blocks until Exception occurs. Only then the Application will exit. 

I'm wondering if there is a proper way i haven't discovered yet. 
-Listener.Server.Shutdown or Disconnect throws exception
-SocketOption.DontLinger has no noticable effect
-Calling Close() on accepted TcpClients has no noticable effect
-stepping with the debugger through the Net.TcpListener.Close() works for some inexplicable reason but not if run without stepping

Ralf

**Comment by sipsorcery** [comment]
I'll have a play around and see if I get the same thing. In the past I have had some success setting Win32 options directly on the socket that the TCP/UDP listeners are wrapping.

**Comment by sipsorcery** [comment]
I wasn't able to re-produce this on my Windows 10 machine. 

My experiment was:

1. Run the sipsorcery-allinone.exe application in a Command Prompt with Administrator privleges and with a SIP TCP soket configure for port 5060,

2. Register a Bria softphone on the sipsorcery-allinone application using TCP 5060 and also establish a telnet connection with "telnet 10.1.1.2 5060", so there are now two TCP connections established to the sipsorcery SIP stack. Run "netstat -anp tcp | grep 5060", results of which were:

  TCP    10.1.1.2:5060          0.0.0.0:0              LISTENING
  TCP    10.1.1.2:5060          10.1.1.2:51493         TIME_WAIT
  TCP    10.1.1.2:5060          10.1.1.2:51515         ESTABLISHED
  TCP    10.1.1.2:5060          10.1.1.2:51519         ESTABLISHED
  TCP    10.1.1.2:51515         10.1.1.2:5060          ESTABLISHED
  TCP    10.1.1.2:51517         10.1.1.2:5060          TIME_WAIT
  TCP    10.1.1.2:51519         10.1.1.2:5060          ESTABLISHED
  TCP    127.0.0.1:5060         0.0.0.0:0              LISTENING 

3. Kill the sipsorcery-allinone.exe with ctrl-c. Run "netstat -anp tcp | grep 5060", results of which were:

  TCP    10.1.1.2:5060          10.1.1.2:51493         TIME_WAIT
  TCP    10.1.1.2:5060          10.1.1.2:51515         TIME_WAIT
  TCP    10.1.1.2:5060          10.1.1.2:51519         TIME_WAIT
  TCP    10.1.1.2:51517         10.1.1.2:5060          TIME_WAIT

4. As quickly as possible restart the sipsorcery-allinone.exe application (would have been less than 10s). Run "netstat -anp tcp | grep 5060", results of which were:

  TCP    10.1.1.2:5060          0.0.0.0:0              LISTENING
  TCP    10.1.1.2:5060          10.1.1.2:51493         TIME_WAIT
  TCP    10.1.1.2:5060          10.1.1.2:51515         TIME_WAIT
  TCP    10.1.1.2:5060          10.1.1.2:51519         TIME_WAIT
  TCP    10.1.1.2:51517         10.1.1.2:5060          TIME_WAIT
  TCP    127.0.0.1:5060         0.0.0.0:0              LISTENING

5. Check that the telnet and Bria connections to TCP 5060 still work which they did.

It could be possible that the Windows OS will do things differently if the TCP connection is external. That's a lot harder to test so perhaps if you try the above experiment and see if you get the same results as me or whether you still experience the port in use issue.

**Comment by rj2Skipper** [comment]
Hi Aaron,

I pulled an allnighter and got to the bottom of my problem.
It WASN'T the tcpListener, but the outgoing connection (for SIP Register) that failed to close on exit

i've tried and retried a lot so my code looks a lot funny and i don't want to push it. maybe you can verify my finding ?

Ralf

**Comment by sipsorcery** [comment]
Wow an all nighter! Is the issue causing that much of a problem??

I've made a few changes to the SIPConnection class to try and get the TCP connections to shutdown immediately but based on my testing it hasn't helped. In my case the TCP sockets take about 30s to close after the process exits.

There are a lot of forum posts with people experiencing the same thing...

Reevant StackOverflow isues:
http://stackoverflow.com/questions/15325506/tcpclient-close-works-only-with-thread-sleep
http://stackoverflow.com/questions/425235/how-to-properly-and-completely-close-reset-a-tcpclient-connection
