### ISSUE TITLE
PlayDTMF or SendDTMF

### ISSUE THREAD

**Issue by rodolphopedra** [sipsorcery/sipsorcery#91]
Hi,

With a answered call, how to send dtmf digits?
Could give an example?

**Comment by sipsorcery** [comment]
The [example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SendDtmf) is literally in progress. Should be ready in a day or so.

**Comment by sipsorcery** [comment]
The [example program](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SendDtmf). An [explanatory article](https://sipsorcery.github.io/sipsorcery/articles/senddtmf.html) is also available.

The amount of code required to do there sort of things is still too much. I do plan on adding a higher level abstraction in the future as time permits.
