### ISSUE TITLE
New examples (Transfer and SendDTMF) as methods

### ISSUE THREAD

**Issue by rodolphopedra** [sipsorcery/sipsorcery#92]
What the plans to do methods as Answer, Hangup, Reject, etc for the new Examples (Transfer a call and SendDtmf)?

I am using the example codes, but if you put the news as Methods on a Softphone example, would be nice.

Sorry my english!

**Comment by sipsorcery** [comment]
Ok, will take a look. Most of the work is updating the softphone UI but that should be achievable.

**Comment by larcai** [comment]
Can you make it possible to receive DTMF tones?

**Comment by apdevelop** [comment]
> Can you make it possible to receive DTMF tones?

Do you mean detecting DTMF tones from voice channel ?

**Comment by larcai** [comment]
First of all, thanks for your great work with sipsorcery.

in RTPFrame.cs the byte[] GetFramePayload() is a bit difficult to use when receiving DTMF tones
I had to get all FramePackets by Header.PayloadType for DTMF (101)...  It could be made a bit simpler.
_audioChannel.DTMFSampleReceived(id, volume, duration) event would be helpfull.

It would be nice if you could add that to the sample softphone... to send and receive DTMF tones

**Comment by sipsorcery** [comment]
The softphone now supports blind transfers and can send DTMF events. Answer, hangup and reject were already available and show up when an incoming call is detected.

The [CallHoldAndTransfer](https://github.com/sipsorcery/sipsorcery/tree/master/examples/CallHoldAndTransfer) is the closest command line example application to the softphone and they have roughly the same capabilities.

Work will start shortly on detecting DTMF and attended transfers.
