### ISSUE TITLE
SIPResponse.RemoteSIPEndPoint no longer settable

### ISSUE THREAD

**Issue by boskjoett** [sipsorcery/sipsorcery#93]
I just took in a newer version of the SIPSourcery NuGet package and in the new version the SIPResponse.RemoteSIPEndPoint property is no longer settable.
What was the reason for this change? I was setting this property after calling SIPTransport.GetResponse().
Could you make it settable again, or add a constructor or method that allows me to set it?

**Comment by sipsorcery** [comment]
In almost all cases it's wrong to set the `RemoteSIPEndPoint` on a `SIPResponse`. The internals of the SIP transport and transaction classes should be taking care of it. And in cases where they can't (or dont' get an opportunity to) it can be left as null and the transport class will use the SIP headers to work out where the response should be sent.

The danger is if the `RemoteSIPEndPoint` on a response is set arbitrarily or incorrectly the response will end end up going to the wrong SIP agent or on the wrong connection and be discarded.

With all that being said I have adjusted the `SIPResponse` constructor to at least allow the `RemoteSIPEndPoint` to be set when the object is created. It's still safer to leave it as null but if you really need to it's there. It's available in the NuGet package >= 3.6.

**Comment by sipsorcery** [comment]
The use of the `LocalSIPEndPoint` and `RemoteSIPEndPoint` has now changed. They are now readonly properties that serve to indicate the local and remote end points request and responses were received or sent to.

It was getting very untidy using those properties for the additional purpose of determining which SIP end point to attempt to send a request from or two.

Two replacement properties have been added to provide a hint on which SIP channel and optionally connection should be used to send a message. The new approach is documented [here](https://sipsorcery.github.io/sipsorcery/articles/transport.html). 

The change is currently on `master` but has not been pushed in a nuget package yet. That's expected to happened shortly. Given the breaking nature of the change the next nuget package will bump the major version to become `4.0.0`.
