### ISSUE TITLE
Matching source code to NuGet releases

### ISSUE THREAD

**Issue by boskjoett** [sipsorcery/sipsorcery#96]
When I look in your Github repository there are no tags and no releases, and only two branches. So I wonder how I can find the source code that matches a given release of the SIPSorcery NuGet package.
This is not an issue as such, just a question.

**Comment by sipsorcery** [comment]
Hadn't thought about that one to be honest.

I had a look at [Json.Net](https://github.com/JamesNK/Newtonsoft.Json) which is potentially the most popular NuGet package. It has tags and releases.

I'll look into how to automate the releases. In the meantime I should be able to add some tags for the most recent NuGet package versions.

**Comment by sipsorcery** [comment]
Last 3 NuGet package releases now have corresponding tags.
