### ISSUE TITLE
How to choose IP address for SIP and RTP sockets

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/sipsorcery#97]
Originally this issue was titled `How do user agents deal with IPAddress.Any (0.0.0.0)` but that turned out to be a symptom rather than the cause. 

The root problem is the difficulty selecting an IP address to use for SIP and RTP sockets. SIP places IP addresses in:

- URI's
- Contact Header URI
- From and To Headers (these are not used for message routing so don't matter)
- Via Header
- Route Header
- SDP

To have the best chance of a SIP message exchange working correctly the correct IP address must be determined PRIOR to sending the message. But how can that be done? 

For example if a machine has two IP private addresses how can an application know which to use for internet hosts and which to use for other private hosts. If there is a VPN interface how does the application know the private address ranges on the other side of the VPN.

The answer is the application cannot know. The OS can determine the answer by applying it's IP routing table but that logic is not exposed to an application (as far as I know).

There is no perfect way to select the IP address a SIP agent should use. There are two alternatives that will always work for the `Transport Layer`:

- Iterate through all available IP addresses and create a separate socket for each.
- Create a socket with IPAddress.Any which achieves the same things as above BUT results in the local IP address being set as `0.0.0.0` or `[::]`.

Note that WebRTC has to deal with the same problem and uses [ICE](https://tools.ietf.org/html/rfc8445). Apart from the fact that it's a fairly complicated protocol it's not readily supported by most SIP SoftPhones (interestingly the [microsip](https://www.microsip.org/) softphone and [pjsip](https://trac.pjsip.org/repos/wiki/Using_Standalone_ICE) does both state ICE option).

Of the two options above using `IPAddress.Any` is by far the better option and solves additional challenges such as no need to determine which IP address needs to send a new request when the host is multi-honed.

The downside of using `IPAddress.Any` is `0.0.0.0` will be placed in SIP headers and SDP offers. This issue is to keep a track of observations about how different SIP software deals with `0.0.0.0`.

### Invite Response

Example of an INVITE response sent from the `UserAgentServer` example when listening on UDP `IPAddress.Any`:
````
[11:13:01 DBG] Response sent: udp:0.0.0.0:5060->udp:192.168.11.50:54498
[11:13:01 DBG] SIP/2.0 200 Ok
Via: SIP/2.0/UDP 192.168.11.50:54498;branch=z9hG4bK-524287-1---ca64380374eed342;rport=54498;received=192.168.11.50
To: <sip:1@192.168.11.50>;tag=JQMQCRNCDB
From: <sip:aaron@192.168.11.50>;tag=a614cb6c
Call-ID: 84929OWVlNTk3MTQ1NmY5MTljNDViYWRjYjAwZjI5NTM3YTk
CSeq: 1 INVITE
Contact: <sip:0.0.0.0:5060>
Server: www.sipsorcery.com
Content-Length: 131
Content-Type: application/sdp

v=0
o=- 61473 0 IN IP4 0.0.0.0
s=sipsorcery
c=IN IP4 0.0.0.0
t=0 0
m=audio 49000 RTP/AVP 0
a=rtpmap:0 PCMU/8000
a=sendrecv
````

| Softphone\Server   | ACK Received | BYE Received | RTP Accepted  | RTP Received  | Notes
| -------------            |:-------------:    | :-----:            | :-----:               | :-----:              | :-----: |
| Bria 4.8.1                | No                   | No               | Yes                   | No                  |  |
| MicroSIP 3.19.21    | No                   | No               | No                    | No                  | |
| Zoiper5 5.3.5          | No                   | No                | No                   | No                  | Response error with unparseable SDP* |

* Zoiper uses the [pjsip](https://www.pjsip.org/) SIP library. Additional testing with the pjsip `pjsua` application resulted in a failed assertion if `0.0.0.0` was returned as the RTP address in SIP OK response.

**Comment by sipsorcery** [comment]
### pjsip testing

Some early testing with pjsip indicates it suffers from exactly the same problem described above.

#### Test 1
On Windows 10 with a single private IP address on an Ethernet interface pjsip works correctly, as expected.

#### Test 2
After enabling the WiFi interface on my machine my network configuration is:

| PC 192.168.11.50 | <--> | 192.168.11.2 FW 192.168.0.2 | <--> | 192.168.0.1 MO | <--> Internet
|       192.168.0.137| <----------------------------------------------->|  192.168.0.1 MO | <--> Internet 

My machine now has two routes to the Internet via either Ethernet (192.168.11.0 network) or WiFi (192.168.0 network).

Starting the pjsip `pjsua` test app gives:

````
21:01:19.945  sock_common.c  .hostname IP is 192.168.11.50:0
21:01:19.945  sock_common.c  .default IP is 192.168.0.137:56761
21:01:19.952  sock_common.c  .Checking candidate IP 192.168.11.50:0, weight=2
21:01:19.953  sock_common.c  .Checking candidate IP 192.168.0.137:0, weight=3
21:01:19.953  sock_common.c  .Candidate 192.168.0.137:0 selected
````
The interface weightings are applied in `[pj_gethostip](https://github.com/pjsip/pjproject/blob/a441c67a5437a6c49cfb6e541cf769d9907dca68/pjlib/src/pj/sock_common.c#L735)`:

````
/* Weighting to be applied to found addresses */
WEIGHT_HOSTNAME	= 1,	/* hostname IP is not always valid! */
WEIGHT_DEF_ROUTE = 2,
WEIGHT_INTERFACE = 1,
WEIGHT_LOOPBACK = -5,
WEIGHT_LINK_LOCAL = -4,
WEIGHT_DISABLED = -50,
````
In this case the DHCP address assigned to my WiFi interface has been chosen as the default `192.168.0.137`.

**Comment by sipsorcery** [comment]
There are application layer utilities on Windows and Linux that can determine routes.

### Experiment

#### Step 1:

On a multi-honed Windows determine the default interface for a dummy network, in this case `192.168.100.0`.

##### Windows:
`PS> Find-NetRoute -RemoteIPAddress "192.168.100.22"`
````
IPAddress         : 192.168.0.137
InterfaceIndex    : 13
InterfaceAlias    : Wi-Fi
````

##### WSL:
`$ ip route get 192.168.100.22`
`none 192.168.100.22 via 192.168.0.1 dev wifi0 proto unspec src 192.168.0.137`

#### Step 2:

Add a new route to the dummy network using the non-default interface:

`route -p add 192.168.100.0 mask 255.255.255.0 192.168.11.2 metric 2 if 20`

````
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0     192.168.11.2    192.168.11.50    281
          0.0.0.0          0.0.0.0      192.168.0.1    192.168.0.137     35
         10.6.0.0    255.255.255.0    192.168.11.10    192.168.11.50     27
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
      192.168.0.0    255.255.255.0         On-link     192.168.0.137    291
    192.168.0.137  255.255.255.255         On-link     192.168.0.137    291
    192.168.0.255  255.255.255.255         On-link     192.168.0.137    291
     192.168.11.0    255.255.255.0         On-link     192.168.11.50    281
    192.168.11.50  255.255.255.255         On-link     192.168.11.50    281
   192.168.11.255  255.255.255.255         On-link     192.168.11.50    281
    192.168.100.0    255.255.255.0     192.168.11.2    192.168.11.50     27
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link     192.168.11.50    281
        224.0.0.0        240.0.0.0         On-link     192.168.0.137    291
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link     192.168.11.50    281
  255.255.255.255  255.255.255.255         On-link     192.168.0.137    291
===========================================================================
Persistent Routes:
  Network Address          Netmask  Gateway Address  Metric
         10.6.0.0    255.255.255.0    192.168.11.10       2
          0.0.0.0          0.0.0.0     192.168.11.2  Default
    192.168.100.0    255.255.255.0     192.168.11.2       2
===========================================================================
````

#### Step 3:

Repeat `Step 1` with the new route in place.

##### Windows:
`PS> Find-NetRoute -RemoteIPAddress "192.168.100.22"`
````
IPAddress         : 192.168.11.50
InterfaceIndex    : 20
InterfaceAlias    : Ethernet
````

##### WSL:
`$ ip route get 192.168.100.22`
`none 192.168.100.22 via 192.168.11.2 dev eth0 proto unspec src 192.168.11.50`

### Conclusion

There are application layer commands that can determine the route to a destination IP address AND provide the local interface and IP address for that route.

The question now is whether those commands can be accessed from a .Net component or whether it will require forking to a shell.

**Comment by apdevelop** [comment]
Have a look at [c# Know with which IP we use to communicate with another IP?](https://stackoverflow.com/questions/15086863/c-sharp-know-with-which-ip-we-use-to-communicate-with-another-ip). Looks like there are some methods for querying the routing table.

**Comment by sipsorcery** [comment]
The `socket.IOControl` works nicely but Windows only. Eventually I stumbled on the `NFS` code base and the [trick](http://git.linux-nfs.org/?p=steved/nfs-utils.git;a=blob;f=utils/mount/network.c;hb=HEAD#l1153) they use for the same thing.

The solution is as simple as calling `Connect` on a UDP socket. Somewhat counterintuitive but I'm very happy to now have a cross platform solution!

````
UdpClient udpClient = new UdpClient(AddressFamily.InterNetwork);
udpClient.Connect(IPAddress.Parse("192.168.100.55"), 0);
Console.WriteLine($"{udpClient.Client.LocalEndPoint}");
````
