### ISSUE TITLE
Code Formating Styles/StyleCop ?

### ISSUE THREAD

**Issue by rj2Skipper** [sipsorcery/sipsorcery#99]
Hey Aaron, 
i'm currently in the process of re-merging your changes in my fork (after letting it slide for more than 2 years) and like to submit my changes as pull-requests to master-branch once i'm done.
But there is the issue of different coding and formatting styles and I'd like to avoid future/current merge conflicts because of white spaces or lines.

Do you prefer a special formatting style i should adopt before pushing?

btw: when do you think you merge the ipaddrany-branch to master, because that looks like it could conflict with my current changes?

ciao Ralf

**Comment by sipsorcery** [comment]
Hi Ralf, as far as coding styles go I'm not that fanatical. I tend to stick to the default Visual Studio C# formatting rules and rely heavily on `ctrl-e-d`.

I don't use fxcop or similar. Do you have experience using a style tool on an open source project?

I plan to merge the `ipaddrany` branch tomorrow or maybe even today if things go well. You should definitely wait until it's merged as it does make some major changes to the `SIPTransport` class which tends to permeate throughout the rest of the code.

**Comment by rj2Skipper** [comment]
Hey Aaron,
I do definitely rely on VS formatting capabilities, too, but I changed these settings years ago, I think, and they might not match to default anymore (especially tabs vs. spaces and "smart" indenting). They might even differ between versions of Visual Studio.

I recently came across a project ([ManagedDism](https://github.com/jeffkl/ManagedDism)) which used [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) and with that extension VS showed a squiggly line anytime i wrote a line or completed block. But it also had the ability to apply enforced code formatting with some simple mouse-clicks on the entire file/project/solution.

Besides StyleCop VisualStudio (since VS 2017) has the ability of "traveling formatting rules" via [.editorconfig files](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017) .

I think it can be worth a try to create a new branch, format everything, and commit. I'll do that if you let me, but therefor the code should stay mostly unchanged for a while and we need to come to a common code styling convention before (allthough there are standard-settings, which could be THE common understanding or just the base of negotiation)

ciao Ralf

**Comment by sipsorcery** [comment]
Thanks for the info Ralf. I had a look over the info you provided and the `.editorconfig` option looks like a perfect fit. It works properly with the quick actions in Visual Studio and shouldn't impose any kind of burden on developers contributing to the library.

I've gone ahead and added a minimal `.editorconfig` to the top level directory and applied it to all the source files in this repo. Hopefully that should minimise whitespace changes on new PR's.
